SparkDevNetwork/Rock

- Rock/Workflow/Action/CheckIn/SaveAttendance.cs
This option allows you to reuse the code per family, instead of generating a unique code for each person.  See http://www.rockrms.com/Rock/Ask/Using/Questions/251.
Since the attendance code is the same across the family, pickup labels are much easier. We don't have to print multiple labels and the parent just has to keep track of one.
> Checkin/SaveAttendance: Add an option to reuse the code per family (disabled by default).

- RockWeb/Blocks/Security/RestKeyDetail.ascx.cs
- RockWeb/Blocks/Security/UserLoginList.ascx.cs
Also fixes UserDetail block showing incorrectly that it was. Closes #825.
> Fix new REST key not confirmed on create 

- RockWeb/Blocks/Security/LoginStatus.ascx
- RockWeb/Blocks/Security/LoginStatus.ascx.cs
Current Appearance:
Proposed Changes:
Not sure if this is the best way to make this change — so feel free to make changes on the branch if needed.
> Only show "Login" when user not logged in, not empty dropdown

- Rock/Model/Person.cs
Performance boost when adding multiple people/relationships
> Pass in optional RockContext to CreateCheckinRelationship

- Rock/Data/MigrationHelper.cs
Added new methods to the migrations helpers:
DeleteByGuid
DeleteAttributesByEntityType
DeleteAttributeValuesByWorkflowAction
DeleteWorkflowTriggersByWorkflowCategory
CreateWorkflowTrigger
DeleteWorkflowType
DeleteWorkflowActivityType
DeleteWorkflowActionType
> Feature migration helpers

- Rock.Rest/ApiController.cs
- Rock.Rest/App_Start/WebApiConfig.cs
This code adds a PATCH method to the Rock REST API.  Patch allows any entity's attributes or a subset of those attributes to be updated.
More info on PATCH here:
http://restcookbook.com/HTTP%20Methods/patch/
An example might be to change person 3's nickname and remove his title, I would would send the following JSON to
PATCH api/People/3
{
"SuffixValueId": null,
"NickName": "Bob"
}
> Feature api patch

- Rock/SystemGuid/Attribute.cs
Make it easier to import and reference Person Allergy attributes.
> Add a PERSON_ALLERGY system guid

- Rock/Data/DbContext.cs
In addition post-save triggers fire on delete instead of the post-delete triggers. Please watch this video for a better explanation (https://www.youtube.com/watch?v=L4dj_at0Fxk). The video was shot using the develop branch of Rock.
> Addresses #953 - Post-Delete Triggers never fire

- Rock/Web/UI/Controls/Grid/Grid.cs
- RockWeb/Blocks/Reporting/ReportDetail.ascx.cs
This is a second attempt at submitting this code, based on feedback from previous pull request.
@azturner, I have tried to incorporate all of your feedback. I've undone most of the refactoring, leaving only the new method "GetExportValue" which wraps a block of code that has the most significant changes anyway. Hopefully this is acceptable, otherwise I will change and resubmit.
@dcs619, your help was invaluable in working out the process of managing my GitHub fork and local working copy - thank you! The missing piece of the puzzle for me was setting up Spark/Rock as an additional remote which I could pull from directly to update my working tree - this makes the whole process much simpler than syncing my fork through GitHub and then pulling from there, and makes it much easier to submit …
> BugFix for Excel Export from Grid

- Rock.Rest/Controllers/AuthController.cs
- Rock/Rock.csproj
- Rock/Security/Authentication/Google.cs
- RockWeb/Styles/_rock-core.less
- RockWeb/Themes/DashboardStark/Styles/theme.css
- RockWeb/Themes/Flat/Styles/theme.css
- RockWeb/Themes/KioskStark/Styles/theme.css
- RockWeb/Themes/Rock/Styles/theme.css
- RockWeb/Themes/Stark/Styles/theme.css
This is my first pull request so I'm not sure if I've missed anything. I've been testing using Rockit rather than a local version of the develop branch if that makes a difference.
This is a Google OAuth2 authentication which heavily borrows from the existing Facebook authentication service. It currently requests first name, last name, email, id, and gender. It requires a client secret and client ID from the [Google Developers Console](http://console.developers.google.com), the process of how to obtain those is detailed [here](https://developers.google.com/identity/protocols/OpenIDConnect#getcredentials).
I made the decision not to request Google+ circles (given how little Google+ is used and the fact you'd need to request an additional scope for that) and a user picture (given the …
> Google Authentication

- RockWeb/Blocks/Reporting/ReportDetail.ascx.cs
I ran into this problem while developing a new Report Field.
After adding the field to a number of reports, I changed the name of the field in code and when I re-opened the report in Rock, an unhandled Exception occurred.
These changes allow "stale" fields to be displayed in the Report Editor with some minimal details preserved (Column Name, visibility) so that the Field can be easily updated to use the newer DataSelectComponent.
> Fix for exception when editing Report with stale DataSelectComponent

- Rock/Reporting/DataFilter/Group/GroupBranchFilter.cs
- Rock/Rock.csproj
Adds a data filter that returns all of the child Groups of a specified parent Group and (optionally) the parent itself.
> Added Data Filter "Group/Group Branch"

- Rock/Model/LocationService.Partial.cs
Added a verifyLocation boolean parameter (default true) + whitespace cleanup
> Fix #1025, add an option to create/retrieve location without verification

- Rock.Tests/SeleniumTestSuites/PersonTests/Edit Blargh McFlibbercutty Visit Information Attributes.html
@nairdo Here's my first pull request for Selenium tests. More to come...
> - Fixed a couple issues with Edit Person test.

- RockWeb/Blocks/CheckIn/AttendanceReporting.ascx.cs
also some whitespace cleanup @mikepetersonccv.
> Fix typo that was causing a "multiple controls with ID xxxxxx" message

- Rock/Web/UI/Controls/NewFamily/ContactInfo.cs
> Use Defined Values for Family Pane Labels

- Rock/Reporting/DataSelect/Person/PhoneNumberSelect.cs
Updated the phone number type report field to be consistent with the changes made in caf484805ba4a7e8d9277e722dff5bbc78807050
> Edit the phone number type report field to be consistent

- RockWeb/Blocks/Groups/GroupRegistration.ascx.cs
Option to have the form not auto populate data just because there is a
logged in user.  Allows the form to go in the Group Toolbox as a method
for leaders to add new members.
> Auto Fill Mode

- RockWeb/Blocks/Security/Login.ascx.cs
Allows the Login Block to have a default redirect page if there is no URL param for 'returnurl'.  Example use: redirect a user on the "My Account" page if no 'returnurl' is in query string.
> Add Redirect Page Setting

- Rock/Web/UI/Controls/Pickers/LocationAddressPicker.cs
- Rock/Web/UI/Controls/Pickers/LocationPicker.cs
- Fixed issue where Location Picker would not retain selected value for Location, Point or Geo-Fence. (Fixes #1115)
> Fix for Location Picker Selected Value

- Rock/Reporting/DataFilter/Group/ContainsGroupMembersFilter.cs
- Rock/Reporting/DataFilter/Group/ContainsPeopleFilter.cs
- Rock/Reporting/DataFilter/GroupMembers/ContainsPeopleFilter.cs
- Rock/Reporting/DataFilterComponent.cs
- Rock/Rock.csproj
- Rock/Utility/SettingsStringBase.cs
The purpose of these changes is to add Data Filters that can be used to join Groups, Group Members and People.
> + Added Data Filters to Link Groups and People

- RockWeb/Blocks/Crm/PersonDetail/Bio.ascx
- RockWeb/Styles/_helpers.less
> Suggested layout changes to bio block, added breakpoint namespaced alignment helper classes

- Rock/Model/CodeGenerated/DataViewService.cs
- RockWeb/Blocks/Reporting/DataViewDetail.ascx
- RockWeb/Blocks/Reporting/DataViewDetail.ascx.cs
Adds a copy button to duplicate an existing Data View. If the approach taken in this PR is OK, I intend to do the same for Reports.
> + Added a Copy command for Data Views.

- Rock/Model/CodeGenerated/ReportService.cs
- RockWeb/Blocks/Reporting/ReportDetail.ascx
- RockWeb/Blocks/Reporting/ReportDetail.ascx.cs
Uses the same method as #1187 for copying Data Views.
> + Added a Copy command for Reports.

- Rock/Lava/RockFilters.cs
```
<div class="panel panel-default panel-lavaitem">
<div class="panel-heading js-example-toggle clearfix">
<div class="row">
<div class="col-md-8">
<a name="Floor"></a>
<h1 class="panel-title">Floor</h1>
</div>
<div class="col-md-4">
<div class="pull-right">
<div class="example-toggle">
<i class="fa fa-circle-o"></i> Show Details
</div>
<div class="pull-right margin-t-sm">
<span class="label label-default pull-right">v4.0</span>
</div>
</div>
</div>
</div>
<p class="description">
Takes a number and returns the next smallest integer.
</p>
</div>
<div class="panel-body" style="display: none;">
<strong>Additional Details</strong>
<p>
</p>
<div class="examples">
<strong>Example:</strong>
<div class="example">
<div class="input">
<pre>"Values": {
"NumberOne": 2.6,
"NumberTwo": 7.2
}</pre> …
```
> + Added new Floor and Ceil Lava filters for rounding. Closes #1193

- RockWeb/Blocks/Reporting/DataViewDetail.ascx
- RockWeb/Blocks/Reporting/DataViewDetail.ascx.cs
- RockWeb/Blocks/Reporting/ReportDetail.ascx
- RockWeb/Blocks/Reporting/ReportDetail.ascx.cs
> + Added toggle button to Show/Hide Data View and Report Results.

- Rock/Web/UI/Controls/Pickers/ItemPicker.cs
> Change ItemPicker:  ClientID instead of ID

- Rock/Reporting/DataFilter/EntityFieldFilter.cs
- Rock/Reporting/DataFilter/GroupMembers/GroupMemberAttributesFilter.cs
- Rock/Rock.csproj
- Rock/Utility/SettingsStringBase.cs
... to filter Group Members by custom attributes.
> + Added Data Filter "Group Member/Attribute Value"

- RockWeb/Blocks/Core/LocationDetail.ascx.cs
https://github.com/SparkDevNetwork/Rock/issues/1394
> Fixed custom attributes not saving value on Locations

- Rock/Field/Types/CodeEditorFieldType.cs
> Fix 1420, code editor doesn't properly escape html values

- RockWeb/Blocks/Event/EventItemOccurrenceListByAudienceLava.ascx.cs
Essentially identical to #1387 -- just for a different variant of the block.
> Add context object to EventItemListLavaByAudience

- RockWeb/Blocks/Connection/ConnectionRequestDetail.ascx.cs
> Members of a campus-specific connection group can now add connection requests

- RockWeb/Blocks/Reporting/Dashboard/LiquidDashboardWidget.ascx.cs
Checking to make sure the Entity (setting for series partition) actually has a value selected before trying to apply it (else handles it from the page context).
> Fixes #1426 - Liquid Dashboard Widget series partition not changing

- RockWeb/Blocks/Groups/GroupFinder.ascx.cs
Fixes issue #1403 of linked pages not saving.
Fixes issue of Show Grid control showing the value of Show Map.
Added linked pages to Lava Output so both InfoWindow and LavaOverview get linked page references (before only InfoWindow did).
Applied standard code formatting
> Fixed settings not saving and added linked pages to lava

- RockWeb/Blocks/Finance/ScheduledTransactionListLiquid.ascx.cs
- RockWeb/Blocks/Finance/ScheduledTransactionSummary.ascx.cs
This fixes the summary to match what the list blocks are doing. (Like 5309be58abd38b885a0a3800b3fb83e7faa26b44)
> Update ScheduledTransactionSummary to include all schedules with same giving leader id.

- RockWeb/Blocks/Reporting/DynamicData.ascx
- RockWeb/Blocks/Reporting/DynamicData.ascx.cs
- Updates the dynamic data filter with DBA-friendly syntax
- Allows filtering by any text in the column, not just at the beginning
- Sets the filter visibility on by default 
@edmistj any issues with item 3?  Every time we've turned the filter on for a DD block, users have been ecstatic.
> [EN] Update the dynamic data block with better filters

- Rock/Security/Authorization.cs
This is a possible fix to issue #1467. I solved the problem by passing an optional RockContext into each method. This may or may not be the preferred solution.
> #1467 Passed RockContext through to fix database timeout

- Rock/Workflow/Action/CreateConnectionRequest.cs
via the Create Connection Request workflow action.
> Added ability to add comment to a new Connection Request

- RockWeb/Themes/Rock/Layouts/Site.Master
- RockWeb/Themes/Rock/Styles/theme.less
Transition doesn’t stutter thanks to CSS relative fix on
content-wrapper, and chained jQuery.
> Fixed Side Navbar Transition Toggle

- RockWeb/Blocks/Event/EventItemOccurrenceListByAudienceLava.ascx.cs
> Make campus optional for event by audience block

- Rock/Model/Person.cs
Fixes the issue raised by @mikepetersonccv in #1459.
This is a *way* better way of tackling this.
> Fix Format Age

- RockWeb/Blocks/Core/CampusContextSetter.ascx.cs
Set clear selection text to optional as the text will only be hidden if the attribute is blank
Added option to hide inactive campuses from list
> Tweaks to campus context setter

- Rock/Jobs/SendGroupEmail.cs
- Rock/Rock.csproj
> + Added SendGroupEmail Job

- Rock.Rest/Controllers/PeopleController.Partial.cs
This adds a new method to get the current person for the user who is currently authenticated to the Rock API.
> #1568 - Adding a GetCurrentPerson method to get the currently authenticated person.

- Rock/Lava/RockFilters.cs
This implements the slice filter from standard liquid: https://help.shopify.com/themes/liquid/filters/string-filters#slice
> - Adding slice to lava string filters.

- Rock/Web/UI/RockPage.cs
- RockWeb/Http404Error.aspx
- RockWeb/Themes/CheckinAdventureKids/Layouts/Site.Master
- RockWeb/Themes/CheckinBlueCrystal/Layouts/Site.Master
- RockWeb/Themes/CheckinPark/Layouts/Site.Master
- RockWeb/Themes/DashboardStark/Layouts/Site.Master
- RockWeb/Themes/Flat/Layouts/Site.Master
- RockWeb/Themes/KioskStark/Layouts/Site.Master
- RockWeb/Themes/Rock/Layouts/Site.Master
- RockWeb/Themes/Stark/Layouts/Site.Master
- RockWeb/error.aspx
Closed HTML elements that were preventing DOM navigation via XmlDocument().
> Closed HTML elements that were preventing DOM navigation

- Applications/Support Tools/Pills/AddLogin.aspx
- Rock/Store/PurchaseResponse.cs
- RockWeb/Blocks/Security/Login.ascx.cs
- RockWeb/Blocks/Store/PackageInstall.ascx.cs
- RockWeb/Styles/_rock-core.less
- RockWeb/Themes/DashboardStark/Styles/_variables.less
- RockWeb/Themes/KioskStark/Styles/_variables.less
Sorry about the previous botched pull request... attached a few too many commits
> Fixes spelling of authentication on less and .net

- Rock/Transactions/SendPaymentReciepts.cs
Added a new merge field for the whole Transaction entity in payment receipts.  This allows us to include information such as the transaction date/time, the payment method etc.
> Adding the whole transaction entity as a merge field option for receipts.

- Rock.Migrations/Migrations/Version 0.1 (Pre Beta)/Version 0.1.9/201403011329500_CommunicationsMenu.cs
- Rock.Migrations/Migrations/Version 4.0/Version 1.4.0/201505052324260_KioskPages.cs
- Rock/Model/CommunicationRecipient.cs
- Rock/Model/FinancialScheduledTransactionService.Partial.cs
- Rock/Model/GroupRequirementType.cs
- Rock/Model/PersonService.Partial.cs
- Rock/Rock.csproj
- Rock/Transactions/SendPaymentReceipts.cs
- Rock/Web/UI/Controls/Checkin Configuration Controls/CheckinArea.cs
- Rock/Web/UI/Controls/Communication/ChannelControl.cs
- Rock/Web/UI/Controls/Communication/Email.cs
- Rock/Web/UI/Controls/Communication/Sms.cs
- RockWeb/Blocks/CheckIn/Config/CheckinTypeDetail.ascx
- RockWeb/Blocks/Communication/CommunicationDetail.ascx.cs
- RockWeb/Blocks/Communication/TemplateList.ascx.cs
- RockWeb/Blocks/Crm/PersonDetail/EditPerson.ascx
- RockWeb/Blocks/Crm/PersonDetail/EditPerson.ascx.cs
- RockWeb/Blocks/Crm/PersonSearch.ascx.cs
- RockWeb/Blocks/Crm/PersonUpdate.Kiosk.ascx.cs
- RockWeb/Blocks/Finance/TransactionEntry.ascx.cs
- RockWeb/Blocks/Groups/GroupTypeDetail.ascx
- RockWeb/Http404Error.aspx
- RockWeb/Plugins/readme.txt
- RockWeb/Readme.txt
Found a few spelling mistakes using the `readme.txt` file as a guide.
> Fix spelling mistakes

- RockWeb/Styles/_blocks-checkinadmin.less
- RockWeb/Styles/_blocks-communication.less
- RockWeb/Styles/_blocks-core.less
- RockWeb/Styles/_blocks-crm.less
- RockWeb/Styles/_blocks-reporting.less
- RockWeb/Styles/_checkin-core.less
- RockWeb/Styles/_components.less
- RockWeb/Styles/_dashboard.less
- RockWeb/Styles/_modal.less
- RockWeb/Styles/bootstrap-colorpicker/colorpicker.less
DRYing up LESS, and ran CSScomb on `_checkin-core.less` which failed previously.
> Cleanup / DRY up LESS files

- .github/ISSUE_TEMPLATE.md
Make it easy as possible for users to submit, and developers to reproduce issues by requesting/requiring enough diagnostic detail.
Checkboxes 😉
> Update issues template to include checkboxes

- Rock/Field/Types/RangeSliderFieldType.cs
Yes
SparkDevNetwork/Rock#1845
it fixes the index for the range slider max control
resolves SparkDevNetwork/Rock#1845
> grab range slider controls by correct index

- Rock/Web/UI/Controls/NewFamily/MembersRow.cs
- RockWeb/Blocks/Crm/PersonDetail/AddGroup.ascx.cs
YES!
Somebody at CCV wanted the New Family block to prompt for middle name
Let them prompt for middle name if they want to
Added a "Show Middle Name: Block Option to the Crm\PersonDetail\AddGroup block.  It defaults to false, but can be enabled.  If enabled, it will show an edit box for middle name and add the person with the middle name specified.
None
_If your change effects the UI or needs to be documented in one of the existing [user guides](http://www.rockrms.com/Learn/Documentation), please provide the brief write-up here:_
> + Added option to prompt for middle name in the New Family Block

- Rock/Model/PersonService.Partial.cs
- database/Functions/ufnCrm_GetSpousePersonIdFromPersonId.sql
Yes
Another church reported in Slack that the Get Spouse SQL function was running extremely slowly in a large query.
Rewrote the SQL function to match the corresponding C# function. Modified it from there to better guess who the spouse is.
First I fixed the speed issue, which was due to some incorrect joins that were producing bad results in some cases (first commit).  Then I rewrote the query to be simpler and …
> Fixed the Get Spouse SQL function and improved logic in both SQL and C#

- RockWeb/Themes/Flat/Assets/Lava/RegistrationListSidebar.lava
- RockWeb/Themes/Rock/Assets/Lava/RegistrationListSidebar.lava
- RockWeb/Themes/Stark/Assets/Lava/RegistrationListSidebar.lava
Links in the stark theme are missing a slash, per issue #1862 
Adds a slash, fixes link
Add a slash
None
N/A
N/A
> #1862 - Added missing slash to registration link

- Rock/Model/Person.cs
- RockWeb/Blocks/Finance/ContributionStatementLava.ascx.cs
Yes
Issue #1859 
To improve the selection of a mailing address for the contribution statement.
Created a GetMailingLocation() function that will select the best of all available addresses (across multiple families when applicable).
If the person is part of a giving group, this family's addresses will be prioritized, and it will first look for an address that is both marked Mailing and Mapped. If that does not …
> Improved Contribution Statement address selection

- Rock/Jobs/CalculateMetrics.cs
yes
When calculating Metrics via Source SQL and the MetricValueDateTime column contained more than one date, the job could create duplicate metric values.
We have a metric that runs every night to calculate volunteer attendance.  Most of the attendance is on Sunday, but there are some volunteer opportunities during that week that need to be tracked.  That attendance may be checked in live, but can also be posted later by a staff member.  With this change, …
> - Prevent CalculateMetrics from creating duplicates

- Rock/Reporting/DataFilter/Person/InLocationGeofenceFilter.cs
- Rock/Rock.csproj
Yes
We need a way to find everyone within a neighborhood so we can connect them to their neighbors.
This will allow us to use or create a geofence in a dataview or dynamic report to locate people.
I created a new filter similar to the ingroupgeofence filter
It should have no additional implications.
This request requires #1904 in order to work properly.
> Added a person report filter to find people within a geofence

- Rock/Model/GroupLocationService.Partial.cs
Yes
We have just shy of 200,000 group locations in our database. We are looking into connecting people in their neighborhoods and we noticed that searching for all people in a small geofence takes about 30 seconds.  
We want to find all of the groups within an area quickly.
We suspected that SQL Server 2016 was doing a full table search on all of the GroupLocation.
Locations. There is a spacial index on the geopoint column, but for some reason SQL Server isn't using that index. Upon investigation we discovered that the pagination of the grid (line 951 of Grid.cs) causes SQL Server to not use the index. That is when Entity Framework adds in "TOP 50" to the SQL it causes a full table scan. Normally we would add an index hint to SQL, but EF does not support hints. 
The strategy to make SQL …
> Added an optimization to GetMappedLocationsByGeofences

- RockWeb/Themes/Flat/Assets/Lava/GroupDetail.lava
- RockWeb/Themes/Rock/Assets/Lava/GroupDetail.lava
- RockWeb/Themes/Stark/Assets/Lava/GroupDetail.lava
Counter and permission are misspelled on the group detail pages. 
Fix spelling mistakes
Modifying lava files
N/A
> Fix Spelling Mistakes in Group Detail

- RockWeb/Themes/Flat/Assets/Lava/EventItemOccurrenceListByAudience.lava
- RockWeb/Themes/Rock/Assets/Lava/EventItemOccurrenceListByAudience.lava
- RockWeb/Themes/Stark/Assets/Lava/EventItemOccurrenceListByAudience.lava
Themes include a reference to a image in a missing NewCovenant_v1 theme.
Remove missing images 
N/A
N/A
> Remove missing images from themes

- RockWeb/Blocks/Groups/GroupRegistration.ascx.cs
_Have you filled out and sent your [Spark Contributor Agreement] (http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?_ Yes
When a person registered for a group where they already existed in the group but were inactive, it left the person as inactive rather than updating their status per the settings in the Group Registration block.
Group member's status will now be updated if the already exist in the group in the same role.
The block was already checking to see if the person existed in that role but it wasn't checking the status.  Now if the person exists but the status is different the person gets updated.
None.  I wouldn't think anyone would actually want this to not update the status if someone registers for the group.
> Group Registration Status - Update the status of existing group members.

- RockWeb/Blocks/Security/Login.ascx.cs
Yes.
It's hard to reproduce, but we've occasionally seen the login screen not focus on the username field.  This forces a focus on the username field so you can start typing immediately.
Focus the username field on Login.
N/A.
> Focus the username field for the Login page

- Rock.Rest/Controllers/UserLoginsController.Partial.cs
Yes.
When implementing our native app, we needed to be able to check if a username already existed.  This functionality exists inside Rock, but isn't exposed to the API.
This PR adds an API endpoint to check for username availability.
See code.
N/A, provides ease of …
> Add an API endpoint to check if a username is available

- RockWeb/Themes/Rock/Layouts/Splash.aspx
[YES] Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?
We get a lot of 404s from Apple products looking for icons. We think it is coming from the login splash page as it is lacking any directives for the icon. 
Apple products will find the proper icon.
I added the icon links to the splash/login page.
None.
> Added icon links to splash page

- RockWeb/Themes/Stark/Assets/Lava/GroupDetail.lava
Yes
Unable to click to call phone number for members on mobile when viewing group leader toolbox.
Adds simple tel: handler to three phone numbers in Stark lava.
Changed to Starks groupdetail.lava.
None foreseen.
_Provide us some screenshots if your pull request either …
> + Added Click to Call to HTML of Stark GroupDetail.lava

- Rock/Lava/RockFilters.cs
Yes
Needed to expose that an event was happening from 1pm until 3pm.
Adds a new Lava filter that parses the End Date(s) from the iCal feed.
Copy/Paste from existing code in Lava filters changing where necessary.
More Filters!
```
Returns a list of upcoming end dates from an iCal string or List of iCal strings.
Additional Details
This filter takes an optional parameter of the number of upcoming occurrences to display. The default is 1. A text value of 'All' can also be used to return all the occurrences.
Example:
"EventItemCampuses": {
[
{ 
"ContactEmail": "jenny@rocksolidchurchdemo.com",
"EventItemSchedules": [
{ 
"Schedule": {
... ,
"iCalendarContent": "BEGIN:VCALENDAR VERSION:2.0 PRODID:-//ddaysof...",
... ,
}
}
]
}
]
}
{% assign upcomingEndDates =  EventItemSchedules | …
```
> + Added a new Lava Filter to get the End Date from an iCal feed.

- Rock/SystemGuid/EntityType.cs
- RockWeb/Blocks/Finance/TransactionEntry.ascx.cs
Added Campus Context options, URL Param Values to Attribute Values, and URL Param to Selected Account list in the Transaction Entry block.
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor Agreement.pdf) to secretary [at] sparkdevnetwork.org?_
Yes
**Two problems:**
1. Needed to control the list of Accounts displayed and save Transaction Attribute Values all via URL Params for third party integration.
2. Needed to have the Campus Context apply to the Account List when not controlling list of Accounts via URL.
**Three main goals:**
1. URL Parameter to control …
> Added Features to the Transaction Entry Block

- Rock/Utility/ExtensionMethods/AttributesExtensions.cs
Yes
Sometimes there is the need to only save one or more specific attributes rather than all of them, but there was no SaveAttributeValue method to go with the SaveAttributeValues method.
To allow the saving of one or more specific attributes.
Created extension methods called SaveAttributeValue, one which takes a key and one which takes a collection of keys. 
_What could this change potentially impact? Are there …
> Added SaveAttributeValue Extension methods

- Rock/Communication/MediumComponent.cs
- Rock/Communication/Transport/Twilio.cs
- Rock/Communication/TransportComponent.cs
- Rock/Rock.csproj
- Rock/packages.config
- RockWeb/Webhooks/Twilio.ashx
Even though the sending is now async, the webhook was not, so we still saw large load spikes
To make the webhook for twilio faster
IHTTPASYNC YAY
Changed the IHttpHandler for Twilio to be async
> Make twilio webhook async and allow for future fully async transports

- RockWeb/Blocks/Groups/GroupMemberAddFromUrl.ascx.cs
**Yes**
Potential security concern when using this block. The Person is passed as a GUID but the Group is passed as a integer ID number. Meaning the user can modify the URL to easily add themselves to other Rock Groups that have common numbers out of the box - such as the Admin security role.
Also (I know, I'm a bad boy for not doing two merges) added an additional default member role if none is specified as the GroupType's defined default member role (if it is defined).
_What will this pull request achieve and how will this …
> Updated Group Member Add From Url block to enhance security and provide role defaults

- RockWeb/Blocks/Cms/PageList.ascx.cs
Yes
See issue #2023 
Use a list instead of the original queryable
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST test your code before submitting a pull request._
N/A …
> Fixes #2023 - Fixing the site pages layout filtering

- RockWeb/Blocks/Groups/GroupList.ascx.cs
Fixing GroupList to use the same inactive class as GroupMemberList (Fixes#2041).
No
Fixes #2041 
It adds the correct CSS class to make records ghosted out when the user is added to a role as inactive.
Changed the class name.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop …
> Added correct CSS class to GroupList record.

- RockWeb/Blocks/Administration/SystemInfo.ascx.cs
☑️
The template no longer recommends attaching the diagnostic input, but it occasionally gets attached. The diagnostic file includes the cookie output.
See @nairdo or @mikepetersonccv
> Remove Rock cookie from diagnostics

- RockWeb/Styles/_blocks-crm.less
Yes
New Family Block isn't responsive on mobile #1151 
Make new family responsive from @screen-sm down.
N/A
None
N/A
> + Updated New Family to be responsive on mobile (Fixes #1151)

- RockWeb/Blocks/Cms/PublicProfileEdit.ascx.cs
YES
On the public profile edit block the suffix and title drop downs aren't populated. #2060
I added the bindings to OnInit.
> Fixed #2060 Added bindings to dropdown on public person page.

- Rock/Workflow/Action/Groups/PostAttendanceToGroup.cs
**Yes**
When using the Group Member Attendance Add workflow action it has an Attribute setting for the Schedule to use, but it never makes use of it in code.
Implement code to use the Schedule to fix #2125.
I copied and pasted the location code and changed a few characters to make it work for the schedule. Then I tested it to make sure it worked. It was fun.
_If your code is a new method or function (that doesn't …
> Fixed Group Member Attendance Add to use the Schedule Attribute.

- Rock/Attribute/Helper.cs
Yes
@nairdo's comment here https://github.com/SparkDevNetwork/Rock/pull/2025/files#r109787808
Eliminate obsolete code
Highlighting the offending line and hitting the delete key with gusto.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTes …
> - Removed an unnecessary AttributeService variable

- Rock/Web/UI/Controls/KeyValueList.cs
- Rock/Web/UI/Controls/ValueList.cs
**Yes**
Fix issue #1354 
Modify the rendered Javascript to no clash.
Wrapped the Javascript inside a local scope as the function calls are not made from outside the scope.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure …
> Fixed javascript scope for ValueList and KeyValueList

- RockWeb/Blocks/Finance/ContributionStatementLava.ascx.cs
Yes
Include Public Name in Pledge Summary.
(https://github.com/SparkDevNetwork/Rock/issues/2164)
Added PublicName in PledgeSummary. However same property was already in Account Summary.
> Fix ContributionStatementLava.ascx- Added Public Account Name in Pledge Summary (Fix #2164)

- RockWeb/Blocks/Communication/CommunicationEntry.ascx
- RockWeb/Blocks/Communication/CommunicationEntry.ascx.cs
Yes
https://github.com/SparkDevNetwork/Rock/issues/1999
Added server side validation of future send date/time values 
If a time but no date is entered, or if the date is in the past, display an error message instead of continuing
> Fix communication Entry - added server side validation of future send date/time values ( https://github.com/SparkDevNetwork/Rock/issues/1999)

- Rock/Model/SignatureDocumentTemplateService.Partial.cs
- RockWeb/Blocks/Event/RegistrationDetail.ascx.cs
Yes
See #2176 and #2177 
This provides fixes for both the issues above.
For #2176 - Use the AppliesTo person instead of the AssignedTo
For #2177 - Reload any objects used when sending the Signature Document into the RockContext that we are passing down into the SignatureDocumentTemplateService object..
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the …
> Resolving Signature Document issues

- RockWeb/Blocks/Finance/BusinessDetail.ascx
- RockWeb/Blocks/Finance/BusinessDetail.ascx.cs
Yes
Using Highlight Label to show status of Business Block  
Updated the business detail block to use a Highlight Label for indicating if a business is inactive instead of showing it on the view panel.
> Business Block (Inactive)

- RockWeb/Blocks/CheckIn/CheckinScheduleBuilder.ascx.cs
**Yes**
Fix Issue #626, request to have ability to select all or clear all checkboxes for a particular schedule column in bulk.
Add ability to select all/none at once rather than clicking individual checkboxes.
Added a fontawesome icon checkbox that is controlled by javascript. When the page loads it's state is set to checked if all checkboxes in that column are checked, otherwise it's set to unchecked. When …
> Update Schedule Builder block to allow select all/none in column

- RockWeb/Blocks/Groups/GroupRegistration.ascx.cs
**Yes**
When a non-logged in person registers for a group and they are matched to an existing record, then their existing phone number(s) and address will be erased if the user only supplied name and e-mail.
Only set the new values on a matched record if the user entered values in the fields.
Using conditional checks in the C# code to only set the phone number(s) and address if it is not a matched user or the …
> Fixed GroupRegistration block to not erase matched person's data if the user did not fully fill out the form.

- RockWeb/Blocks/Utility/HtmlEditorFileBrowser.ascx
- RockWeb/Blocks/Utility/HtmlEditorFileBrowser.ascx.cs
**Yes**
There was no way to move a folder to another location without going into the file system and manually doing so, which is not something I want regular users doing.
1. Add ability to move folders to be sub-folders of another folder than it currently is.
2. Fix scroll bar height to use full height available instead of hard coded to 120 pixels.
3. Fix alignment issue between folder list and file list (the file list was 5px lower because of the way the …
> Various enhancements to File Manager block.

- Rock.Tests/Rock/Lava/RockFiltersTests.cs
- Rock/Lava/RockFilters.cs
**Yes**
As discussed in #1943, a simpler method of retrieving a single item from an array when chaining filters.
Adds new Lava filter to perform the required operation.
I typed code into the magical white window. Click run. It broke. Fixed a typo and clicked run again. It worked.
New filter accepts a generic input type and a generic index argument, then attempts to cast/convert them to their real values. If they …
> New Lava filter called Index that extracts single element from array

- Rock/Model/FinancialAccountService.Partial.cs
- Rock/Rock.csproj
- RockWeb/Blocks/Finance/AccountDetail.ascx
- RockWeb/Blocks/Finance/AccountDetail.ascx.cs
- RockWeb/Blocks/Finance/AccountList.ascx
- RockWeb/Blocks/Finance/AccountList.ascx.cs
- RockWeb/Blocks/Finance/AccountTreeView.ascx
- RockWeb/Blocks/Finance/AccountTreeView.ascx.cs
Yes
Financial accounts support a parent/child relationship between accounts, but that is currently not obvious because of the user interface that currently exists for editing accounts
> Update Financial Account Detail page to have a parent/child navigation

- Rock/Lava/Blocks/WorkflowActivate.cs
**Yes**
Make command conform to other command syntax better.
Change the `ParseMarkup` method to be closer in syntax to other commands.
Also updated the command itself to support processing an existing workflow without activating new activity. i.e. you can instruct a workflow that is now in a waiting state to process again.
Consulted the Programmer's Magic 8-Ball&trade; to determine what code to type in and then …
> Updated WorkflowActivate lava command

- Rock/Jobs/CommunicationQueueAlert.cs
- Rock/Rock.csproj
Yes
Created CommunicationQueueAlert to send an alert if communication queue is not being sent
> Job to send an alert if communication queue is not being sent

- RockWeb/Blocks/Finance/TransactionList.ascx.cs
Issue #2256 
Make it easier to know what batch you are moving transactions into.
Added the Batch Id to the text values of the drop down list when selecting the target batch. Also changed sort order of items in that list to be by Batch Id number. …
> Update TransactionList block to include Batch Id numbers in "Move To..." drop down

- RockWeb/Blocks/CheckIn/Welcome.ascx.cs
**Yes**
Check-in welcome screen would get stuck at 0:00 on the countdown screen.
Fix issue #2236.
When the page has finished postback, but before the DOM has been destroyed, we destroy the javascript countdown object. Not doing this was causing dozens (possibly hundreds) of countdown timers to collect on the device. This caused both memory leaks and issues with the expiry event firing and causing doezens/hundreds …
> Fixed check-in welcome screen hanging on 0:00 countdown. (Fixes #2236)

- RockWeb/Blocks/Fundraising/FundraisingProgress.ascx
- RockWeb/Blocks/Fundraising/FundraisingProgress.ascx.cs
Yes
Block to view  fundraising progress for all people in a fundraising group.
> Block to view that fundraising progress for all people in a fundraising group

- RockWeb/Blocks/Utility/HtmlEditorFileBrowser.ascx
- RockWeb/Blocks/Utility/HtmlEditorFileBrowser.ascx.cs
- RockWeb/Styles/rock-components/rock-list.less
**Yes**
When we have uploaded a document to Rock and need to make a change to that document we have to manually type in the URL to download the doc. Amongst other reasons to be able to download from the file manager.
Allow users to download files in addition to uploading and deleting them.
New button to left of file icon that allows for downloading the file. More specifically, a hyperlink. The user can either click …
> Updates to the file browser to allow for downloading files

- Rock/Rock.csproj
- Rock/Web/Cache/ContentChannelCache.cs
Yes
Added Content Channel Cache that is required by the rendering engine
> Added Content Channel Cache

- RockWeb/Themes/Stark/Assets/Lava/PodcastSeriesDetail.lava
**Yes**
Invalid HTML in file.
Fix HTML in file.
Through some random letters around in the file to see what stuck. Called myself the Picasso of C#. Became a millionaire.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your …
> Fix some formatting and invalid HTML in the PodcastSeriesDetail.lava file

- RockWeb/Blocks/Finance/PledgeList.ascx
Yes
#2200 Pledges export to Excel has missing columns
Used ExcelExportSource as ColumnOutput and ExcelExportBehavior to IncludeIfVisible for all virtual members.
> Fixes #2200 Pledges export to Excel has missing columns

- RockWeb/Blocks/Groups/GroupDetail.ascx
- RockWeb/Blocks/Groups/GroupDetail.ascx.cs
Yes
Added block setting for Group List Page and Fundraising Progress Page.
Also added a new button icon to be displayed  if the current group is a fundraising group type and a value has been set for the new block setting.
> Added block setting for Group List Page and Fundraising Progress Page

- RockWeb/Blocks/Groups/GroupTypeList.ascx.cs
Yes
Group Type list is currently sorted only by [order].
Sorted Group Type List on basis of [Order] then by [Name].
> Fixed Sorting in GroupType List to Order first by [Order] then Name #2266

- Rock.Rest/Controllers/PeopleController.Partial.cs
- RockWeb/Blocks/Groups/GroupMemberList.ascx
- RockWeb/Blocks/Groups/GroupMemberList.ascx.cs
- RockWeb/Scripts/Rock/Controls/personPicker.js
Yes
Records were displayed with InActive instead of pending in Person Picker  as well as Marital Status was missing in Group Member List.
> Fixed Pending records in Person Picker  #2288 & Added Marital Status to Group Member List

- Rock/Attribute/DataViewsFieldAttribute.cs
- Rock/Field/Types/DataViewsFieldType.cs
- Rock/Rock.csproj
- Rock/Web/UI/Controls/Pickers/DataViewsPicker.cs
Yes
A new field type that is a list of selected Data Views. This would allow a group attribute to select which data views that are selected for the specific group
> Communication - Data Views Field Type

- RockWeb/Blocks/Groups/GroupList.ascx
- RockWeb/Blocks/Groups/GroupList.ascx.cs
Yes
Added the functionality inside the Group List block to filter on Group Types Purpose
> Allowed the Group List block to filter on Group Types Purpose

- Rock/Reporting/DataFilter/Person/FinancialPledgeDataViewFilter.cs
- Rock/Rock.csproj
Yes
Issue #2310, being able to segment people by their pledges (or lack of pledges) is helpful for giving analytics and accounting department related tasks.
Add financial pledges to the related data views section for a person.
Created based on the new Financial Transaction Data View Filter.
My test writing skills are lacking 😭 
More fun
_Provide us some screenshots if your pull request either alters existing UI or provides new UI. Arrows and labels are helpful._
N/A
> Added Pledge data view filter to allow filtering by pledges (Fixes #2310)

- RockWeb/Blocks/Core/DeviceList.ascx
- RockWeb/Blocks/Core/DeviceList.ascx.cs
**Yes**
I broke the Delete button with #2314.
Fix what I broke.
Made the delete field dynamic.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests …
> Fix Delete button after previous device attributes PR

- Rock/Follow/Event/PersonHistory.cs
- Rock/Rock.csproj
**Yes** (someday I should say no and see what happens)
I was asked for permission to integrate the plug-in into core.
Implement the plug-in event detection code directly into core.
Copy & paste
**Public disclaimer**: I basically did not test this at all other than making sure it showed up correctly in the UI. The plug-in code is functional and was 100% direct copy with the exception of the namespace.
_If your code …
> Migrate Person History Follower plug-in to core

- RockWeb/Blocks/Security/LoginStatus.ascx.cs
Yes
Fixed logout issue when user contain Url Encoded Key 'rckipid'
> Fixed logout Issue when URL contains Encoded Key #2202

- RockWeb/Blocks/Event/RegistrationInstanceDetail.ascx
- RockWeb/Blocks/Event/RegistrationInstanceDetail.ascx.cs
Yes
Added Registration Start Date and End Date to Registration Instance Detail.
> Added Registration Start and End dates to Registration Instance Detail

- RockWeb/Blocks/Finance/TransactionEntry.ascx.cs
✔︎
See discussion at #2191.
Squash the bugs.
Checked for NULL before calling an object method.  Also checked for empty strings so that another method doesn't get called unnecessarily.
> Fix 2191, ACH-only giving throws an exception

- RockWeb/Blocks/CheckIn/AttendanceHistoryList.ascx.cs
✔︎
NULL objects are grouchy and don't like getting their methods called without asking.
Make NULL objects great again.
Asked NULL objects permission first.
> Fix attendance history list crashing without groupid, #2057

- RockWeb/Blocks/Core/FollowingByEntityLava.ascx.cs
Yes
Added Delete Functionality to Existing Following By Entity block
> Added Delete Functionality to Existing Following By Entity block

- RockWeb/Styles/_blocks-crm.less
- RockWeb/Styles/_blocks-events.less
- RockWeb/Styles/_forms.less
- RockWeb/Styles/_grid.less
- RockWeb/Styles/_modal.less
- RockWeb/Styles/_rock-core.less
- RockWeb/Styles/_rock-variables.less
- RockWeb/Styles/bootstrap-colorpicker/colorpicker.less
- RockWeb/Styles/rock-components/html-editor.less
- RockWeb/Styles/rock-components/picker-date.less
- RockWeb/Themes/CheckinAdventureKids/Styles/_variables.less
- RockWeb/Themes/DashboardStark/Styles/_variables.less
- RockWeb/Themes/Flat/Styles/_variables.less
- RockWeb/Themes/Flat/Styles/theme.less
- RockWeb/Themes/Rock/Styles/_variables.less
- RockWeb/Themes/Stark/Styles/_variables.less
- RockWeb/Themes/Stark/Styles/theme.less
Housekeeping; some less files have picked up weird indents, spacing, property orders, etc...
Easy to read and maintain less
CSSLint against existing files. Fix includes lowercase color names, truncated 6-digit hex colors, prefer `0` over `none` for border values.
N/A
N/A
N/A
N/A
> Updated less to conform to style guide

- RockWeb/Assets/Lava/MyWorkflowsSortable.lava
- RockWeb/Blocks/WorkFlow/MyWorkflowsLava.ascx
- RockWeb/Blocks/WorkFlow/MyWorkflowsLava.ascx.cs
- RockWeb/Themes/Rock/Assets/Lava/MyWorkflowsSortable.lava
Yes
1. Renamed MyWorkflowsLiqud to MyWorkflowsLava
2.  Added block setting for panel title and Icon.
> Renamed MyWorkflowsLiqud to MyWorkflowsLava and Added setting for panel title and Icon

- RockWeb/Blocks/WorkFlow/MyWorkflows.ascx.cs
Yes
On the MyWorkflows.ascx block, Added block setting to filter by a Workflow Categories. The default value will not have a category which will reproduce the current functionality.
> Added a block setting to filter by a Workflow Categories.

- RockWeb/Blocks/Event/RegistrationTemplateDetail.ascx.cs
Yes
Added a tooltip to the options on this select so if two attributes have same name, but different ids, we can know which is which.
> Added tooltip to PersonAttribute dropdown to identify option with same name

- RockWeb/Blocks/Finance/BusinessList.ascx
Yes
Fixed Line break issue in Contact Information Column inside Business List Block
> Fixed Line Break Issue in Contact Information Column

- Rock/Web/UI/RockPage.cs
- RockWeb/Blocks/Cms/SiteDetail.ascx
- RockWeb/Blocks/Cms/SiteDetail.ascx.cs
- RockWeb/Themes/CheckinAdventureKids/Layouts/Site.Master
- RockWeb/Themes/CheckinBlueCrystal/Layouts/Site.Master
- RockWeb/Themes/CheckinPark/Layouts/Site.Master
- RockWeb/Themes/DashboardStark/Layouts/Site.Master
- RockWeb/Themes/Flat/Layouts/Site.Master
- RockWeb/Themes/KioskStark/Layouts/Site.Master
- RockWeb/Themes/Rock/Layouts/Site.Master
- RockWeb/Themes/Stark/Layouts/Site.Master
Yes
Added feature is to allow add custom favicons for each site without having to know complex HTML or have to edit Theme files.
> Added Fileupload for favicon in Site Detail and linked it through RockPage.cs

- RockWeb/Blocks/Cms/LavaShortcodeDetail.ascx.cs
Yes
Validation on exisitng Tag Name in LavaShortcode Detail Block.
> Check for exisitng Tag Name in LavaShortcode Detail Block

- RockWeb/Blocks/Cms/ContentChannelView.ascx
Yes
https://github.com/SparkDevNetwork/Rock/issues/2276
> Fixed #2276 Added required Attribute to Channel picker in ContentChannelView 

- .github/CONTRIBUTING.md
Helping Rock, Rock on GitHub.
Move Wiki article to `contributing.md` with GitHub label issue structure as discussed at RX2017
`Priority: / Status: / Type: / Topic:` structure for github labels, goal being that issues should only have one of each priority, status, and type. And a minimal number of Topics.
N/A
- 📈  **Awesome**
- 📉  **Developer Confusion**
N/A
N/A
> Added CONTRIBUTING.md file

- RockWeb/Blocks/Finance/TransactionEntry.ascx
- RockWeb/Blocks/Finance/TransactionEntry.ascx.cs
**Yes**
See #2359 for discussion.
Rock our Finance Team's world.
New URL formats supported:
* `AccountIds=AccountId^Amount^UserEditable[,...]`
* `AccountGlCodes=AccountId^Amount^UserEditable[,...]`
* Amount and UserEditable are optional in both formats.
* Example: `?AccountIds=2^50.00^false`
* `Frequency=DefinedValueId^UserEditable`
* UserEditable is optional.
* Example: `&Frequency=133,false`
Special care taken to …
> [EN] Added ability to set default frequency and dollar amounts for TransactionEntry

- Rock/Model/Metric.cs
- Rock/Security/Authorization.cs
Yes
Metrics do not inherit security from categories
> Fixed #2399 Metrics do not inherit security from categories

- .github/CONTRIBUTING.md
- .github/SUPPORT.md
Yes
Issue labels are out of date, and GitHub now supports a `SUPPORT.md` file. This adds a support link to the top of issues, and pull request pages. The support doc should help with the continued growth of the community and direct people to the correct support channels.
Making the world a better place... through labels.
N/A
N/A
N/A
N/A (It kinda is documentation)
N/A
> - Updated GitHub Contribution Docs

- Rock/Rock.csproj
- Rock/Workflow/Action/Connections/SetConnectionRequestConnector.cs
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?_  
Yes
_What is the problem you encountered that lead to you creating this pull request?_  
Could not set a Connector via a Workflow Action.
_What will this pull request achieve and how will this fix the problem?_  
Create a new workflow action which sets a connection request connector.
_How have you implemented your solution?_  
Added a new Workflow Action which allows the connector to be set via a workflow.
_What could this change potentially impact? Are there any security considerations? Where could this potentially affect backwards compatibility?_  
None
_Provide us some screenshots if your pull request …
> Added a new workflow action to set a connector.

- RockWeb/Blocks/Groups/GroupFinder.ascx.cs
Yes?
Issue #2425 
Replace "\\" with "\\\\" so JSON.Parse can handle it appropriately.
Added an additional replace function to each JSON string.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes …
> Group Name's with "\" in name break Group Finder

- RockWeb/Blocks/Event/RegistrationInstanceDetail.ascx.cs
**Aye**
See #2437. We use a group tree for our youth groups and use event registration to sign up for groups for the year. When a group closes (leader moves for example) the group is marked as Inactive. The problem is that people who _were_ in that now inactive group do not show up for placement because it thinks they are already placed.
People are now only hidden from the placement list if they are an `Active` member of an `Active` group in the selected …
> Fix Group Placement to not hide people in inactive groups or inactive members

- RockWeb/Blocks/Finance/ContributionStatementLava.ascx.cs
**Darn Tootin'**
See issue #2463.
- Show pledges that overlap with the statement year being generated.
- Do not count gifts towards pledges that are beyond the end of the statement year (or current date).
- Show "as of date" with the "Pledges" text for less confusion when generating post-dated statements.
Adjusted the default Lava for the attribute block setting.
Adjusted the year comparison to find existing …
> Fix Lava Contribution Statement to show correct pledge amounts

- Rock/Workflow/Action/Groups/AddPersonToGroup.cs
Yes
Fixes #2459 Added Group Member Status to Group Member Add
Add EnumField Attribute for Group Member status inside AddPersonToGroup.cs
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST test your code before submitting a pull request.
N/A
What could this change potentially impact? Are there any security considerations? Where could this potentially …
> Fixes #2459 Added Group Member Status to Group Member Add

- Rock/Web/UI/Controls/FollowingsHelper.cs
Have you filled out and sent your [Spark Contributor Agreement]
Yes
#2401 Cannot follow multiple items on single page 
Appended Control ClientId in  RegisterStartupScript Key to make it unique.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST test your code before submitting a pull request.
N/A
What could this change potentially impact? Are there any security …
> Fixes #2401 following multiple items on single page

- Rock/Model/FinancialPledge.cs
- RockWeb/Blocks/Finance/PledgeDetail.ascx
Yes
#2421 Financial Pledges Allow Negative Values
validated inside IsValid to check TotalAmount is always positive. Also assign MinimumValue to Zero in PledgeDetail block.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests …
> Fixes #2421 Financial Pledge block Allow Negative Values

- Rock/Model/GroupType.cs
- RockWeb/Blocks/Groups/GroupTypeDetail.ascx
- RockWeb/Blocks/Groups/GroupTypeDetail.ascx.cs
Yes
#2447 Group Type editor allows creation of circular references for Inherited Group Types
Check for circular references inside InValid property of GroupType.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all …
> Fixes #2447 Validating circular references for Inherited Group Types

- RockWeb/Blocks/Administration/PageProperties.ascx.cs
_Have you filled out and sent your [Spark Contributor …
> Updated Page Settings to show blocks requiring Context parameters

- RockWeb/Themes/Flat/Assets/Lava/PageListAsBlocks.lava
Additionally fixes missing single quote referred to in #2495
_Have you filled out and sent your [Spark …
> Fixes #2498 for Flat theme

- RockWeb/Themes/Stark/Assets/Lava/PageListAsBlocks.lava
Fixes missing single quote and issue from #2498
_Have you filled out and sent your [Spark Contributor …
> Fixes both #2498 and #2495 (Stark theme)

- RockWeb/Themes/Rock/Assets/Lava/PageListAsBlocks.lava
Fixes #2498 in Rock theme
_Have you filled out and sent your [Spark Contributor …
> replace childPage.Id with childPage.Url (Fixes #2498 in Rock theme)

- Rock/Workflow/Action/CheckIn/ParseZebraLabel.cs
_Have you filled out and sent your [Spark Contributor …
> Fix the Parse Label workflow action to not erase existing merge codes

- RockWeb/Blocks/Event/EventItemOccurrenceDetail.ascx
- RockWeb/Blocks/Event/EventItemOccurrenceDetail.ascx.cs
2. If your PR is for an enchancment that has not been discussed and approved by the core team please get that approval BEFORE submitting the request. In fact, this approval should be recieved before writing the code to limit rework on your part. This will ensure that all code is working into the same vision and direction of the core project.
> I asked Mike Peterson for permission and he explicitly denied his ability to approve this PR.  I guess I'll just ask for forgiveness …
> Adding attribute support to Event Item Occurrences.

- RockWeb/Blocks/WorkFlow/WorkflowEntry.ascx.cs
**Yes**
Multiple user entry forms don't scroll to top of page when loading 
scrolling to top on successful submit in case of Multiple user entry form
Instead of rendering Control in same view, there is redirect to same page in a way to achieve complete postback.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see …
> Fixes #2511 scrolling to top on submit in case of Multiple user entry form

- Rock.Migrations/Migrations/201709231340508_FixPersonicx.cs
**Yes**
Migration having delete and then insert personicx Cluster data was not working if data is already referenced.
Changed Personicx Migration to make an update rather than insert with delete
Yes Finded out all the changes and written update query for each changes separately.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see …
> Changed Personicx Migration to make Update rather than insert with delete

- RockWeb/Blocks/Connection/ConnectionRequestDetail.ascx
- RockWeb/Blocks/Connection/ConnectionRequestDetail.ascx.cs
**Yes**
#2524 Connection Request Detail block does not handle errors gracefully
Handling the Query String exception and showing proper message in Connection Request Detail
Show Critical Message only in case when there is no opportunity Connection Id and Connection Request Id in the Querystring of the request. 
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be …
> Fixes #2524 Handle Query String exception in Connection Request Detail

- RockWeb/Blocks/Connection/ConnectionOpportunityDetail.ascx.cs
**Yes**
#2489 Connection Opportunity Block not marking files Temporary = false 
Goal is to mark IsTemporary to false on Image Upload in Connection Opportunity
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request …
> Fixes #2489 Mark IsTemporary false on Image Upload in Connection Opportunity

- Rock/Reporting/DataFilter/Person/PersonalDeviceDataViewFilter.cs
- Rock/Rock.csproj
**Yes**
Adding related person data filter for Personal Device
Goal is to Add related person data filter for Personal Device.
Created new Data View Filter similar to UserLogin Data View Filter
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) …
> Added related person data filter for Personal Device

- RockWeb/Blocks/Groups/GroupList.ascx.cs
**Yes**
#2491 Allow Group List Block to Sort on DateTimeAdded.
Fixes #2491 Allowed Group List Block to sort on DateTimeAdded
Mapped DateTimeAdded field in Correct field in DB.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your …
> Fixes #2491 Allowed Group List Block to sort on DateTimeAdded

- Rock/Follow/Suggestion/InFollowedGroup.cs
- Rock/Rock.csproj
**Yes**
Need way to automatically follow people in groups that are followed.
Added  InFollowedGroup Suggestion type for anyone who is in a Group that is followed.
A new InFollowedGroup  Suggestion Type is created.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lav …
> Added  InFollowedGroup Suggestion type for anyone who is in a Group that is followed.

- RockWeb/App_Code/FileUploader.ashx.cs
**Yes**
File Uploader allows illegal characters in filenames which causes issues trying to download the files later, See #2227.
Fix the uploader so it doesn't allow invalid characters.
Use a regular expression to replace all occurrences of invalid characters with an empty string. thus `A&B%C.png` -> `ABC.png`
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and …
> Updated File Uploader to clean invalid characters from filenames.

- Rock/Model/PersonService.Partial.cs
**Yes**
When searching for businesses in the Person Picker, if the business has a comma in the name it's almost impossible to search for. See #2279.
Allow for Person Picker to search for businesses with a `,` in the name.
When searching for businesses, also search for the "full name" search term that was specified.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes …
> Updated Person Search to better handle businesses with a comma in name.

- RockWeb/Blocks/Finance/GivingAnalytics.ascx.cs
**Yes**
Export to Excel in Giving Analytics block was missing GivingId.
Included GivingId on export to Excel in Giving Analytics block
Just defined the column in the Grid.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull …
> Included GivingId on export to Excel in Giving Analytics block

- RockWeb/Blocks/Event/CalendarLava.ascx.cs
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreemen …
> + Added the ability to filter the calendar lava block using page parameters

- RockWeb/Blocks/Cms/ContentChannelDetail.ascx.cs
Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement …
> Fixes #2572 Attribute Key Conflict Error

- Rock/Attribute/Helper.cs
- Rock/Attribute/IHasInheritedAttributes.cs
- Rock/Data/Model.cs
- Rock/Model/EventItem.cs
- Rock/Model/Group.cs
- Rock/Model/GroupMember.cs
- Rock/Model/GroupType.cs
- Rock/Model/RegistrationRegistrant.cs
- Rock/Rock.csproj
**Yupperz**
Inability to use inherited attributes in plugins. See #2386 for discussion.
Splinter the `LoadAttributes()` method out to smaller pieces, allowing each entity type to provide it's own inherited attributes.
New interface `IHasInheritedAttributes` that is implemented on `Model<T>` with empty methods. Concrete subclasses can override the method implementation to provide their own list of inherited …
> + Added support for plugins to specify inherited attributes on custom entities.

- RockWeb/Blocks/Crm/PersonDetail/Bio.ascx
**Yes**
Issue #2610, new custom content can move a bit. 
Prevent jumpy content
Add a `clearfix`
N/A
N/A
N/A
N/A
N/A
> Added clear fix to bio bar summary to reflow content (Fixes #2610)

- RockWeb/Blocks/Core/ScheduleDetail.ascx
- RockWeb/Blocks/Core/ScheduleDetail.ascx.cs
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreemen …
> Feature cb schedule detail attributes

- Rock/Model/DeviceService.Partial.cs
- RockWeb/Blocks/Core/DeviceDetail.ascx
- RockWeb/Blocks/Core/DeviceList.ascx
**Y.E.S. spells YES**
See issue #2625 for discussion of issue. Device DNS hostname matching matches against Name field instead of IPAddress field.
Make Rock logical.
Change the matching code to first attempt to match by IP address, and if that fails (and reverse lookup is requested) then it will try matching by Hostname against the IPAddress field.
_If your code is a new method or function (that doesn't need a mock …
> Updated Device search by Hostname functionality to match against IPAddress field

- RockWeb/Blocks/WorkFlow/WorkflowEntry.ascx.cs
Adding a check to make sure we aren't already redirecting when loading the new Rock page in WorkflowEntry.
_Have you filled out and …
> Fixes #2645 - Redirect issue in Workflow

- Rock/Reporting/Dashboard/LineBarPointsChartDashboardWidget.cs
**Oh yeah**
See issue #2576. Dashboard Reporting Widget blocks would only get one partition context from the current page even if more were available.
Aaaaaand i screwed up the commit message by not following the proper commit grammar. Sigh.
Update base class to support multiple partitions.
All partition context information is returned instead of just the first one. Calling methods (only 2) decide if they want the …
> Updated dashboard widget code to support multiple partition contexts

- RockWeb/Blocks/Event/RegistrationTemplateDetail.ascx.cs
If a dollar sign is saved as part of the fee option (Id / Name), it causes the fee not to work during and event registration, this because the fee control id is malformed with an invalid dollar character that causes the find control logic not to find and charge the selected fee during registration.
the request. In fact, this approval should …
> Remove dollar sign (character) from fees

- Rock/Lava/RockFilters.cs
Unable to easily make a unique list of items from a collection that may have duplicates.
Provide a Lava filter to "unique" a collection of values.
Used Dynamic LINQ to Distinct() the collection.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull …
> Added new Uniq lava filter to return the unique set of values from a collection of values

- Rock/Model/FinancialPledge.cs
- RockWeb/Blocks/Finance/PledgeDetail.ascx
- RockWeb/Blocks/Finance/PledgeEntry.ascx
See #2653. There has been some confusion about whether the Pledge Total is the grand total or the amount of each individual gift as specified by the pledge frequency. It is the former, though some C# code comments incorrectly stated it as the latter.
Clarify the functionality.
Fix the C# code comments and add Help text on the pledge detail screen.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) …
> Updated Help text to clarify the meaning of the total amount and pledge frequency.

- RockWeb/Blocks/Communication/CommunicationList.ascx
- RockWeb/Blocks/Communication/CommunicationList.ascx.cs
See #2683. If you entered a bad filter (such as a long-range date filter with content filter) it would cause an exception which was not handled so the entire page would not be accessible. As such you could not fix the filter.
Gracefully catch the error.
Catch any error during data binding. Display a message to the user that includes the exception message. Also log the exception to the database.
_If your code is a new method or function (that doesn't …
> Fixed Communication List block so that it no longer throws error on query exception.

- Rock/Data/IRockStoreModelConvention.cs
- Rock/Data/RockContext.cs
- Rock/Data/Udf/GetAddressStoreFunctionInjectionConvention.cs
- Rock/Data/Udf/GetGeofencedGroupNamesStoreFunctionInjectionConvention.cs
- Rock/Data/Udf/GetSpousePersonIdFromPersonIdStoreFunctionInjectionConvention.cs
- Rock/Rock.csproj
As a plugin developer, could not use custom made SQL Functions with my LINQ queries. Also see #2642.
Provide a way to do this.
Added new interface `IRockStoreModelConvention<T>` which inherits from `IStoreModelConvention<T>` and use reflection to add all matching class instances to the configuration. …
> - Added support for plugins to use custom SQL Functions in LINQ queries

- RockWeb/Themes/Rock/Styles/email-editor.less
Yes
Fixes #2801
Allow easier adding of components on longer emails.
Add position sticky:
```
.editor-toolbar-container {
position: sticky;
top: 0;
z-index: 1000;
```
N/A
None
N/A
N//A
> - Added sticky email editor toolbar and css comb email editor file

- RockWeb/Blocks/Cms/PublicProfileEdit.ascx.cs
Fix incorrect word placement. See #2790.
Move the word.
Copy & Paste the word to the correct location.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST …
> Fixed incorrect placement of word "old" in My Account page.

- Quartz/DateBuilder.cs
- Rock/Model/GroupService.Partial.cs
- Rock/Model/GroupType.cs
Yes
Occurrence is misspelled in several places in code. (And on the lava [text filters page](https://www.rockrms.com/page/441))
Fix spelling 📝 
Replaced "Occurance" misspelling. Needs migration to fix misspelling added via `201801162056008_V8Features.cs`
N/A
None
N/A
N/A
N//A
> Fixed spelling of occurrence in code

- Rock/Lava/RockFilters.cs
Confusion in how to sanitize a Lava variable before using in SQL.
Provide a starting point to help sanitize user text before using in a SQL command.
Currently the filter just replaces `'` with `''` so that they cannot escape a `'...'` quoted string. Later this filter may provide some extra safeguards like trying to detect common SQL statements.
```sql
{% sql %}SELECT * FROM [Person] WHERE [LastName] = '{{ Name | SanitizeSql }}'{% endsql %}
```
_If …
> Added SanitizeSql to Lava filters to help protect against SQL Injection

- Rock/Workflow/Action/Utility/RunSQL.cs
See #2866. There is no way to use SQL parameters which makes SQL injection a much high possibility.
Add SQL parameter support to the Run SQL action.
Added new KeyValueList attribute to the Run SQL action which allows the user to specify SQL parameters. Values are resolved with Lava first before being passed to SQL. …
> Added support to the Run SQL workflow action for Parameterized SQL statements

- Rock.Rest/Controllers/UserLoginsController.Partial.cs
See #896. When creating a user login through the API, if the username already exists an error 500 is returned.
Make the 500 go away.
Now check to see if username exists and if so return a 409 Conflict status instead.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) …
> Fixed the UserLogin API to return a 409 status if the username already exists.

- Rock/Model/BenevolenceRequest.cs
- Rock/Reporting/DataFilter/BenevolenceRequest/CampusActiveFilter.cs
- Rock/Reporting/DataFilter/BenevolenceRequest/CampusFilter.cs
- Rock/Reporting/DataFilter/BenevolenceRequest/CampusesActiveFilter.cs
- Rock/Reporting/DataFilter/BenevolenceRequest/CampusesFilter.cs
- Rock/Reporting/DataFilter/BenevolenceRequest/TotalBenevolenceFilter.cs
- Rock/Reporting/DataFilter/Person/BenevolenceRequestDataViewFilter.cs
- Rock/Reporting/DataSelect/BenevolenceRequest/CampusSelect.cs
- Rock/Reporting/DataSelect/BenevolenceRequest/TotalBenevolenceSelect.cs
- Rock/Rock.csproj
Yes
Benevolence Requests were missing some reporting tools. This adds some. 🎉  
Add Reporting to Benevolence Requests on:
- Total Benevolence
- Campus Select and Filters
- Person Benevolence Request Data View
DataSelect and DataFilter CS Methods (Copy+Paste from existing conventions)
N/A
N/A
N/A
N/A
N//A
> Added benevolence request reporting features

- RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
> Handling a history point creation exception on event registration.

- Rock/Reporting/DataFilter/Group/DistanceFromFilter.cs
- Rock/Reporting/DataFilter/Person/DistanceFromFilter.cs
Go easy on me guys, this is my first pull request. Hope I followed all instructions correctly!
I didn't put an issue number because I couldn't find this as a known issue, but if there's a better way to handle that, please let me know!
> + Fixed an issue preventing user drawn geo-fences from filtering groups and people.

- Rock/Financial/TestGateway.cs
Difficulty in testing "denied" scenarios with swipe cards on the test gateway. See #2769.
Allow user to specify which card numbers (ends with) will be denied.
Wrote the code, tested the code, committed the code, pushed the code. Hoping somebody will pull the code.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all …
> Updated Test Gateway to support specifying which card numbers to deny.

- RockWeb/Themes/Flat/Assets/Lava/CalendarItem.lava
- RockWeb/Themes/Flat/Assets/Lava/FundraisingOpportunitySummary.lava
- RockWeb/Themes/Flat/Assets/Lava/FundraisingParticipantProfile.lava
- RockWeb/Themes/Rock/Assets/Lava/CalendarItem.lava
- RockWeb/Themes/Rock/Assets/Lava/FundraisingOpportunitySummary.lava
- RockWeb/Themes/Rock/Assets/Lava/FundraisingParticipantProfile.lava
- RockWeb/Themes/Stark/Assets/Lava/CalendarItem.lava
- RockWeb/Themes/Stark/Assets/Lava/FundraisingOpportunitySummary.lava
- RockWeb/Themes/Stark/Assets/Lava/FundraisingParticipantProfile.lava
- RockWeb/Themes/Stark/Assets/Lava/PodcastSeriesDetail.lava
Yes
Fixes #2775
Encode all URLs using `EscapeDataString` 
`EscapeDataString` all encoded urls that were  using `Escape`
N/A
None
N/A
N/A
N//A
> Fixed share urls to work properly for all pages

- RockWeb/Blocks/Examples/ModelMap.ascx
- RockWeb/Blocks/Examples/ModelMap.ascx.cs
> Enhance the Model Map with filters and query string parsing

- RockWeb/Blocks/Finance/TransactionEntry.ascx.cs
> Transaction Entry - TransactionEntityTransactionsTotal bug fix fixes #2933

- Rock/Web/UI/Controls/Communication/Sms.cs
- RockWeb/Blocks/Communication/CommunicationEntry.ascx.cs
- RockWeb/Blocks/Communication/CommunicationEntryWizard.ascx.cs
> [EN] Communication Enhancement limit what SMS numbers you can send from

- RockWeb/Blocks/Reporting/ServiceMetricsEntry.ascx.cs
> Fix spelling error "scheudle"

- Rock/Model/Person.cs
- Rock/PersonProfile/Badge/TopPersonSignal.cs
- RockWeb/Blocks/Crm/PersonSearch.ascx.cs
1. Add tooltip to Signal Flag to indicate to the user which signals that person has tagged on them.
2. Add the signal icon to show up on the person search results.
1. Add tooltip to Signal Flag to indicate to the user which signals that person has tagged on them.
2. Add the signal icon to show up on the person search results.
As usual, I gave the instructions to my coding monkey and it took care of all the heavy lifting. A banana is a small price to …
> Enhance Person Signal display on v8

- Rock/Lava/RockFilters.cs
Difficulty in adding months to a date (i.e. I can't just do `DateAdd:30,'d'` and be good with it). See #3001.
Add extra options for Weeks, Months and Years.
Wrote some code, made millions, lost it in a pyramid scheme.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) …
> Additional options to the DateAdd filter for Weeks, Months and Years

- RockWeb/Blocks/Core/Categories.ascx.cs
When using the Admin > System Settings > Category Manager to work with categories, if a category is marked IsSystem = true, then it still allows you to edit and delete them, even though you shouldn't be able to.
See #2827 
If it ain't broke don't fix it... If it is broke... well, fix it.
Passed the `IsSystem` value to the grid so that the DeleteField will automatically disable if the category is a system category.
In the case of EditField, I didn't …
> Fixed Category Manager to not allow deletion or editing of System categories

- Applications/Wpf/CheckScannerUtility/CheckScannerUtility/ScanningPage.xaml.cs
See #2887. Check scanner will sometimes pick a short 2 digit field in the MICR data instead of the longer (more probable) field for the check number.
Pick the longest field in the MICR extra data.
Order by length of parts and take the last element.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/ …
> Fixed Check Scanner application to better handle check numbers

- RockWeb/Blocks/Core/ScheduledJobDetail.ascx
Give administrators examples of cron expressions when they know essentially what they want to build, but can't remember the exact syntax.
Examples provided are a daily and a weekly syntax.
Fixes: #3103
n/a
n/a
> Amended Help Text for Cron Expression in Scheduled Job Detail block to provide examples

- Rock/Communication/Medium/Sms.cs
Basically, If I don't have a home phone, I might have written my cell phone in the "home phone" field and enabled SMS. When sending an SMS, it will send to that number.
However, if I then reply to that message, Rock will send back an error stating my number could not be found in the system. This is because the code for processing a response looks specifically at phone numbers of type `Mobile`.
See #3046 
Fix the problem so you can send SMS messages to Rock if your mobile phone is configured …
> Allow for SMS replies to come from non-Mobile numbers in Rock.

- RockWeb/Blocks/Crm/PersonUpdate.Kiosk.ascx
- RockWeb/Blocks/Crm/PersonUpdate.Kiosk.ascx.cs
- RockWeb/Blocks/Finance/TransactionEntry.Kiosk.ascx.cs
This fixes a couple of small bugs with the Kiosk blocks:
PersonUpdate.Kiosk
- Removed Validation from Person Profile Back and Cancel buttons
TransactionEntry.Kiosk
- Fixed an issue where someone would register through the transaction entry kiosk block and their address and phone number would not get saved.
N/A
> Kiosk Fixes

- RockWeb/Blocks/Event/RegistrationInstanceSendPaymentReminder.ascx
> Fixed Typo

- RockWeb/Blocks/Event/EventItemOccurrenceListByAudienceLava.ascx.cs
- RockWeb/Blocks/Finance/ScheduledTransactionSummary.ascx.cs
- RockWeb/Blocks/Finance/TransactionReport.ascx.cs
This pull request just fixes a few places to use RockDateTime instead of DateTime.  
> Fixed a few places where DateTime was used instead of RockDateTime.

- RockWeb/Blocks/Cms/PublicProfileEdit.ascx.cs
Fixed bug where First and Last fields were disabled for new family members in the Public Profile Edit block.
Fixes: #3272 
> Fixed Disable Name Edit so that new records can enter name.

- RockWeb/Themes/KioskStark/Assets/Lava/KioskGivingReceipt.lava
If a donor does NOT give anonymously via a card swipe kiosk, the receipt template errors.
Fixes: #3241
> Fix conditional in Kiosk Receipt Message

- RockWeb/Webhooks/TextToWorkflowTwilio.ashx
- RockWeb/Webhooks/Twilio.ashx
The current Twilio Webhooks process as an Async HttpHandler, but they do not include Exception handling. Thus if an internal error occurrs inside Rock while trying to process the request it will restart the entire app pool.
This PR wraps the two webhooks inside try/catch blocks and logs the exception to Rock's exception log.
Fixes: #3207 
> Updated Twilio webhooks so that they properly log exceptions

- RockWeb/Blocks/Finance/BatchList.ascx
- RockWeb/Blocks/Finance/BatchList.ascx.cs
> Added the ability to filter batches by source type on the Batch List block.

- Rock/Lava/Blocks/Sql.cs
Fixes the code for the SQL command block in Lava. It accepted parameters but my original PR somehow missed the line of code that actually passed the parameters to the SQL method.
Additionally, I think maybe my original implementation had never accounted for UPDATE statements. Either way this PR includes support for passing those parameters to statement commands too.
Fixes: #3306
> Fixed sql Lava command to work correctly with parameterized SQL statements

- Rock/Communication/Medium/Sms.cs
The SQL query to find existing response codes for previous SMS communications uses a `.StartsWith()` function in LINQ which translates to `LIKE '@%'`. This is a very expensive operation. This PR switches this to a `LEFT()` query in SQL which is a much faster operation.
Some churches, especially on Azure, are having timeouts with the current query syntax.
Fixes: #3209
> Improved performance of processing incoming SMS messages

- Rock/Communication/RockPushMessage.cs
When the code for the Rock.Communication.RockPushMessage class was (presumably) copied, the entity type reference did not get updated so it was returning an entity type of EMAIL instead of PUSH_NOTIFICATION.
Fixes: #3189
> Fixed RockPushMessage class to return the correct entity type

- RockWeb/Blocks/Event/CalendarLava.ascx.cs
Updates the calendar selector in the Calendar Lava block to always show the selected month.
Closes: #3285
> Update calendar selector to always show the selected month (Closes #3285)

- RockWeb/Blocks/Fundraising/FundraisingParticipant.ascx
- RockWeb/Blocks/Fundraising/FundraisingParticipant.ascx.cs
+ Fixed issue where the fundraising participant transaction grid was not showing the transaction detail amount (Fixes #3133).
> Fixed issue with Fundraising Participant Transaction Grid Details

- RockWeb/Themes/LandingPage/Styles/_variables.less
Changed the xs to sm breakpoint in the Landing Page theme.
Fixes: #
- [x ] Bugfix (non-breaking change which fixes an issue)
- [x ] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [x ] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [x ] By contributing code, I agree to license my contribution under …
> - Updated xs to sm breakpoint in LandingPage Theme.

- RockWeb/Blocks/CheckIn/Welcome.ascx
In 8.x the check-in countdown timer always shows 0:00:00 on some browsers due to the change for always showing in local time zone. This adjusts how the Date object is created so that it ensures the date is always created in the local time zone. Some browsers were creating it as a UTC date.
Fixes: #3384 
> + Fixed check-in countdown always showing as 0 on some browsers.

- RockWeb/Blocks/Crm/PersonDuplicateDetail.ascx.cs
Adds support for the Person Duplicate Detail block to have custom columns by adding the `ICustomGridColumns` interface to it.
Fixes: #3362
n/a
n/a
> Added support for custom columns to Person Duplicate Detail block.

- RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
The  'Allow External Updates to Saved Registrations' checkbox should actually work.
Fixes: #3401 
> Resolving an issue with the 'Allow External Updates to Saved Registrations' checkbox not functioning.

- RockWeb/Blocks/Reporting/DynamicData.ascx.cs
Adds a missing null check to the Dynamic Data Block to catch timeouts in certain circumstances.
Fixes: #3123
N/A
N/A
> Fix possible NullReferenceException when a Dynamic Data Block times out (Fixes #3123)

- RockWeb/Blocks/CheckIn/Success.ascx.cs
Version 8.5 added the ability to set a Success Template on each check-in configuration, but also came with an attribute on the Success block for the same purpose which is not used anywhere, a relic from the process, I presume.  @MikeDPeterson confirmed that this attribute should be deleted.
> - Removed obsolete Success Template field

- RockWeb/Blocks/Communication/CommunicationDetail.ascx.cs
- RockWeb/Blocks/Communication/CommunicationList.ascx.cs
- RockWeb/Blocks/Communication/CommunicationRecipientList.ascx.cs
These changes will update the communication detail, list, and recipient list to include push notification titles if they exist. Before this change, if a push notification was sent, then the list (or detail) would not show the title of that push notification. It would just be blank. This change allows the push notification title to display correctly.
Before:
After:
> Updated communication labels to include push notification titles

- RockWeb/Blocks/Reporting/PowerBiReportViewer.ascx
- RockWeb/Blocks/Reporting/PowerBiReportViewer.ascx.cs
The embedded Power BI report viewer in Rock has navigation that some organizations may not want to have displayed.  It takes up screen real estate and affects the looks of printed output.
Added 3 new block settings:
+ Show Fullsize Button (defaults to show which was previous behavior)
- hides or shows the zoom full size button in the upper left hand corner of the report
+ Show Right Pane (defaults to show which was previous behavior)
- hides or shows the filter pane on the right side of the report
+ Show Navigation Pane (defaults to show which was previous behavior)
- hides or shows the navigation tabs at the bottom of the report
* Also fixed typo on class name
Fixes: none
_Put an `x` in the boxes …
> Added block settings to show/hide controls in embedded Power BI report

- RockWeb/Blocks/Finance/BenevolenceRequestList.ascx.cs
Added a case for when the Status isn't one of the default statuses.
Fixes: #3519
- [ X ] Bugfix (non-breaking change which fixes an issue)
- [ X ] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [ X ] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [ X ] By contributing code, I agree to license my …
> Fixes Issue #3519

- RockWeb/Blocks/Core/NoteTypeDetail.ascx
Added a clarification help dialog for the "User Selectable" field on the note type creation/editing block. Documentation was available in the Admin Hero book, but is helpful here when trying to figure out why the new note type I just added won't let me add notes.
Fixes: #
- [x ] Bugfix (non-breaking change which fixes an issue)
- [x ] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without …
> Add Help dialog for NoteTypeDetail block

- RockWeb/Blocks/Event/RegistrationInstanceDetail.ascx
- RockWeb/Blocks/Event/RegistrationInstanceDetail.ascx.cs
Uses C# code inside the `BindRegistrationsGrid()` method to sort the grid, similar to how sorting is done for `TotalCost` and `BalanceDue`. This was done since the content of the column is conditional upon whether or not a Person record is tied to it or just `FirstName` and `LastName` fields.
Fixes: #3622
n/a
> Added ability to sort the Registrations tab by "Registered By"

- RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
The `FormHasWaitFields()` method seems to have just been missing a check to see if the `CurrentFormIndex` was in a valid range before checking the fields on that (non-existent) form.
Added check in the same syntax/format as the `CurrentRegistrantIndex` check it does.
Fixes: #3623 
> Note: This is set to merge against hotfix-1.8.8
This is such a complex block, it is hard to make any changes and know 100% for sure they work. But we implemented this …
> Fixed error when user tries to register for an event on the waitlist when inline signing is enabled

- Rock/Model/AttributeValue.cs
This fixes a bug that causes the History table to store encrypted values in plain text.
Fixes: Issue #3570 
> +Fixed 'Encrypted Text' field type as Person attributes logs history in plain text (Fixes #3570)

- RockWeb/Blocks/Fundraising/FundraisingParticipant.ascx.cs
Fixes error causing the Fundraising Participant page from rendering.
Fixes: #3649 
> Fixed GitHub issue #3649

- RockWeb/App_Code/GetImage.ashx.cs
Putting animated Gifs in your email to drive engagement is apparently the new hotness. We tried this and it didn't work. Turns out GetImage.ashx is sending images on to the resizer even when didn't ask it to, and this breaks the animation.
I added a method that adds up all of the query parameters we know aren't for Image Resizer and uses that to check to see if we need to get the image resized. This is similar to what was being done before just more thorough.
> Fixed animated gifs being turned into static gifs

- RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
This fixes an issue when registering for an event when the Registrar Option is set to "Use Logged In Person" where the Confirmation Email was not being set in the registration.
This is a very simple bugfix.
N/A
No migrations needed.
> Confirmation Email for logged in person registrar.

- Rock.Mailgun/Communication/Transport/MailgunHttp.cs
This sets the parameter type for the Reply-To parameter to GetOrPost.  The default on a RestRequest Parameter is Cookie which was not working.
Fixes: #3636 
This is a really simple change.
No documentation needs to be updated.
This does not require any migration changes.
> Fixes #3636 - Fixing an issue with the Reply-To header with the MailGun HTTP Transport.

- RockWeb/Blocks/Crm/PersonDetail/Bio.ascx.cs
Fixed an issue where numbers would never show up on mobile devices as tappable phone links
Fixes: #
- [ x] Bugfix (non-breaking change which fixes an issue)
- [ x ] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [ x ] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [ x ] By contributing code, I agree …
> Fix phone numbers to be tappable on mobile devices

- Rock/Workflow/Action/Communications/SendNotification.cs
This changes fixes an issue with the Send Push Notification workflow action. The action wouldn't correctly process any Lava added to a push notification message so the message appeared incomplete.
For example, we set up a workflow to send a push notification and put the following in the `Message` field:
`{{ Workflow | Attribute:'PrayerGiver', 'Object' | Property: 'NickName' }} has just prayed for you!`
This should have returned `Rich has just prayed for you!", but instead was returning " has prayed for you!"
This fixes that so it returns the correct string.
Fixes: n/a
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
> Fixes lava not processing correctly in push notification messages

- Rock/Web/UI/Controls/Grid/Grid.cs
This handles certain situations when attributes on a grid return null rather than an empty string.
This is a tiny self-explanatory change.
N/A
N/A
> Fixing a Null Reference exception when exporting a grid

- Rock/Workflow/Action/CheckIn/LoadGroups.cs
When the number of groups in a Check-In Configuration gets large, loading the groups becomes very slow because a separate query is done for every single group to see if the person is a member of the group.  Even when the number of groups isn't large, this is an inefficient way to get the data.
This will now retrieve all the person's groups one time and compare each group against that list, which significantly reduces the database queries made and speeds up the loading of the groups.  On our largest configuration, loading the groups on a family of four dropped from 4 seconds to 1 second.
Discussed change with @MikeDPeterson and confirmed pull request is desired.
_Put an `x` in the boxes that apply. …
> Improved performance of LoadGroups check-in action

- Rock.Migrations/Migrations/Version 9.0/Version 1.9.0/201905150435321_Assessments.cs
Fixes: #3797 
- [x ] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [x ] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
If your pull request requires a migration, please *exclude the migration from the Rock.Migration project*, but submit it with your pull request. Please add a note to your …
> proposed fix for #3797 to allow support for multiple Person Bio blocks

- Rock/Model/Schedule.cs
- RockWeb/App_Code/GetEventCalendarFeed.cs
The GetEventCalendarFeed class was not returning many recurring events that should have been included in the iCal feed, because it was attempting to query for events where the EffectiveStartDate and EffectiveEndDate range overlaps a requested date range, but EffectiveEndDate was populated with the date of the first occurrence.
This change will set EffectiveEndDate to be the end date of the final occurrence, or to 12/31/9999 if the recurrence has no end.
Fixes: #3502 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …
> iCal event feed now properly includes all recurring events that overlap with the requested date range.

- Rock/Workflow/Action/Communications/SendSms.cs
This fixes an issue where the SMS Send workflow action would silently fail if there was no text in the body of the message. Twilio can send attachment-only messages, so this change updates the workflow action to allow them.
Fixes: 3788
If your pull request requires a migration, please *exclude the migration from the Rock.Migration project*, but submit it with your pull request. Please add a note to your pull request that provides a heads up that a …
> - Update SMS Send workflow action to allow attachment-only messages (Fixes #3788)

- RockWeb/Blocks/Prayer/PrayerRequestEntry.Kiosk.ascx.cs
- RockWeb/Blocks/Prayer/PrayerRequestEntry.ascx.cs
> Fixed PrayerRequestEntry blocks showing top-level category in dropdown

- RockWeb/Blocks/Finance/BusinessList.ascx.cs
The `BusinessList` block was trying to bind the address without verifying it existed first. I added a check to only bind that field if the address exists.
Fixes: #3954
> Fixed exception in BusinessList block when a business had no address

- database/Functions/ufnCrm_GetFamilyTitle.sql
- database/Functions/ufnCrm_GetFamilyTitleIncludeInactive.sql
Mkinyon identified an issue with extra spaces being added in family titles when there are 2 adults with different last names.  I was able to replicate this issue as well, and it was due to not having a suffix in each name.  I also noticed that an extra space was being added for a single person as well.  I implemented mkinyon's suggestion from 10/19/2017 to address both issues.  I also updated the param and code comments as they weren't up to date.
Fixes: #2554 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging …
> - Fixed extra spaces in names and incorrect param/code comments (Fixes 2554)

- RockWeb/Blocks/Administration/DataAutomationSettings.ascx.cs
Home > Data Integrity > Data Automation > Data Automation Settings > Reactivate People.
When deselecting any of the "Data Automation Settings - Reactivate People - Any family member has an interaction of the following type in the last" - check boxes the setting is not saved.  
The Data Automation job will continue to execute with all interaction options enabled.
The change removed an IF statement where the setting was only saved if the check box was checked.
The InteractionItem constructor sets the IsInteractionTypeEnabled = true so if the setting is not saved, which it isn't if the box is unchecked, the setting will not be saved.
_Put an `x` in the boxes that apply. You can also fill these out …
> Corrected Issue with Data Automation settings for Interactions not saving

- RockWeb/Blocks/Security/RestKeyList.ascx
- RockWeb/Blocks/Security/RestKeyList.ascx.cs
I changed the `RestKeyList` block to show all rest keys, regardless of active / inactive status. 
I also, added a grid column to display and sort by the status.
Fixes: #1782 
I had to add a filter to only show REST type People with an associated user account. Otherwise, "deleting" a rest key left the Person in the list as inactive, which would have been a confusing user experience.
If your pull request requires a migration, please *exclude the …
> + Updated the RestKeyList block to show inactive REST users

- RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
This is a small change to the javascript to run they Credit Card Type Detector every time the final panel is opened as well to when the keyup() event is fired on the credit card field.
Fixes: #1717
N/A
N/A
N/A
> - Fixing an issue with the Credit Card Type Detector on Registration Entry (Fixes #1717)

- RockWeb/Blocks/Connection/ConnectionRequestDetail.ascx.cs
If there are no other opportunities to transfer to hide the transfer button.
Fixes: #3963 
- [ x] Bugfix (non-breaking change which fixes an issue)
- [x ] This is a single-commit PR. (If not, please squash your commit and re-submit it.)
- [ x] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [ x] I have read the [Contributing to …
> Fixes #3963 Transfer only if there are other opportunities

- Rock/Transactions/SendDigitalSignatureRequestTransaction.cs
Adds SignatureDocumentTemplateId to the Any clause that checks to see if the AppliesTo person has already signed the document.
Fixes: #3608 
> Fixes #3608. SendDigitialSignatureRequestTransaction

- RockWeb/Blocks/Finance/PledgeAnalytics.ascx.cs
Giving analytics was `Last, First`, and Pledge analytics was `First Last`. This PR changed Pledge analytics to match Giving analytics.
Fixes: #3139
> Update name formatting in pledge analytics to match giving analytics

- RockWeb/Blocks/Core/LocationDetail.ascx.cs
This is a change to the location detail block. The issue was that attributes don't save when creating a new location. I think it was because the attribute part of the form was created after the ViewState loaded. I changed the logic so that loads/creates the location entity in the OnInit and uses the same variable across the whole life cycle.
Fixes: #3657
I changed a lot. It seemed like it should be a simple fix, but in testing there was quite a bit …
> Improved location detail block. Fixes #3657

- RockWeb/Blocks/Reporting/DynamicData.ascx.cs
The dynamic data block when trying to decide between a date and date time column was only evaluating if there were seconds in the date time and not if a non-midnight time existed
Fixes: #4028
- [x ] Bugfix (non-breaking change …
> Fixed issue with Grid Results Not Showing Time if Seconds = 0

- RockWeb/Blocks/Cms/SiteDetail.ascx
- RockWeb/Blocks/Cms/SiteDetail.ascx.cs
These changes update the SiteDetail block to make Site entity attributes visible/editable.
https://community.rockrms.com/Rock/BookContent/14#creatinganewsite
The "create a new site" section could potentially updated to include this, but since there would be no site attributes out of the box, there wouldn't be anything visibly different.
> + Added the ability to see and edit values for entity attributes on the site detail block

- Rock/Jobs/GroupLeaderPendingNotifications.cs
The Group Leader Pending Notifications job was not correctly counting the number of pending individuals that notifications were sent for. The job log always showed "Sent __ emails to leaders _for 0 pending individuals_. 0 errors encountered."
There was already a variable defined for the number of pending people notified, …
> Fixed incorrect pending member count in the "Group Leader Pending Notifications" job's status message.

- RockWeb/Blocks/WorkFlow/WorkflowEntry.ascx.cs
Submitting on behalf of @cbump 
On occasion we have noticed odd behavior from our workflows especially if they are not persisted. The workflow would randomly restart. We noticed that this only happens on our production server. We discovered the higher number of CPUs on that server was causing the system time to not get propagated as quickly as expected. Microsoft promises that the system time only gets updated every 15ms at most. If the workflow last processed time matches the current time it will restart if not persisted. This change sleeps the thread for 1ms which allows the processor to get it's new accurae system time.
We have been running this for 6 months and it has fixed our issues.
_Put an …
> Fixed issue where workflow outruns system clock

- Rock/Workflow/Action/Utility/InteractionAdd.cs
This addition updates the Interaction add workflow action to be more specific in how it identifies the interaction component to tie the new interaction to. Previously, the context of the interaction channel id was not used even when it was provided by the workflow. This change includes that information, which accurately ties the interaction to the correct component when there are multiple components that match the same entity Id from different channels.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
> Added channel Id context to get component function of Interaction Add workflow action

- RockWeb/Styles/_rock-variables.less
Changes the declaration of `@autocomplete-text` color to not be the same color as the `@autocomplete-bg` color. This seems like it was just an oversight when initially setting this up.
Fixes: #4076 
_Put an `x` in the boxes that …
> - Fixed auto-complete text to no longer be same color as background.

- Rock/Web/UI/Controls/Grid/RockTemplateField.cs
RockTemplateFields in Rock Grids have an OnRowSelectedEnabled property that indicates whether clicking inside this column will fire the OnRowSelected event for the grid, but setting the property to false has no effect. This fix allows the property to be set. I confirmed that setting this property to false does prevent OnRowSelected from firing when clicking inside this field.
If your pull request requires a migration, please *exclude the migration …
> - Fixed bug that forced the OnRowSelectedEnabled property of the RockTemplateField to always be true.

- RockWeb/App_Code/GetImage.ashx.cs
Our CDN wasn't caching our images and we discovered the reason was a missing cachability header/ This PR adds this. We have been running this for a few months and our server is much happier.
> Add public cacheability header when the file type is marked as cacheable

- RockWeb/Blocks/Reporting/MetricDetail.ascx
- RockWeb/Blocks/Reporting/MetricDetail.ascx.cs
This PR adds the ability to use set values of metric attributes on the metric detail block.
> Added the ability to view and edit custom attribute values for metric entity on the metric detail block

- RockWeb/Scripts/Rock/Controls/fieldVisibilityWrapper.js
- When a conditional field is dependant on a radio button control the form didn't always validate - Fixes #4139
Adding support for radio buttons to the field visibility validation javascript.
Fixes: #4139 
_Put an `x` in the boxes …
> Prevent double postback for radio buttons

- Rock/Model/AttributeMatrixService.Partial.cs
The query used in this method is too broad. It currently looks at **all** Attribute Values that have a value of any kind. However, it's actually looking to see if the Attribute Value is exactly equal to a Guid, which will always be 36 characters.
This change adjusts the query to limit the where clause to limit to values of 36 characters exactly.
Fixes: #4127 
> + Improved performance of Orphaned Attribute Cleanup. (Fixes #4127)

- Rock/Utility/ExtensionMethods/StringHtmlExtensions.cs
Modified the string extension method SanitizeLava() to return an empty string if it is passed a null value. This brings its behavior in line with SanitizeHtml() rather than throwing an ArgumentNullException. 
Fixes: #4175
_Put an …
> Fixed SanitizeLava() to handle null values

- RockWeb/Blocks/Cms/ThemeStyler.ascx
Fix spelling error in the Font Awesome Alternate Fonts tooltip. It used the word `to` instead of `too` and that has been fixed.
Fixes: #
> - Fix spelling error in Font Awesome Alternate Fonts tooltip.

- RockWeb/Blocks/Reporting/MetricValueDetail.ascx.cs
In the Metric Value Details block set the required flag on the control based on the field from the metric value. 
Fixes: #4206 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're …
> + Fixed issue with Metric Value Details block (Fixes #4206)

- RockWeb/Scripts/summernote/plugins/RockAssetManager.js
- RockWeb/Scripts/summernote/plugins/RockFileBrowser.js
- RockWeb/Scripts/summernote/plugins/RockImageBrowser.js
The summernote editor plugins for Image Browser, File Browser, and Asset Manager insert HTML that points to files on the file system. When emails are sent and the inserted file names have spaces in them, they may get encoded so that the spaces become plusses (confirmed in gmail but forums on the web indicate this is true for some other email hosts as well).  When the file names are encoded this way, the URLs do not work and the images do not display and links do not work.
This change uses the encodeURI javascript function to encode the address of the file as it's being inserted into the editor, changing spaces to %20. This prevents them from being mis-encoded in the sending so that the images show up and links work properly.
_Put an …
> Encode URLs inserted by Summernote editor to prevent spaces from being changed to plusses when emailed.

- RockWeb/Blocks/CheckIn/Admin.ascx
- RockWeb/Blocks/CheckIn/Admin.ascx.cs
- RockWeb/Styles/_checkin-core.less
See #3631 for original PR discussion.
Re-worked the logic of the check-in Admin block to still do IP-based configuration even when Geo-lookups are enabled.
Moved the Javascript snippet that handles local storage into the `.ascx` file so that it is always available as it now might be triggered on postback rather than always on initial page load.
The change to the CSS less file was so that when both the Retry and OK buttons are displayed at the same time there is some whitespace between them.
Screenshots below.
Fixes: #3259
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …
> + Allow IP configuration and Geo configuration to both function at same time

- Rock/Web/UI/RegistrationInstanceBlock.cs
- RockWeb/Blocks/Event/RegistrationInstanceRegistrantList.ascx.cs
- RockWeb/Blocks/Event/RegistrationInstanceWaitList.ascx.cs
Add the Connection Status field to the Registration Registrant and Wait List Grids. 
Fixes: #3224
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
> Added Connection Status to Registration Registrant and Wait List Grids

- RockWeb/App_Code/Mailgun.ashx.cs
Rock was not inactivating bounced addresses when using the new API webhooks in Mailgun (the legacy API webhooks worked fine). This PR fixes Rock's Mailgun webhook to properly process bounced messages from the new Mailgun API.
We have sent out a few large emails since making this change and haven't noticed any issues. …
> Update Mailgun webhook to correctly handle bounces from the new API

- Rock/Workflow/Action/Communications/SendNotification.cs
This PR updates the `SendNotification` workflow action so that a URL can be passed to the notification.
Not really sure which category this fits in. It's not a bug, but an addition to a feature newly introduced in core. This has definitely not been approved by core.
> Update the SendNotification workflow action to allow sending a url to the notification

- RockWeb/Blocks/Cms/ContentChannelItemView.ascx.cs
Wanted to use a single block for all sermons. This feature accomplishes that desire using the Content Channel Item View (which logs interactions).
See in action here: https://rock.hubcitychurch.com/Sermons
That page is this block. When no `Item=` param is present, the last approved item in the Content Channel is set as the …
> + Added option to display most recent item if no url parameter provided.

- Rock/Model/AttributeValue.cs
We were having some issues with a workflow taking a long time to complete. This turned out to be a SQL timeout due to a full table scan on AttributeValue whenever setting a matrix to a person as a person attribute. Our database size was causing this to take too long and timeout. This change makes it so that it only searches through attribute values that are of an attribute that is a matrix field type. This takes the time on our server to go from timeout to milliseconds.
Fixes: #
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …
> Sped up attribute value query that was causing timeouts

- RockWeb/Blocks/Cms/Redirect.ascx.cs
Added new block setting to the Redirect block to indicate that a Permanent Redirect should be used. When enabled, a 301 status code is used instead of a 302 status code. This allows search engines to replace the existing listing with the new URL.
Most (all?) browsers will cache a 301 redirect forever - or at least until the cache is cleared. However, they do honor the cache header information so the cache header is set to 5 minutes, meaning the browser will request the original page again after 5 minutes (and probably be redirected again). This allows the admin a way to fix it if they redirected to the wrong page.
We have run into cases a few times (and have seen a couple questions on the community chat along the same lines) on how to do a permanent redirect to a new page because we want …
> Added ability to use 301 permanent redirect in Redirect block.

- Rock/Web/Cache/Entities/AttributeCache.cs
- Fixes #4367 - The IsAnalytic columns are not being created properly during the Process BI Analytics jobs
This is a pretty simple change to add a missing DataMember attribute to the IsAnalytic property on the AttributeCache object.
Fixes: #
_Put an `x` in the boxes …
> Missing IsAnalytic DataMember attribute.

- RockWeb/Blocks/Security/AccountEntry.ascx.cs
Fixes #4530.
Validates username against global variable.
Fixes: #4530
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …
> Validate username in AccountEntry block

- RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Add check for feeValues == null so we can remove the fee from the registrant.FeeValues. Additionally make sure payment amount and input for amount to pay are cleared out so payment amount isn't more than balance during submission. Tested with single/multiple fee type and with and without quantity. 
Fixes: #
What types of …
> + Fix inability to remove fees during registration (Fixes #4558)

- Rock/Field/Types/DateFieldType.cs
Change `controls.Count > 5` to `controls.Count >= 5` to fix error where Date Field Types don't load their saved configuration and instead use default configuration. 
Fixes: #4576 
_Put an `x` in the boxes that apply. You can also …
> + Fixed Configuration Value Set on Date Field Type (Fixes #4576)

- Rock/Reporting/DataFilter/Person/InRegistrationInstanceRegistrationTemplateFilter.cs
Fixed DataView filtering for Person In Registration Template excluding inactive instances 
Added in a line that filters the Registration Registrant query to active registration instances only unless the option to include inactive instances was selected. Additionally removes an extraneous semicolon and also removes an extraneous else statement that set the variable to the same value it had been initialized to. 
Fixes: #4607 
Small change.
If your …
> Fixed DataView filtering for Person In Registration Template (Fixes #4607) 

- RockWeb/Blocks/CheckIn/RapidAttendanceEntry.ascx.cs
The Rapid Attendance Entry block has a setting to disable its attendance functions and use it solely as a contact item entry. However, the block was checking for attendance settings even if attendance was disabled. This was causing the block to throw a null reference exception if the user hadn't selected a group / schedule …
> Fix Rapid Attendance Entry to allow disabling attendance

- Rock/Workflow/Action/Utility/WebRequest.cs
> Fix typo: enpoint -> endpoint

- Rock/Reporting/DataFilter/Person/ConnectionRequestDataViewFilter.cs
Fixed verbiage for Connection Request DataView Filter by replacing Benevolence with Connection.
Fixes #4758
Fixes: #
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any …
> Fixed verbiage for Connection Request DataView Filter

- Rock/UniversalSearch/IndexModels/BusinessIndex.cs
Adds business addresses to universal search indexing, mirroring the functionality of normal person records.
- [x ] New feature (non-breaking change which adds functionality, which has been approved by the core team)
_Put an `x` in …
> Add business addresses to universal search indexing

- Rock/Lava/RockLiquid/Blocks/Cache.cs
Fixes: #4672
The MergeLava function of the Cache class needs to look at all context scopes and not just the first one in order for a lava `cache` tag to work within scoped tags like `if` or `include`.
_Put an `x` in the boxes that …
> - Fixed issue where lava cache fails inside scoped tag (Fixes #4672)

- RockWeb/Blocks/Groups/GroupAttendanceDetail.ascx
Small javascript change to fix the "select all" functionality on the Group Attendance Detail Block.
Fixes: #4795 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of …
> Fix "Select All" shortcut on Group Attendance Detail block

- RockWeb/Blocks/Utility/HtmlEditorFileBrowser.ascx.cs
As noted in issue #4791, we have had issues with images being able to be selected in the image browser. This PR reorders the steps in OnLoad to check for ajax postbacks before doing additional work. Currently the block has it needlessly rebuilding the file tree before the much simpler ajax request to return the filename. We have a fairly slow file system for our image content and a large number of images stored in it. This caused our ajax callback to take 2-5 seconds. This fix reduced that time to ~25ms.
Fixes: #4791 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply …
> Fixes #4791 Reordered operations to speed up ajax postbacks

- RockWeb/Blocks/Core/CampusList.ascx
Fixes: #
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …
> -Added Campus Type and Campus Status columns to CampusList block.

- Rock/Model/GroupService.Partial.cs
The lava filter `FamilySalutation` and the "Combine Family Members" checkbox on merge templates were both causing a null reference exception because the `GroupService.CalculateFamilySalutation` method was trying to reference `calculateFamilySalutationArgs.RockContext` which wasn't being set in either of those 2 cases. …
> + (Group) Fixed FamilySalutation lava filter returning error

- RockWeb/Blocks/Crm/Documents.ascx.cs
… replace special characters in the downloaded file name with an underscore.  Resolves #4902.
Update the Document.ascx.cs download function to remove special characters from  the file name that is passed to the Response.AddHeader method call on line 508.
Fixes: #4902  …
> Document Block Multiple Content Disposition Fix

- Rock.Tests.Integration/Model/PersonTokenServiceTests.cs
- Rock.Tests.Integration/Rock.Tests.Integration.csproj
- Rock/Model/Core/PersonToken/PersonTokenService.cs
When "Person Token Use Legacy Fallback Value" was disabled, and an invalid token was provided, the `GetByImpersonationToken` method was still trying to access `personToken.PersonAlias.PersonId` even though `personToken` would be null.
This PR adds an early return to the `GetByImpersonationToken` method to return null if we …
> Fixed issue where invalid person tokens would cause an exception when legacy fallback was disabled

- RockWeb/Blocks/Finance/PledgeDetail.ascx.cs
When clicking on the Add Pledge button, under Contributions on a Person Profile, it takes you to the Pledge Detail page. This block has a couple of page parameters, one of them being "PersonActionIdentifier". The page is looking for "PersonActionIdentifier" in the URL while the previous block/button is passing through …
> Update Public String PersonActionIdentifier

- Rock/Workflow/Action/CheckIn/FilterLocationsByLocationSelectionStrategy.cs
Change line 162 from 
```
if ( location.Schedules.Contains( selectedSchedule ) )
```
to 
```
if ( location.Schedules.Select( s => s.Schedule.Id ).Contains( selectedSchedule.Schedule.Id ) )
```
so it will return true when schedules match since the objects themselves are not the same and always returns false otherwise. …
> + (Check-in) Fix issue in Filter Locations By Location Selection Strategy Workflow Action where schedules could not be matched. (Fixes #5062)

- RockWeb/Blocks/Reporting/MetricDetail.ascx.cs
Moves metric creation to occur sooner, so that the attribute values have something to be added to in the database.
Move Lines 507-513 further up in the MetricDetail Block code, so that the attribute values are assigned a proper EntityId on creation.
Fixes: #5079
_Put …
> Move metric creation (Fixes #5079)

- Rock.JavaScript.Obsidian/package.json
The npm task references the `build` directory but the directory in this folder structure is actually `Build` (case-sensitive).
On some operating systems the case sensitivity does not matter. On GitHub actions, case matters.
_Put an …
> Reference correct folder (case-sensitive)

- RockWeb/Blocks/Cms/MediaElementList.ascx
Fixes: #
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …
> - Fixed incorrect list name in Media Element List block.

- Rock/Web/Cache/RockCache.cs
- Rock/Web/Cache/RockCacheManager.cs
- RockWeb/Blocks/Cms/CacheManager.ascx.cs
In RockCache.cs there are two places where the namespace of the cache is assumed: 
[ClearCachedItemsForType](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.14.2/Rock/Web/Cache/RockCache.cs#L542)
[GetStatisticsForType](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.14.2/Rock/Web/Cache/RockCache.cs#L703)
This …
> Fix issue where WebsiteLavaTemplateCache cannot be cleared (Fixes #5250)

- RockWeb/Blocks/CheckIn/AttendanceHistoryList.ascx.cs
Submitting this PR to close this issue: https://github.com/SparkDevNetwork/Rock/issues/5313.
I made the changes straight through Github, so I'm not sure if the whitespace is exact in there.
I also wasn't sure whether this solution or another would be better to solve this.
```
Where( a => ( a.Group != null && …
```
> + (Group) Update AttendanceHistoryList to check for null Groups. (Fixes #5313)

- RockWeb/Blocks/Finance/TransactionList.ascx.cs
EntityTypeId = a.EntityId should have been EntityTypeId = a.EntityTypeId
**We cannot guarantee that your pull request will be accepted.** There are many factors involved.  We take into consideration whether or not the Rock system you run is a standard, main-line build.  If it is not, there is a lower chance we will accept your request (since it may impact a part of the system you don't regularly use).  Features that would be used by less than 80% of Rock organizations, or ones that don't match the goals of Rock, are other important factors.
Fixes: #
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …
> Typo fix on TransactionList.ascx.cs

- Rock.JavaScript.Obsidian/Framework/Controls/nmiGatewayControl.ts
- Rock.NMI/Controls/NMIHostedPaymentControl.cs
- Rock.NMI/Gateway.cs
- Rock.NMI/gatewayCollectJS.js
+ Corrected NMI URLs from secure.tnbcigateway.com to the secure.nmi.com
Simple update to correct the Rock RMS NMI gateway integration to use NMI owned nmi.com domains instead of 3rd party TransNational owned white label domain tnbcigateway.com. The URLs needed to be changed to nmi.com for multiple reasons including:
- NMI Collect.js will return a "user not found" when tokenizing when non-transnational NMI tokenization key is used. This is due to NMI scoping or targeting TransNational NMI customers based on the inbound domain name used to load the collect.js JavaScript resource. Changing from tnbcigateway.com to nmi.com allows all NMI customers to use the Rock RMS NMI gateway integration and not just TransNational NMI customers. 
- NMI.com is the directly owned domain and not a 3rd party …
> + Corrected NMI URLs from tnbcigateway.com to the nmi.com

- Rock.JavaScript.Obsidian.Blocks/src/Event/RegistrationEntry/registrar.partial.ts
Update the registrar.partial.ts to match the existing RegistrationEntry ASP.NET Control. The original block has columns and rows set up to be mobile-friendly, while the new Obsidian block is not laid out the same way. This PR would make it match up with the ASP.NET block just a bit more.
Fixes: #5334 
I made these changes directly from Github, so I'm unable to determine whether my whitespace/formatting is to standard. Since I made it from Github, …
> Adjust Registration Form Layout to match existing RegistrationEntry

- RockWeb/Blocks/Core/SignatureDocumentTemplateDetail.ascx.cs
Corrects a bug introduced by commit 59c56a44 that causes the dialog to lose track of which template was selected.
Recent updates introduced a bug for legacy signature providers in the template dialog that causes the selected template to not be visible.
Simple re-ordering of two sequential lines of code.
Fixes: #
What types …
> - Modified SignatureDocumentTemplateDetail

- RockWeb/Blocks/CheckIn/TimeSelect.ascx.cs
Adds a null check to the Time Select Check-in block so that if someone reaches that block without a person already selected, the block does not throw an unhandled exception.
This Pull Request was requested by @ethan-sparkdevnetwork on the #5446 issue. My previous Pull Request (#5447) had a fix in it that had already been implemented by another commit (https://github.com/SparkDevNetwork/Rock/commit/6d6e496786978d801b0000dde8b1033b5ea43554).
Fixes: #5446 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
> - (Check-in) Added a null check to the Time Select block (Fixes #5446)

- .github/PULL_REQUEST_TEMPLATE.md
**In case you are submitting a non bug-fix-PR, we highly recommend you to engage in a PR discussion first.**
There are many factors we consider before accepting a pull request. This includes:
1. Whether or not the Rock system you run is a standard, main-line build. If it is not, there is a lower chance we will accept your request since it may impact some other part of the system you don't regularly use.
2. Features that would be used by less than 80% of Rock organizations, or ones that don't match the goals of Rock.
With the PR discussion we can assess your proposed changes before you start working on it so that we can come up with the best possible approach to it. This may include:
1. Coming up with an alternate approach that does not involve changes to core.
2. Advising how your …
> Fixed Formatting Error in Pull Request Template

- Rock.Blocks/Event/RegistrationEntry.cs
- RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
This change fixes an issue in both the C# and Obsidian Registration Entry blocks where emails were not being saved on family members that were selected from the "Family Member to Register" dropdown.
This fixes that issue by adding Email to the list of person fields that are saved on existing people.
Fixes: #5497
If your pull request requires a migration, please *exclude the migration from the Rock.Migration project*, but submit it with your pull …
> Fixed Issue in Registration Where Email Was Not Saved on Family Members

- Rock/Web/UI/Controls/PersonLink.cs
Fixed C# Person Link Controls' tooltips not closing automatically by un-commenting the code that is supposed to hide the tooltip.
Fixes: #5577 
> Fixed an issue with the Person Link Control where tooltips would not automatically hide

- Rock/Data/DbService.cs
- Rock/Jobs/ProcessBIAnalytics.cs
**In case you are submitting a non bug-fix-PR, we highly recommend you to engage in a PR discussion first.**
There are many factors we consider before accepting a pull request. This includes:
1. Whether or not the Rock system you run is a standard, main-line build. If it is not, there is a lower chance we will accept your request since it may impact some other part of the system you don't regularly use.
2. Features that would be used by less than 80% of Rock organizations, or ones that don't match the goals of Rock.
With the PR discussion we can assess your proposed changes before you start working on it so that we can come up with the best possible approach to it. This may include:
1. Coming up with an alternate approach that does not involve changes to core.
2. Advising how your …
> - Fix CommandTimeout in ProcessBIAnalytics job

- Rock.Rest/ApiController.cs
When you try to do a PATCH to update an enum property through the API, it currently throws an exception. This fixes that bug. (The Status column of the FinancialScheduledTransaction entity is an example).
> Fix bug updating enums through API

- Rock.JavaScript.Obsidian.Blocks/src/Event/RegistrationEntry/registrant.partial.ts
- Rock.JavaScript.Obsidian.Blocks/src/Event/RegistrationEntry/registrants.partial.ts
Fixes an issue where registrations were not scrolling to the top when moving between registrants or when moving between a registrant's forms. This fixes that issue by adding scroll logic to the Next and Previous buttons on the Registrant and Registrants controls.
Fixes: #5612 
If your pull request requires a migration, please *exclude the migration from the Rock.Migration project*, but submit it with your pull request. Please add a note to your pull …
> Fixed an issue where the Next/Previous buttons would not always trigger the page to scroll to the top

- Rock/Lava/Filters/LavaFilters.cs
This fixes an issue in the PluralizeForQuantity lava filter where every number less than 1 was treated as not plural, which makes logical sense but is grammatically incorrect. This fixes that issue by treating every number as plural except for 1 and -1.
Fixes: #5682
> + (Lava) Fixed the PluralizeForQuantity filter to follow grammar rules when deciding what is pluralized

- RockWeb/Styles/_helpers.less
- RockWeb/Styles/utilities/_cssgrid.less
- RockWeb/Styles/utilities/_display.less
- RockWeb/Styles/utilities/_flex.less
- RockWeb/Styles/utilities/_ratios.less
This PR adds CSS helper classes to Rock's core styling framework to support CSS Grid as well as Fixed Aspect-Ratio elements.
This would be especially helpful for simplifying grid markup for attributes in workflow entry/event registration forms.
If this PR is accepted, I'm happy to add documentation for these additional classes to the [styling docs](https://community.rockrms.com/styling).
> + (CMS) Added styling helper classes for CSS grid and fixed aspect ratio elements

- Rock.JavaScript.Obsidian/Framework/Utility/page.ts
**In case you are submitting a non bug-fix-PR, we highly recommend you to engage in a PR discussion first.**
There are many factors we consider before accepting a pull request. This includes:
1. Whether or not the Rock system you run is a standard, main-line build. If it is not, there is a lower chance we will accept your request since it may impact some other part of the system you don't regularly use.
2. Features that would be used by less than 80% of Rock organizations, or ones that don't match the goals of Rock.
With the PR discussion we can assess your proposed changes before you start working on it so that we can come up with the best possible approach to it. This may include:
1. Coming up with an alternate approach that does not involve changes to core.
2. Advising how your …
> + Added defensive check in addQuickReturn function (Fixes #5906)
