Rock/Utility/ExtensionMethods.cs, RockWeb/Blocks/CheckIn/CheckinConfiguration.ascx.cs
Fixes #806.  Currently only groups for the top-level areas (group types) are being saved in ViewState.  This adds all N-child-level groups to ViewState.
I couldn't find a way to get N-levels deep using standard LINQ, so I also added a non-recursive IEnumerable<Flatten> extension method.  See comments below.
=> Save viewstate for all levels of groups & labels

Rock/Model/AttendanceCodeService.Partial.cs
Generated codes can be larger than three characters. Modified noGood list to check if code "contains" a noGood, instead just equals.  Also, added two noGood codes.
=> Modified for larger attendance codes. Added 2 noGoods.

RockWeb/Styles/developer.css
This adds font smoothing to core and check-in blocks.  It's noticeably better on Chrome for Windows, high-res screens and Chromebooks (which is how we're planning to run check-in).
=> Add text antialiasing and font smoothing

Rock/Attribute/BinaryFileFieldAttribute.cs, Rock/Rock.csproj
This adds an attribute that can be used to show a binary file field on a workflow action.  I made the binaryFileTypeGuid required since, without it being set, the field has no options and doesn't make sense.
=> Add a binary file picker attribute

Rock.Rest/ApiController.cs, Rock.Rest/Controllers/PeopleController.Partial.cs, Rock.Rest/Controllers/TaggedItemsController.Partial.cs
This will improve the efficiency of 3rd party software that uses the REST endpoint.  This is a very common requirement to need the Id (among other data points) when creating an entity through a REST client.
Consider this real world example of NewSpring's current usage:
1.) Create person locally
2.) Be sure to assign guid for reference
3.) 1st API request POST to Rock to create person there
4.) 2nd API request GET person back from Rock by Guid
5.) Update local person with Rock's Id and other default data (guid, primaryAliasId, etc) assigned upon creation
And with this pull request:
1.) Create person locally
2.) 1st API request POST to Rock to create person there
3.) Update local person with Rock's Id and other default data assigned upon creation …
=> Return the created entity after a REST POST

Rock.Rest/ApiController.cs
Otherwise they throw cannot convert int64 to enum
Fixes #960
=> Enums should be treated as ints

Rock/Data/DbContext.cs, Rock/Model/WorkflowTrigger.cs, RockWeb/Blocks/WorkFlow/WorkflowTriggerDetail.ascx
This feature is an immediate-post-save workflow trigger option.  This option is ideal for workflows that should be executed at run-time (not queued for a transactional worker) and that require the database assigned Id to be set.  
NewSpring will be using this workflow trigger type for our REST based sync between Rock and our other platforms.  The workflow, REST Sync, requires that the Id be assigned already to newly created entities and we want the sync to be real time.
I did not see the value in adding an immediate post delete.  The reason is that pre-delete would function effectively the same way because an entity being deleted already has a database assigned id.
=> Feature immediate post save trigger

Rock/Reporting/DataSelect/Group/MemberCountSelect.cs, Rock/Rock.csproj
Adds a report field that replicates the functionality of the Member Count DataFilterComponent.
The field shows total Members for a Group, with optional filters for Status and Is Leader.
I have added this field to a new category called "Statistics", because I have some plans to add other fields of this type in the future.
=> Added Report Field "Group/Member Count"

RockWeb/Blocks/Finance/BatchList.ascx, RockWeb/Blocks/Finance/BatchList.ascx.cs
We imported our historical batches from FellowshipOne (26k of them) and the FinancialBatch page tries to load all of them at once (it can't).  EF throws a timeout error after about 30 seconds.
This implements a RowLimit filter preference based on the [TransactionList](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionList.ascx.cs#L758) pattern.
=> Enforce a row limit on FinancialBatch List block

RockWeb/Blocks/CheckIn/AttendanceReporting.ascx.cs
This allows the attendance reporting to ignore however deep a group might be. 
In our case groups are at least 3 levels deep and are getting pushed out of the column they should live in:
.
=> Add group ancestry block attribute

Rock/Model/DataViewService.Partial.cs, Rock/Reporting/DataSelect/Group/ParticipationRateSelect.cs, Rock/Rock.csproj
The purpose of this field is to show the number of people that are participating in a Group from a set of candidates defined by a Person Data View.
This can be used to answer questions such as "How many people aged 18-25 are participating in Small Groups"? I intend to add a roll-up feature to summarize the count for a parent group and all its children in a later update.
I have replicated the "IsViewInFilter" method from the OtherDataViewFilter class in the DataViewService so that it can be used more generally. I wasn't sure where to put it, so if this is wrong any guidance is appreciated.
=> + Added Report Field "Group/Participation Rate"

Rock/Field/Types/BooleanFieldType.cs
When a Boolean Field is show as a Grid column and the Filter is blank, the filter should be ignored. Instead, the filter only returns records with an empty value in the Boolean Field.
=> - Fixed issue with empty Boolean Field filter

Rock/Reporting/DataSelect/Person/AddressSelect.cs
This pull localises the address report field address parts, removes the blank default from the address type select (line 184) to make it consistent with the phone number type report select (and remove an unnecessary click).
It also changes the generic state enum to region to make it consistent with AddressControl.
As always I'm sure there are whitespace and formatting issues I've missed.
=> Localise the Address Report Field Address Parts

RockWeb/Blocks/Groups/GroupRegistration.ascx, RockWeb/Blocks/Groups/GroupRegistration.ascx.cs
Allows the Register button to use alternate text like "Sign Up" or "Contact Leader".
=> Add Register Button Alt Text

Rock/Workflow/Action/CheckIn/FilterGroupsBySpecialNeeds.cs, Rock/Workflow/Action/CheckIn/LoadGroups.cs, Rock/Workflow/Action/CheckIn/LoadLocations.cs, Rock/Workflow/Action/CheckIn/LoadSchedules.cs, Rock/Workflow/Action/CheckIn/SaveAttendance.cs, RockWeb/Blocks/CheckIn/Admin.ascx.cs, RockWeb/Blocks/Finance/ScheduledTransactionEdit.ascx.cs, RockWeb/Blocks/Finance/TransactionEntry.ascx.cs, RockWeb/Blocks/Reporting/DynamicData.ascx, RockWeb/Blocks/Reporting/DynamicData.ascx.cs, RockWeb/Blocks/Utility/DefinedTypeCheckList.ascx.cs
Fixes and simplifies any code relying on GetAttributeValue to return a known boolean string.
Found the issue when FilterBySpecialNeeds was edited to display "Yes" or "No" instead of true/false.
There are a few instances where the default value was true (like TransactionEntry: Show Additional Accounts). In those instances the resultIfNullOrEmpty parameter is set to true.
=> Fix Boolean FormatException processing Attribute Values with "Yes" or user-defined text instead of "True"

Rock/Workflow/Action/CheckIn/FilterGroupsByAbilityLevel.cs, Rock/Workflow/Action/CheckIn/FilterGroupsBySpecialNeeds.cs
SpecialNeeds was checking for an attribute value prior to person.Attributes being loaded from the database.  
AbilityLevel was checking for an attribute value but always loading person.Attributes (maybe it was the first action in the stock workflow?).
Now attribute values are available regardless of the workflow action order.
=> Fix issue with FilterBySpecialNeeds checking for a null attributevalue

Rock/Workflow/Action/CheckIn/FindFamilies.cs, Rock/Workflow/Action/CheckIn/FindFamilyMembers.cs, Rock/Workflow/Action/CheckIn/FindRelationships.cs
I've gone back through our workflow looking for performance benefits and there are a couple workflow actions that weren't standardized with AsNoTracking.
=> Sweep to add AsNoTracking to read only lookups

RockWeb/Blocks/Groups/GroupDetailLava.ascx.cs
Group Detail Lava was trying to parse non-existent query strings and when the member ordering was introduced in 5b56a30da091eb7c27f542e7b92486c33283b40d a possible exception was created.
=> Fix Exception in Group Detail Lava

RockWeb/Blocks/Crm/PersonDetail/AddFamily.ascx.cs
If there is only one campus, the Add Family campus field will default to it.
=> A default campus for the Add Family block

RockWeb/Blocks/Finance/AccountDetail.ascx, RockWeb/Blocks/Finance/AccountDetail.ascx.cs
This adds a textbox allowing a user to edit the Url attribute of a FinancialAccount. NewSpring plans to use the Url attribute to specify an image for the account and would like to be able to manage this from the Rock interface.
=> Add a UI control for a FinancialAccount's URL

RockWeb/Blocks/WorkFlow/MyWorkflows.ascx
Changed margin size for toggles on My Workflows block from md to sm.
Before:
After:
=> Update Margin Size on Toggles For My Workflows

Rock.Rest/Controllers/AuthController.cs, Rock/Model/PersonService.Partial.cs, Rock/Rock.csproj, Rock/Security/Authentication/Twitter.cs, Rock/SystemGuid/Attribute.cs, RockWeb/Styles/_rock-core.less, RockWeb/Themes/DashboardStark/Styles/theme.css, RockWeb/Themes/Flat/Styles/theme.css, RockWeb/Themes/KioskStark/Styles/theme.css, RockWeb/Themes/Rock/Styles/theme.css, RockWeb/Themes/Stark/Styles/theme.css
I've added in a Twitter Authentication Service.
It's worth noting that the service won't match emails unless the application is whitelisted (which involves a request to Twitter support) per [these docs](https://dev.twitter.com/rest/reference/get/account/verify_credentials).
I've also added a method for splitting a full name into a separate first and last name. I had no idea where to put it so I stuck it in PersonService.Partial which I'm more than certain isn't the right place. If you move it when you pull then you'll want to change line 290 of the authentication class as well.
=> Add Twitter Authentication Service

RockWeb/Blocks/WorkFlow/MyWorkflows.ascx.cs
Overview:
---
This code change allows the My Workflow block to be filtered via query string.
Example:
---
Using the following url [http://localhost:6229/?RoleFilter=false&StatusFilter=true](http://localhost:6229/?RoleFilter=false&StatusFilter=true) on page load (not on a post back) the My Workflow block shows only workflows that are assigned to the current user and active.
Use Case:
---
We are building a notification block which shows the current number of active workflows assigned to the current user.  Now with the help of the url query string when the user clicks on the notification icon the user is taken directly to a page with the My Workflow block already filtered to show only the workflows that are assigned to them and currently active.
=> Enhancement - Enables Url Query Filters For My Workflow Block

RockWeb/Scripts/Rock/Controls/util.js
I'm running into a scenario where I have to dynamically load the google maps API on certain pages. Some blocks (GroupDetailLava.ascx for example) add the google maps API on page load and do not use the rock util for it. The problem I'm having occurs when I am using pages with these blocks. Calling the rock util to load the gmaps api neither loads the api nor fires the loaded event — leaving my scripts waiting for the event.
To fix this I could either 1. check for the gmaps object before trying load in my own scripts, or 2. we could have the util fire the loaded event if the api is already loaded. Here's an implementation of option 2.
=> googleMapsIsLoaded

RockWeb/Blocks/Core/CampusContextSetter.ascx, RockWeb/Blocks/Core/CampusContextSetter.ascx.cs, RockWeb/Blocks/Core/GroupContextSetter.ascx, RockWeb/Blocks/Core/GroupContextSetter.ascx.cs, RockWeb/Blocks/Core/ScheduleContextSetter.ascx, RockWeb/Blocks/Core/ScheduleContextSetter.ascx.cs
@azturner Added query string support to the CampusContextSetter, GroupContextSetter, and a new ScheduleContextSetter block.
There's also now an option to clear the context once it's been set:
The text displayed to clear/unselect an item is set by a block setting.
=> Add support to context setters to honor query string (fixes #1253)

RockWeb/Blocks/Core/CampusContextSetter.ascx.cs, RockWeb/Blocks/Core/GroupContextSetter.ascx, RockWeb/Blocks/Core/GroupContextSetter.ascx.cs, RockWeb/Blocks/Core/ScheduleContextSetter.ascx.cs
- Adds a missing CSS class from GroupContextSetter.ascx
- Adds a block setting to always display query strings on CampusContext, GroupContext, and ScheduleContext
- Sets the GroupType context when a Group is set
- Adds an option to display grandchildren of the base GroupType
=> Add additional context enhancements to 1.4.0

RockWeb/Blocks/Crm/PersonDetail/Bio.ascx.cs
By default the setting is set to false.
We had the requirement to display people's middle names for security reasons.  Seems like something that would be nice to have as core functionality.
=> Added setting to display the middle name of a person on the bio block.

RockWeb/Blocks/Connection/ConnectionRequestDetail.ascx.cs
When the list gets log, it's harder to find the group you want.  Sorting by name makes it easier to scan through the list.
=> Sort drop down list for placement groups by Name.

RockWeb/Blocks/Core/DateRangeContextSetter.ascx, RockWeb/Blocks/Core/DateRangeContextSetter.ascx.cs
@azturner @edmistj I built this block for the dashboards we're using and matched it to the Analytics work you've been doing.
Two deviations from the other context blocks:
- Stores the date range in the current user's preferences (requires the user to be logged in)
- padding: 10px currently hardcoded in the block but should be added to theme.css
If you don't want this in core feel free to close it.
=> - Add a DateRange context setter to core

Rock/Model/PersonService.Partial.cs
I was getting a null reference exception when adding a new person (not in the database yet) to a group.  The problem was that I had not set a RecordTypeId on the person and this code was throwing the exception.  The `DefinedValueCache.GetName` method supports `int?` so I made it pass as-is since `RecordTypeValueId ` is a non-required field.
=> Add new person to group from API error

Rock/Web/UI/Controls/NewFamily/Members.cs
We noticed that users were often overlooking the "Add Person" control on the "Add Family" page.  I made a change to make that control resemble the control used on the "Edit Family" page.
It looks like this:
=> Make the new family control to add a person match the edit family control to add a person

RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
`CurrentPerson.NickName` is null in our registration scenario and causes a null reference exception on the `CurrentPerson.NickName.Trim()` within the `if` statement.
Because `NickName` is not a required field, I opted to assign it to the value of `FirstName` - though there are many other ways this null reference exception could be remedied.
=> Registration - NickName is null and throws a null reference exception

Rock/Utility/ExtensionMethods/StringExtensions.cs
Many of the string extensions, such as SplitCase (https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Utility/ExtensionMethods/StringExtensions.cs#L71) return null when the context string is null.  I expect that `Left` should do the same thing.  Currently it throws a null reference exception.
=> Left String Extension - Return null if the string is null

Rock/Transactions/ConnectionRequestChangeTransaction.cs
When Workflow trigger is Request Connected,  check connection state is equal to 'connected', not 'inactive'
=> Hotfix connection connected status workflow trigger

RockWeb/Blocks/Core/GroupContextSetter.ascx.cs, RockWeb/Blocks/Core/ScheduleContextSetter.ascx.cs
After getting our production server up, the Order of Groups and Schedules was all over the place.  
We could've changed the order on all our Groups and Schedules but it's easier to have the selector order by Name.
Here's an example of previous behavior:
=> Order Groups and Schedules by name in Context Selectors

RockWeb/Blocks/CheckIn/Manager/Locations.ascx.cs, RockWeb/Blocks/CheckIn/Manager/Person.ascx.cs, RockWeb/Blocks/CheckIn/Manager/SelectArea.ascx.cs
Per https://rockrms.slack.com/archives/check-in/p1448843537000032:
>
David Turner [7:32 PM] 
@mrupsidedown: You have several existing fields on the attendance record that you can use to track this type of information. Which fields you choose sort of depends on how you want attendance to be reported for those people that haven't yet shown up at the classroom.  The existing SaveAttendance action in the out-of-the-box workflow updates the StartDateTime, and DidAttend flags whenever a person checks in.  You could clone this action, and update it so that it does not set one or both of these fields until the child actually shows up at the classroom. And there is already an EndDateTime field that can be used to track when a child "checks out" of the classroom.  In addition to those fields, there …
=> Update the check-in manager to exclude people who have checked out

Rock/Workflow/Action/CheckIn/FilterGroupsByAge.cs
See the following;
- https://github.com/SparkDevNetwork/Rock/issues/1281
- http://www.rockrms.com/Rock/Ask/Troubleshooting/Questions/579
- https://github.com/NewSpring/Rock/issues/151
TL;DR in certain edge cases, an AgePrecise of 2.9955191256830603 would get filtered out of a group with an AgeRange of 2.99.  Fixed with PR.
I tracked down the issue to the AgePrecise value.  Since double is stored as a fractional number in C#, the precision is only limited by the data type and was being calculated with 16 degrees of precision.  Conversely, most of our Groups were using an AgeRange precision of 0 (and usually a max precision of 2).  
In order to consistently compare the ages, I adjusted the local AgePrecise data type to a decimal and limited the precision to whatever the group AgeRange is …
=> - Fix issue with check-in "randomly" not allowing check-ins

RockWeb/Blocks/Event/EventItemListLava.ascx.cs
Copied directly from HTML content block. For our usage, if there was no campus selected, and use campus context was set on the block, the block would display _all_ of the events, for every campus. With access to the context object we can detect if the campus context has not been set (in the lava template) and prompt the user to select a campus instead.
=> Add context object to EventItemListLava block

RockWeb/Blocks/Core/Attributes.ascx
Buggy Behavior
---
When text in an attribute grid for categories is longer than expected the text overflows the grid, and grid buttons aren't immediately visible.
Fix
---
Removed the ItemStyle-Wrap which now allows the category field to wrap properly, and not overflow the grid.  This pattern is very similar to how the Description field in Defined Types (which is also the third column in the table) handles it's content.
=> Attribute Block category wrap

Rock/Web/UI/Controls/Grid/GridFilter.cs, Rock/Web/UI/Controls/Pickers/DateRangePicker.cs, RockWeb/Blocks/Reporting/DynamicData.ascx.cs, RockWeb/web.config
- Adds an option to Dynamic Data Block's options that turns filters on or off (off by default to maintain current functionality)
- When enabled, a filter is available for each column within the dynamic data.  Boolean columns are filterable with a drop down list that presents blank (no filter), yes (show only true values), or no (show only false values).  Date columns use a date range picker control.  All other columns use a text box.  String fields filter as a "begins with" filter.  All other fields filter for an exact match of the text box contents.
- Adds `DateRangePicker.TryParse` that mimics the functionality of `DateTime.TryParse` but for delimited values generated from the `DateRangePicker`
- Fixes issue where calling `GridFilter.DeleteUserPreferences` was not actually deleting …
=> Filters for the Dynamic Data Block

Rock/Model/Person.cs
- Prevent possible null reference exception on the transition date by providing a default value
- Break nested ternary expression into more readable pieces
- Fix bug - if today were less than the transition date, the `GradeOffset` were set to graduation year instead of graduation year minus current year
=> Fix Person WhereGradeOffsetRange Query

RockWeb/Assets/Misc/GoogleAnalytics.txt
> Universal Analytics is the new operating standard for Google Analytics; however, many sites and applications still use outdated tracking libraries to send data to Google Analytics.
> It is strongly recommended that you upgrade to use a Universal Analytics tracking library such as analytics.js or the latest mobile SDKs for Android and iOS. Non-Universal Analytics libraries, including ga.js or v1.x of the mobile SDKs, will be deprecated sometime in the near future.
— https://developers.google.com/analytics/devguides/collection/upgrade/
Also see: https://support.google.com/analytics/answer/2790010?hl=en
=> Upgrade google analytics tracker to latest

RockWeb/Blocks/Event/CalendarLava.ascx.cs, RockWeb/Themes/Flat/Assets/Lava/CalendarGroupedOccurrence.lava, RockWeb/Themes/Rock/Assets/Lava/CalendarGroupedOccurrence.lava, RockWeb/Themes/Stark/Assets/Lava/CalendarGroupedOccurrence.lava
We've run into an issue at our church where events with 4-8 occurrences in the same month would clutter the calendar page. This problem could be fixed by grouping occurrences together under the events that they're tied to. The code below implements this. It adds a new 'EventItems' lava object that contains arrays of occurrences, grouped by their EventItems. Users can use either the existing EventItemOccurrences object in their lava files to keep the existing behaviour, or use the new EventItems object along with the new CalendarGroupedOccurrence.lava file to group occurrences together. 
Additionally, it exposes the occurrences' notes to Lava.
Below are screenshots of the same occurrences using the existing lava file and the new lava file.
**Using existing Calendar.lava**
**Using new …
=> Added ability to group event occurrences in the calendar by event

Rock.Rest/Controllers/FinancialTransactionsController.Partial.cs, Rock/Model/FinancialTransaction.cs
- Add endpoint to get a person's giving group's transactions.  This mimics the TransactionList block functionality with a person context (https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionList.ascx.cs#L906)
- Add `DataMember` to AuthorizedPersonAlias to allow `$expand` ODATA operation
=> API Transactions by Giving Group

Rock.Rest/Controllers/MetricsController.partial.cs
Updating the LastValue merge variable for the LiquidDashboardWidget to sum all metric values entered for the last value date.
=> Fixes #1427 - Liquid Dashboard Widget summing all LastValue Metrics

RockWeb/Blocks/Event/EventItemListLava.ascx.cs
2 reasons:
- When using campus context, this field is not necessary.
- When left blank, events for all campuses will show up, even after adding
a new campus. To do that currently, you would need to add the new campus
to the selection after adding a campus to Rock.
=> Make campuses not required for EventItemListLava

RockWeb/Blocks/Groups/GroupAttendanceList.ascx.cs
This change optimizes performance on the Group Attendance list.  With the default range of a year, one of our larger groups has to calculate 971 attendances.  With this change, only 32 attendances are calculated.
Users can still update the date range filter to a longer/shorter period of time if needed, and that change will be saved to their preferences.
=> Update the default date range for Group Attendance to 3 months instead of a year

Rock/Web/UI/Controls/Grid/Grid.cs
Fixes #1464 by passing the data-priority attribute to the column headers even when sorting is not enabled.
=> Fixed column headers not being responsive

Rock/Rock.csproj, Rock/Utility/ExtensionMethods/DecimalExtensions.cs, Rock/Workflow/Action/CheckIn/FilterGroupsByAge.cs
This removes the dependency that "AgeRange" will always be the key for a group age range attribute.
Also fixes an edge case related to #1385 by adding a Decimal GetPrecision extension. The issue is for an age of 5.97, which MidpointRounding causes to round up to the nearest even number (6).
=> [EN] Remove hardcoded attribute keys from Filter Groups By Age and fix edge case

RockWeb/Blocks/Cms/HtmlContentDetail.ascx, RockWeb/Blocks/Cms/HtmlContentDetail.ascx.cs
The first time a user clicks the 'Save' button a warning box will appear listing any HTML errors should there be any. The warning box will prompt the user to click the 'Save' button again should the errors be intentional, after which the new content will be saved.
=> Attempting to save invalid html in the HtmlContentDetail block now displays a warning message detailing the errors.

Rock/Storage/Provider/FileSystem.cs
Fixes #1471 (see discussion there).  When trying to unit test the file storage provider, `HostingEnvironment.MapPath` would return NULL since it's not run in IIS context.  CreateDirectory then throws an exception because the path isn't valid.
This keeps the current behavior inside IIS environments, but returns the relative path otherwise.  
Confirmed working with an assortment of 50 docs/pdf's and a relative path of `~/` and `~/App_Data/Files`.  
*Note*: when using an absolute path for unit testing outside IIS, `C:\inetpub\wwwroot\App_Data\Files/[fileGuid]` gets written into the BinaryFile.StorageEntitySettings, and GetFile returns an error.
=> Adjust the FileSystem provider to return a path outside of IIS contexts

Rock/Web/UI/Controls/SearchField.cs
Currently, even though an administrator can limit security on a SearchComponent, anyone is able to view and search by it. This code change uses the SearchComponents' security settings to dictate who can actually view them, while adding .12 milliseconds to the page's load time. Below are two examples of users with the SearchComponents they can search by:
Admin Admin, a user with view access to the BusinessName SearchComponent:
Ted Decker, a user without view access to the BusinessName SearchComponent:
=> - Added security to the SearchField control to limit the SearchComponents people can view.

Rock/Web/UI/Controls/EmailBox.cs, Rock/Web/UI/Controls/NumberBox.cs, Rock/Web/UI/Controls/UrlLinkBox.cs
Currently NumberBox, EmailBox, and UrlLinkBox are all input fields of type 'text'. This code changes their types to be (respectively) 'number', 'email', and 'url'. This would allow mobile users to be presented with a custom virtual keyboard tailored to the data they're entering, rather than the generic alphabet virtual keyboard.
Example virtual keyboards:
http://blog.teamtreehouse.com/using-html5-input-types-to-enhance-the-mobile-browsing-experience
=> Enabled custom mobile keyboards for mobile devices when using NumberBoxes, UrlLinkBoxes, and EmailBoxes.

Rock.Rest/Controllers/WorkflowActionTypesController.Partial.cs, Rock/Web/UI/Controls/Pickers/WorkflowActionTypePicker.cs
Previously workflow action pickers were returning the EntityTypeCache Friendly Name (Send Sms), this changes them to use the MEF component name (Send SMS) to match the rest of the workflow UI.
=> Change Workflow Action Pickers to use Action Component Name

Rock/Web/UI/Controls/ModalDialog.cs
Added public reference for modal header and footer controls
Added public reference for close link visibility
The ability to add controls to the footer and header, such as additional buttons or add highlight labels, has been a continued need in our work. These changes would give developers additional control over the modal dialog.
=> Added additional references to ModalDialog controls

Rock/Model/Person.cs, RockWeb/Blocks/Crm/PersonDetail/Bio.ascx.cs, RockWeb/Blocks/Crm/PersonDetail/GroupMembers.ascx.cs
The current ages for any child under the age of 1 just appear as 0 which doesn't provide meaningful information. If a family visitor wanted to know the age of the child they'd have to do the maths themselves. This pull request adds a new method to the Person model for getting a string with a formatted age.
E.G. 12 yrs old, 6 mnths old, 14 days old
Comparison images below.
=> [EN] Better Ages on the Person Profile for Newborns and Infants

RockWeb/Blocks/Finance/TransactionDetail.ascx, RockWeb/Blocks/Finance/TransactionDetail.ascx.cs
This adds support for being able to update/edit custom attributes on FinancialTransactions. I'm not 100% sure if there needs to be additional discussion about this but this is a feature we need to replace the Project functionality we used in Arena. We have a defined type which contains all the values needed for different projects and just set that as an attribute on the FinancialTransaction record.
=> Adding support for updating/editing FinancialTransaction entity attributes

Rock/Rock.csproj, Rock/Utility/ExtensionMethods/GridExtensions.cs, RockWeb/Blocks/Event/RegistrationInstanceDetail.ascx, RockWeb/Blocks/Event/RegistrationInstanceDetail.ascx.cs
Our student and care ministry wanted to be able to see/sort the discount code used for a registration.  This adds an option to display that next to the Total Cost.  Viewing that column is turned off by default.
=> [EN] Adds an option to display the discount code used during Event Registration

RockWeb/Scripts/Rock/Controls/util.js
Fixes issues where the loading event would be incorrectly triggered during
the loading of the maps api.
Example:
1. Script A calls `loadGoogleMapsApi`
2. Rock appends google maps script to head
3. Browser begans loading process
4. Script B calls `loadGoogleMapsApi`
5. API is still loading, but Rock fires the loaded event anyway
6. Script B errors as google is undefined
=> Fix dynamic google maps loading

Rock/Model/Person.cs
Also updated the condensed option to return 0 rather than empty string if the age is less than 1.
Currently, when the current year is later than the birth year, but the age is 0, FormatAge would skip the month logic and go to the day logic. Example: Birthday 9/20/15, current day 5/24/16, FormatAge shows age as 4 days. Didn't test old functionality if the current day was before the birthday too but I suspect it would either return a negative number of days or just a blank.
This new code has been tested with a range of birth dates and current dates and should produce correct results for all cases.
=> Updated FormatAge to work properly for persons less than 1 year old.

Rock/Utility/ExtensionMethods/StringExtensions.cs
This adds AsDictionary and AsDictionaryOrNull to the string extensions.  The methods attempt to convert string to an dictionary using the |/comma and ^ delimiter Key/Value syntax.
=> New AsDictionary String Extension methods

RockWeb/Blocks/CheckIn/AttendanceHistoryList.ascx.cs
The only issue here is with the Grid Filter: I want to set the default value to DidAttend and have that visible *without* having to set the user preference, because if a user's preference is [All] then it gets reset to [Did Attend] on the next visit to the page.
However, since the [Grid Filter only reads from user preferences](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Web/UI/Controls/Grid/GridFilter.cs#L227) to display values, I can only override the user preference to have it visible.  
If I don't override the user's preference then the history is filtered without any clear visible indication (which as a user, I would consider a bug).
=> [EN] Adds a block option to Attendance History to set DidAttend by default

RockWeb/Blocks/CheckIn/AttendanceAnalytics.ascx.cs
One of our larger campuses has been unable to pull attendance data for Easter weekend, so this will be the first round of optimizations. Feel free to merge this and I'll open new PR's for the others.
This PR optimizes the block code to defer filtering on the attendee visit data set (in our case, was 1k+ rows) instead of forcing the data set to recalculate after every filter.  
I also removed duplicate code that added demographic and visit information but was only calculated when `Xth Visit` was set to `No` (0).  Adding a [check for Xth Visit](https://github.com/NewSpring/Rock/blob/optimize-attendance-analytics/RockWeb/Blocks/CheckIn/AttendanceAnalytics.ascx.cs#L1081) prevents the `No` condition data set from getting filtered out.
=> [WIP] Optimize attendance analytics

Rock/Workflow/Action/Communications/SendEmail.cs
When the SendEmail action's From attribute is set to a person, it will use the FullName as the display name rather than just the email address: "First Last <Email>"
=> SendEmail: Use FullName in From field

RockWeb/App_Code/Global.asax.cs
This fixes the `Liquid syntax error: Object '' is invalid because it is neither a built-in type nor implements ILiquidizable` exception that gets thrown when getting a null DB value in, for example, the DynamicData block.
=> Fix lava error when referencing a null database value

RockWeb/Themes/Rock/Styles/theme.less
Fixed so side nav no longer shows the text selection cursor on on non-clickable headers (and the font awesome icons in IE/Edge)
=> Fixed nav from showing text selection cursor

Rock/Workflow/Action/People/SetPersonAttribute.cs
- Updating the SetPersonAttribute workflow action to first encrypt an updateValue IF the field type is EncryptedTextFieldType.
=> Fix for #1599 - SetPersonAttribute action with EncryptedText.

RockWeb/Blocks/Finance/TransactionMatching.ascx, RockWeb/Blocks/Finance/TransactionMatching.ascx.cs
This allows a user to write down notes about a transaction as they're matching it, rather than having to match it and then track it down again to write a note.
=> - Added a 'Summary' textbox to the Transaction Matching block.

Rock/Model/Metric.cs
Part of #1644 mentioned editing the Group Picker to filter by GroupType.  This would apply when your MetricPartition is EntityType `Group`, EntityTypeQualifierColumn is `GroupTypeId`, and EntityTypeQualifier is a GroupTypeId.  
The automatically generated control that displays on [MetricValueDetail](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Reporting/MetricValueDetail.ascx#L38) should limit the list of Groups to the specified GroupType.
=> + Made Metric Partitions accessible via Lava (fixes #1644)

RockWeb/Styles/_components.less
Sets pickers to a max-width of 100%, and to display with static positioning, expanding the height of the parent container and preventing vertical overflow. Fixes #1661
=> Fix pickers on mobile (Fixes #1661)

Rock/Field/FieldType.cs, Rock/Field/IFieldType.cs, Rock/Field/Types/EncryptedTextFieldType.cs, Rock/Model/History.cs, Rock/Workflow/Action/People/SetPersonAttribute.cs, RockWeb/Blocks/Crm/PersonDetail/AttributeValues.ascx.cs
- Adding a setting in FieldType which allows for specifying that a field type is sensitive
- Checking the sensitive setting when logging attribute value in the person history to make sure we don't log values for sensitive field types.
=> Fixes #1593 - No longer log values of sensitive attributes in person history.

Rock/Data/Entity.cs
This allows a workflow trigger to determine which entity type is being updated or changed.  
One use case for this would be triggering an update to a third party system, where a workflow could fire only on certain entity types (without having to create a trigger for each specific type).
=> Make Entity TypeId and TypeName accessible in Lava

Rock/Attribute/AttributeFieldAttribute.cs, Rock/Field/Types/AttributeFieldType.cs, RockWeb/Blocks/Cms/PublicProfileEdit.ascx, RockWeb/Blocks/Cms/PublicProfileEdit.ascx.cs
This adds a block that can be placed on the front-end website, allowing a user to edit not only their information, but that of their family(s), including adding new family members. It also includes a button to send the user to a page where they could request additional changes. This block did require some changes to the AttributeFieldType and AttributeFieldAttribute classes to add in qualifier column/value functionality. This was because the 'Family Attributes' block setting was displaying attributes from check-in groups, and we wanted it to only display Family GroupType attributes.
=> + Adds a block to allow editing of user's account and family from the home page

RockWeb/Blocks/Event/EventItemOccurrenceLava.ascx.cs
Request from Slack to investigate why lava was only working with debug on. [Example here](http://rock.rocksolidchurchdemo.com/page/5392?EventOccurrenceId=5)
Ensure the the lava is hydrated.
I removed a check where the query was set .AsNoTracking() when debug was off.
The query will have a greater (but necessary!) overhead.
=> - Fix Lava Properties in EventItemOccurrenceLava  not hydrating with enable debug off

Rock/Workflow/Action/People/PersonAddressUpdate.cs
Couldn't use an Address attribute to update a person's address. Right now you have to copy it to a Location attribute to update it.
Allow using an Address Attribute to update a person's address.
Add the Address attribute as an allowed field type.
None
=> Allow using an Address Attribute in the Person Address Update Workflow Action

Rock/Field/Types/WorkflowActivityTypeFieldType.cs, Rock/Rock.csproj, Rock/Workflow/Action/WorkflowControl/ActivateActivityInOtherWorkflowOnMatch.cs, Rock/Workflow/Action/WorkflowControl/ActivateActivityinOtherWorkflow.cs
There's a new action in v6 that lets you activate a workflow using a workflow action. If based on logic you want to complete ~~kill~~ that workflow processing there's no way to do so. 
To provide the ability for a workflow to activate an activity in another workflow.
* Edit the workflow fieldtype to provide a drop down list of possible workflow types to select an activity type
* Add a workflow action that will take an activity type and a workflow id and then activate the activity in the given workflow.
The WorkflowActivityTypeFieldType was not designed to be used outside of the context of a workflow and so uses a HTTP.context method, there could be issues there (although these haven't been observed).
_Provide us some screenshots if your pull request either alters existing UI or provides …
=> + Add Activate Activity in Other Workflow workflow action

RockWeb/Styles/_components.less
Fixes issue #1736, the admin bar interfering with selecting or canceling on the picker menu.
Adds a 36px margin to the bottom of the picker menu, forcing the page to extend, which moves the admin bar out of the way.
Minimal, fixes rendering.
With fix:
Without fix:
=> Add bottom margin to .picker-menu

RockWeb/Styles/_components.less
Fixes issue #1710 
Adds classes to .datepicker-switch, prev, and next to use a pointer instead of the text selector cursor.
CSS change in `_components.less` file
None?
=> Change date picker next/prev and switch buttons to use pointer

Rock/Workflow/Action/WorkflowControl/ActivateWorkflow.cs
The ActivateWorkflow activity doesn't copy attributes to the new workflow properly - it's only copying the formatted value.
Fix how the attributes are copied.
This fixes the issue by changing it so that the raw value is copied instead of the formatted value.
=> Fix ActivateWorkflow action not copying attributes properly

Rock.Mailgun/Communication/Transport/MailgunSmtp.cs
Someone on slack brought up wanting to disable tracking links in Mailgun emails. Right now the email headers are hard-coded to enable tracking. 
Add an option to disable tracking on Mailgun emails.
This PR adds a "Track Clicks" option to the MailgunSmtp config which toggles the respective email headers.
None: the option is true by default, maintaining the previous behavior.
=> Add option to toggle tracking on mailgun emails

Rock/Workflow/Action/Groups/RemovePersonFromGroupAttribute.cs
The `Group Member Remove Person from Group Using Attribute` Workflow action removes the person from all of their groups instead of just the one specified.
Fix so that the person is only removed from the specified group.
Add a filter to the list of group members to delete so it only removes ones in the specified group
=> Fix Remove Person from Group Using Attribute Workflow Action removing all groups

Rock/Data/RockContext.cs
When a plugin contains entities that have corresponding configurations, these configurations are not loading into RockContext.  This change is mostly the work of Mike Peterson at CCV.
Completely load all IRockEntity entities and their configurations into the RockContext.
This uses reflection to find any configurations for entities that extend IRockEntity.
We have been running this for a month and 1/2 in production and for many months before that in our development environments.  It completely resolves issues when loading plugin entities into the Rock.
I have attached a sample entity to this which contains a configuration.  Without this change, an error is thrown when the plugin is loaded into the RockContext.
[KioskType.cs.txt](https://github.com/SparkDevNetwork/Rock/files/461814/KioskType …
=> Automatically load entity configurations from plugin assemblies.

Rock/Plugin/Migration.cs
This adds the ability to use standard DbMigration methods in a plugin migration.
The goal is to make plugin migration development "feel" more like standard entity framework.
I wrapped a handful of the standard migration methods into plugin migration. This allows for Rock to include the DbMigration methods for things like CreateTable, DropIndex etc. to expose them to Plugin Migrations.  More information about a previous PR which would have added an EF dependency to plugins is available here: https://github.com/SparkDevNetwork/Rock/pull/1529
This should not break any backwards compatibility.  It only adds new functionality.
There are no UI changes.
=> #1528 - Implement standard DbMigration methods in Plugin Migration Take 2

RockWeb/Blocks/WorkFlow/WorkflowEntry.ascx.cs
See https://github.com/SparkDevNetwork/Rock/issues/1748
This fixes the issue by always executing the code to set the icon and name on a workflow.
Split an If condition into two sections.
None that I know of.
See https://github.com/SparkDevNetwork/Rock/issues/1748
=> #1748 - Show the Workflow Type's Icon and Name on the block.

Rock/Rock.csproj, Rock/Workflow/Action/Utility/RunJob.cs
There are some jobs (Such as calculating group requirements or group sync) that someone may want to be able to trigger automatically via a workflow. This way they can run a job on demand without needing to manually run it themselves or waiting for the scheduled time.
Allow triggering jobs to run from inside a workflow.
This PR adds a new workflow action that will trigger a job to run.
I didn't explicitly check if a job is already running, but I'm pretty sure the scheduler handles that?
=> Add workflow action to start a Job

RockWeb/Blocks/Cms/ContentChannelItemPersonalListLava.ascx.cs, RockWeb/Blocks/Event/CalendarLava.ascx.cs, RockWeb/Blocks/Event/EventItemListLava.ascx.cs, RockWeb/Blocks/Event/EventItemOccurrenceLava.ascx.cs, RockWeb/Blocks/Event/EventItemOccurrenceListByAudienceLava.ascx.cs, RockWeb/Blocks/Event/EventItemOccurrenceListLava.ascx.cs, RockWeb/Blocks/Finance/ContributionStatementListLava.ascx.cs, RockWeb/Blocks/Groups/GroupFinder.ascx.cs
Some merge fields did not get updated from `LinkedPageUrl` to `LinkedPageRoute` in commit ad47233 - this fixes the ones I could find.
=> Fix LinkedPage merge fields missed in ad47233

RockWeb/Themes/Flat/Styles/theme.less
When securing a full rock site under https, the google fonts still pull using http, which causes a security warning, and in some browsers (namely IE), there is a modal window that pops up asking to exclude the content.  This PR address this mixed security while improving UX under https sites.
The goal is to fix mixed security for Flat theme sites.
This PR Changes the google font imports from making the request over http to use https instead.  
This should not affect backwards compatibility.
=> Updated google fonts to use https instead of http in the Flat theme.

RockWeb/Blocks/Administration/PageProperties.ascx
Misleading description in the "Show Breadcrumbs on Page" help text
Alternate clarifying phrase is more informative and clear to users unfamiliar with breadcrumb bars
Simple phrase change
Extremely unlikely
_Provide us some screenshots if your pull request either alters existing UI or provides new UI. Arrows and labels are helpful._
Previous text (navigation history) implies actual browsing history rather than page hierarchy. Hierarchy sounds too dense …
=> Update breadcrumb bar description

Rock/Model/Location.cs
A simpler version of PR #1740, that maintains the current, and ubiquitous `maps.google.com/maps?q=` link structure. Updates to include HTTPS, confirmed working with US and international addresses.
Use HTTPS without using Google's new, and undocumented link structure.
Added an "S" to the current links. This PR also removes the location label from the URL, but makes the title string optional to maintain backwards compatibility.
Minimal comparative to PR #1740, Google could depreciate this link format, but it's unlikely considering the number of sites and projects using this structure.
=> Update Google Map Link to HTTPS

Rock/Field/Types/SelectSingleFieldType.cs
The single select field control is missing a lava tip although it supports lava.
None, is just a minor UI change.
=> Added missing lava tip.

RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Null reference when we have a UserLogin attached to a Business.
Allow user's that are attached to Businesses to register.
Set the FirstName of the CurrentPerson to "" instead of leaving it Null.
This probably helps nobody since I doubt anyone else has UserLogin's attached to Businesses.
N/A
- Setting the FirstName to an empty string for situations where the FirstName might be null.
=> Business: RegistrationEntry Null Reference

Rock/Web/UI/Controls/Grid/Grid.cs
When exporting data to Excel or using the Communication tool from a filtered DynamicData block, it always used all the data instead of using the data with the filter applied.
This updates the PersonData and ExcelExport to used the applied RowFilter.
Use the DefaultView of the DataTable instead of just iterating through the Rows.
It's possible that exporting all the data is someone's desired behavior.  I think this is unlikely but it's hard to know these kinds of things.
=> #1791 - Updating the Excel export and PersonData methods to honor the RowFilter.

RockWeb/Blocks/Groups/GroupListPersonalizedLava.ascx.cs
We need to display the information for only certain ministries' small groups. By selecting a group ancestor we can now show a leader their high school groups, and not their in-home small group.
It will allow this block to become more targeted.
If the parent group is set, the block will recursively look up the IDs of all ancestors of that group. It then adds the where to the query. This may be slow if it is working through a huge number of groups, so I added caching of the IDs. The default cache length is 1 hour but it is configurable.
This should not affect backward compatibility as any block that does not have a parent group set will continue as normal. Selecting a group with a great number of ancestors may be slow.
=> Added option to select group to only show descendant groups in GroupListPersonalizedLava

RockWeb/Webhooks/Mailgun.ashx
Fixes an issue that prevented a bounced email from triggering the custom action on a SendEmailWithEvents activity by splitting the workflow action guid on comma if it exists.
Bounced emails should are now also marked as inactive.
=> Fixes Mailgun webhook bounced email event.

RockWeb/Blocks/Groups/GroupFinder.ascx.cs
When using a group finder block that does not have a group detail page set, clicking on a group in the grid view just reloads the page with no visible change.
Give users better visual feedback after selecting a group, given the context
Show the info window when group is clicked.
In the postback, when there is no group detail page set, a javascript function is called that opens the corresponding infowindow.
None I can see
This is not a perfect solution as it would probably be better to not fire the post back at all, but I was having trouble trying to dynamically set the OnRowSelected attribute for the grid. If there is a better way to implement this, feel free to change it.
=> Group finder: show info window if no detail page

RockWeb/Blocks/Crm/PersonSearch.ascx.cs
Person search was incredibly slow.  Even with a search that matched a single record, it took around 5 seconds for the search to execute before being redirected to the person's profile.  This PR updates the person search to first load a list of id's and then re-query for all the rest of their data as this significantly speeds up the person search block.
This is drastically faster (and a relatively small change)
This does a search first just to get the person id's that matches, then does a secondary search to load all their data.
None that I know of.  It seems to work fine and improve speed no matter the size of the result set.
=> Person Search Performance

Rock/Workflow/Action/Groups/PostAttendanceToGroup.cs
The Post Attendance to Group workflow action does not set the campus id for a given location. And the action will fail if the person who's attendance is being posted is not already in the group.
The description for Add To Group implies that attendance should be posted despite group membership. As does the add [log entry action](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Workflow/Action/Groups/PostAttendanceToGroup.cs#L191) on line 191 of the PostAttendanceToGroup.cs file, since it is a log entry rather than an error.
Allow attendance markings without being part of a group, or being added to a group (similar behavior to check-in kiosks). Also include the campus id in the attendance marking. 
This PR removes the return statement that stops attendance from being posted when a …
=> PostAttendanceToGroup Improvements

RockWeb/Blocks/Finance/ContributionStatementLava.ascx.cs
Our finance department wanted first to be able to use PublicName instead of Name on the Contribution Statement, but then seeing that PublicName is used in the Account Picker they decided to use Description. These were not available options in the Summary section.
To give churches options on which fields they want to show in the summary on the Contribution Statement
Added the properties to the class and populate them.
None
None
=> Added PublicName and Description to the AccountSummary on the Contribution Statement.

RockWeb/Blocks/Finance/BatchDetail.ascx.cs
When adding a new batch from the Batch List screen, the status was defaulting to Pending. The documentation states that Pending is intended for use with the check scanner to indicate that a batch is currently being imported into. 
To save the user an extra step of marking each manual batch Open when creating it.
I set the status when creating a new object in the Batch Detail page only; I considered adding it to the constructor so that all batch objects would be Open by default but I thought that might have unintended consequences elsewhere in the code, and the Batch List/Detail blocks are the primary way a Batch would be created.
None
None
=> Creating a new batch with the Batch Detail page will default the Status to Open.

Rock/Field/Types/CurrencyFieldType.cs, Rock/Web/UI/Controls/CurrencyBox.cs, Rock/Web/UI/Controls/NumberBox.cs
While working on adding Payment Detail entity attributes to the Transaction Detail edit screen (pull request coming soon), I noticed that attributes of the currency type were not being formatted or validated correctly. It was possible to enter alphabet characters into a currency attribute, which should only accept decimal numbers. 
To correct the format and validation of currency attribute controls.
CurrencyFieldType now inherits from DecimalFieldType and CurrencyBox inherits from NumberBox. CurrencyBox sets its NumberType to Currency when constructed (which allows values with commas to be accepted by the validator), and NumberBox uses its current NumberType for validation rather than always using Integer. Also fixed misc. comments and formatting.
None likely.
None.
=> Fixed formatting & validation of currency-typed entity attributes.

RockWeb/Assets/Images/person-no-photo-child-female.svg, RockWeb/Assets/Images/person-no-photo-child-male.svg
The SVG files for Children don't show in the Checkin Manager because they don't have a default width and height. This pull adds the same width and height used by the default male and female SVGs (Fixes #1786)
Add a default width and height to match the style found on the `person-no-photo` SVGs 
Matching code used on the working images `width="298.811px" height="298.708px"`
Nothing to mention. Going forward it should be noted that Rock doesn't like the responsive image default from Adobe Illustrator because Illustrator expects the parent container to have a width/height attribute. 
From `/checkinmanager`
Before:
After:
=> Use the same SVG width and height for children

RockWeb/Blocks/Finance/TransactionDetail.ascx, RockWeb/Blocks/Finance/TransactionDetail.ascx.cs, RockWeb/Blocks/Finance/TransactionMatching.ascx, RockWeb/Blocks/Finance/TransactionMatching.ascx.cs
We have the need to track transaction attributes that only apply for a given currency type. These are implemented by adding Financial Payment Detail attributes with qualifiers on CurrencyTypeValueId. In our case we have an optional attribute for Checks and a few required attributes for Stocks.
We need to be able to set these attributes on the Transaction Detail screen when the associated currency type is chosen. We also need to allow these values to be set on the Transaction Matching screen.
Added code to display and save edit controls for the Payment Detail Attributes.
None
Attributes for stock (Transaction Detail block):
Attributes for checks (Transaction Detail block):
Attributes for checks (Transaction Matching block):
=> Added Payment Detail entity attributes to the Transaction Detail and Transaction Matching blocks

RockWeb/Blocks/Finance/TransactionMatching.ascx.cs
We use Shelby Teller to scan checks and a custom plugin to import those checks into Rock. The amounts are already assigned in Teller and loaded correctly into the matching screen.  But when the user chooses to display a different set of accounts on that screen, even if the populated account(s) are included, the previously stored values are erased and must be retyped.
To reload any existing amounts into their proper account controls after changing which accounts should display. This should be done even if amounts are not pre-loaded because the user could have entered an amount already before noticing that one of the accounts they need is not displayed, and so they should not have to re-enter amounts after changing this display.
Load the values in the Save event for the Accounts Personal …
=> Reload Transaction amounts after changing displayed accounts on Transaction Matching screen.

RockWeb/Blocks/Finance/AccountDetail.ascx.cs
Account Entity Attributes could be edited on the AccountDetail block, but were not being Saved properly.
To Save all values on the AccountDetail block properly.
Moved the code to display and populate the attribute edit controls up to the OnLoad() function, outside of the logic that checks for a PostBack. If the attribute controls are not created on PostBack, then they do not exist to have their values saved.
None
None
Also cleaned up a little bit of messy conditional logic in ShowDetail(), no impact on functionality.
=> Account Entity Attributes will now save properly from the AccountDetail Block.

Rock.Rest/Controllers/GroupsController.Partial.cs, RockWeb/Blocks/Groups/GroupMap.ascx, RockWeb/Blocks/Groups/GroupMap.ascx.cs
At CCV, our Neighborhood Groups (small groups) are organized by Campus and Region, and there are sometimes 1000s of people inside those regions.  In CCVs case, when somebody clicks on the Map icon for a Neighborhood Group Region, they are typically just concerned about a specific campus.  
This pull request adds an "Show Campus Filter" option to GroupMap.  The option defaults to false, since it is probably a feature that most places won't use.  If it is enabled, a Campus Filter will show up which will limit which Families show up when the "ConnectionStatus" checkboxes are toggled. (If no campuses are selected, it won't filter by campus)
The block has a couple of modes where it doesn't show Connection Status checkboxes, so I made sure that the CampusFilter won't be showing in that case. …
=> Feature mp groupmap campusfilter

Rock/Workflow/Action/Groups/RemovePersonFromGroup.cs
The "Group Member Remove from Specified Group" Workflow Action ignores the specified group and instead removes group memberships from all groups.
Only remove group members from the specified group.
Add the group Id to the groupMembers filter.
=> Fix Group Member Remove Workflow Action removing all groups

Rock/Lava/RockFilters.cs, Rock/Model/Person.cs, Rock/Model/PersonService.Partial.cs, Rock/Rock.csproj, Rock/Workflow/Action/People/PersonGetHeadOfHousehold.cs, Rock/Workflow/Action/People/PersonGetHeadOfHouseold.cs
Have you filled out and sent your [Spark Contributor Agreement]
Yes
This workflow action will take a person, passed through an action attribute, find the person’s head of household (which they could be them), and set a person attribute with that person.
Added Spouse and HeadOfHousehold to RockFilter and will take Person as input.
This will help us to get the Person's head of the Household.
Yes
#Documentation
**Spouse  Filter**
{% assign spouse = CurrentPerson | Spouse %} 
<p>{{spouse .FullName}} </p>
**HeadOfHousehold  Filter**
{% assign headofHousehold= CurrentPerson | HeadofHousehold %} 
<p>{{headofHousehold.FullName}} </p>
=> Added Workflow action to get person's head of household 

Rock/PersonProfile/Badge/InDataView.cs
We wanted to add a badge to a person's profile if they are safe to work with children. We have an existing data view which we use extensively. Rather than recreating and managing parallel Lava any changes to the data view can appear on the badge as well.
This will allow churches to use data views to show badges. 
I created a badge type that displays lava enabled output if the person is in the data view.
There should be none, except for many complex badges at the same time.
=> Added badge type which displays if person is in dataview

RockWeb/Blocks/Finance/ContributionStatementLava.ascx.cs
On the ContributionStatementLava block, the pledge amount given number is incorrect - it showed ALL gifts to that fund, not just for the individual/giving group.
Fix ContributionStatementLava.ascx.cs so only pledges for current giving group are shown.
Alter the LINQ statement to only get transaction for the current giving group.
none
=> Bugfix in ContributionStatementLava Pledges

RockWeb/Blocks/Core/Attributes.ascx.cs
Yes
The Entity Attribute screen no longer displays Entity Type and Qualifiers.
Entity Type and Qualifier controls will display.
These controls were added to a panel that was marked visible = false, however the code that was supposed to display them was setting the visible property of the controls themselves rather than the panel. I changed the code to make the panel visible.
_What could this change potentially …
=> Fixed display of entity attribute qualifiers

Rock/Jobs/SendDataViewEmail.cs
Yes
This job allows administrators to send email to a Person DataView on a one-time or recurring basis.  The job depends on a Lava template that is managed in the Communications > System Emails section.  There is an optional data timeout (for large dataviews) to prevent the default Rock timeout from cancelling the job.
See above.
None, provides …
=> + Added a job to send emails to a dataview

Rock/Web/UI/Controls/AddressControl.cs
[x] _Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?_
Per issue #1827 when address 2 is shown; chrome and Safari force autocomplete to fill-in address 1 in both the address 1 and address 2 field. This adds autocomplete attributes from the HTML5 spec to the form controls.
Prevent bad data and failed address validations from event signups.
The autocomplete attribute.
None
None
N/A
=> Added autocomplete attributes to address control

Rock/Rock.csproj, Rock/Utility/ExcelHelper.cs, Rock/Utility/ExtensionMethods/ObjectExtensions.cs, Rock/Web/UI/Controls/Grid/Grid.cs
Yes
Initially, I found that exporting a Dynamic Data Block resulted in a spreadsheet that did not have any Date or Number formatting. I also found that a single formatting for Dates and Numbers did not always make sense, such as showing the hours and minutes on a BirthDate column, or showing some currency columns with decimal and others as text with a dollar sign. Finally, I found some other miscellaneous bugs such as extra rows/columns being added, and the column headers not being included in the frozen header section.
_What …
=> Multiple improvements to grid export files

RockWeb/Blocks/Finance/TransactionReport.ascx, RockWeb/Blocks/Finance/TransactionReport.ascx.cs
yes - just sent
Our accounting dept wanted the transaction code information to display in giving history grid
Make accounting happy, and benefit other churches as well who need the same information
Added a block setting that allows for transaction code column to not be shown (shown by default)
none
na
=> Added transaction code to giving history

Rock/Communication/Medium/Email.cs
Sending bulk email is stressful, lets make Rock not scare users after they've sent an email by making the error messages a little nicer.
Remove exclamation points from the notes displayed next to failed recipients.
Deleting the❗️💥 
None
Removes the exclamations from the communication history/status display seen here:
Email notes don't appear to be in the documentation yet.
=> Removed exclamation points from failed recipients

RockWeb/Blocks/Crm/PersonDetail/EditGroup.ascx.cs
Yes
Many adults in our database were not set to give with the family. I found that this was because adults added from the Edit Family screen are not set to give with the family the way they are if they are added as part of the initial creation of the family.
New adults will now be set to give with their family when created.
Fixed a bug that was comparing a Guid to a string and expecting them to match.
_What could …
=> Adding an adult on the Edit Family screen will correctly set the Giving Group

RockWeb/Blocks/Reporting/DynamicChart.ascx.cs
Yes
We're working on generating campus-specific dashboard pages that contain DynamicChart blocks, and wanted the ability to pass in campus Ids so that we could generate charts specific to that campus.
This change allows users to pass in custom parameters into the SQL used to generate DynamicCharts. Not only does this allow users to pass in page parameters, but it also allows them to pass in lava-based parameters such as DateTime values, etc.
We implemented this by copying the same functionality that the DynamicData block uses over to the DynamicChart block.
Depending on how you set up your parameters in the …
=> - Added the ability to pass parameters into the SQL used to generate the DynamicChart charts.

Rock/Reporting/DataFilter/GroupMembers/GroupMemberAttributesFilter.cs
Yes
Group member data views throw null exceptions when selecting the filter type of "Group Member Attributes" if there is a group member attribute that is a schedules filter type.
groupmemberattributesfilter.cs calls  EntityHelper.GetEntityFieldForAttribute( attributeCache ) which can return null. I added a null check before adding the entity field.
I looked into making schedules filterable, but that probably isn't a reasonable option. In the end a null check worked best.
None
Note:  The main changes are on lines 110-116. Visual Studio added in the normal Rock formatting so there are a few extra lines changed.
=> Added null check to keep group member dataviews from breaking

RockWeb/Blocks/Finance/ContributionStatementLava.ascx.cs
Yes
When printing a contribution statement, there are no headers repeated on every page for the contribution list.
To display headers at the top of each page.
Using the THEAD tag, each page will show the headers if the list of contributions is longer than one page. …
=> Table header on Contribution Statement will now print on every page

Rock/Lava/RockFilters.cs
Yes
Currently the ZebraPhoto Lava Filter is saving photos to the printer's E: (Flash Memory) location, which is typically used to store more static data and is not recommended for repetitive write operations.
This pull request will change the filter to store photos in the printer's DRAM instead, which is designed for repetitive functions like this.
As the photos are now being stored in R: instead of E:, any labels that use this filter will need to be updated to reflect this by changing their ^XG (Recall Graphic) references to the photo's new R: location (`^XGR:LOGO.PNG,1,1^FS`).
=> - Changed ZebraPhoto Lava Filter to use DRAM instead of Flash Memory when saving photo to printer memory.

RockWeb/Scripts/summernote/plugins/RockFileBrowser.js, RockWeb/Scripts/summernote/plugins/RockImageBrowser.js
Yep!
In some situations, the Rock File Picker would fail to paste the link when a File was selected.  We narrowed it down to cases when there was a Vimeo already in the HTML
This pull request will fix it so that a File and an Image can be picked even if there is a Vimeo already in it (or whatever)
Narrowed it down to a javascript 'Access Denied' that sometimes occurred when trying to JQuery something inside an …
=> Fix htmleditor rockpickers sometimes not working

Rock/Web/UI/RockPage.cs
Yes
I created a person report filter that would find people within a geofence. The google map would not load inside the picker. This is because the LocationPicker (and thus the GeoPicker) is created in an async postback. The loading of the googleMapsApiScript is registered with ClientScript which doesn't work well with async postbacks. I changed it to ScriptManager which works with async postbacks. 
http://stackoverflow.com/questions/7049041/differences-between-scriptmanager-and-clientscript-when-used-to-execute-js
I have tested the LocationPicker/GeoPicker to make sure it still works normally elsewhere.
=> Fixed issue where google maps would not work if LocationPicker created in async callback

RockWeb/Blocks/Groups/GroupDetail.ascx.cs
Yes
We copied some groups in the DB and didn't copy their schedules.  When we try to update or delete the groups we are getting errors now.  This resolves the issue.
This checks to verify that this is, indeed, the only group using a schedule.  This situation shouldn't ever happen using Rock but we have some customizations that copied groups without also copying their schedules and this fixes it.
Just run a quick query to make sure the schedule isn't used on any other groups.
None.  This should not break anything in existing Rock implementations.
No UI Changes.
N/A
=> Group Schedule Delete Issue

RockWeb/Themes/Flat/Assets/Lava/GroupDetail.lava, RockWeb/Themes/Flat/Assets/Lava/PodcastMessageDetail.lava, RockWeb/Themes/Rock/Assets/Lava/GroupDetail.lava, RockWeb/Themes/Stark/Assets/Lava/GroupDetail.lava, RockWeb/Themes/Stark/Assets/Lava/PodcastMessageDetail.lava
Removes `||` operator from all lava files and replaces with or
Bring lava in line with coding standards
Find and replace :)
N/A
N/A
N/A
=> Fixes #1912 - incorrect lava operators per @azturner

RockWeb/Blocks/Crm/PersonSearch.ascx.cs
Yes
PersonSearch would throw a SQL Exception if there were a large number of matches.  For example, if searching for a single letter "s", which returns 33000 matches on our database
Make it so that it doesn't throw the exception if there is a large number of matches, but still perform quickly
I borrowed an idea from SECC to cut-off using a static list of Ids if the list is over 10000 and use an IQueryable instead …
=> Feature mp person search fix

Rock/Reporting/DataFilter/Group/GroupTypeDataViewFilter.cs, Rock/Rock.csproj
Yes
There was now GroupType related DataView filter when you built a DataView for Groups.
This creates a new "Related Data Views" filter when building Groups Data Views that lets you select a Group Type dataview.
I more-or-less copied an existing related dataview filter and implemented it to work for this situation.
None.  Just new functionality.
_Provide us some screenshots if your pull request either alters existing UI or provides new UI. Arrows and labels are helpful._
_If your change effects the UI or needs to be documented in one of the existing [user guides](http://www.rockrms.com/Learn/Documentation), …
=> New Group -> GroupType DataView related filter

RockWeb/Blocks/Security/UserLoginList.ascx.cs
Yes.
When tabbing through the User Account screen, any selection of the authentication provider will trigger a postback to load the new provider's detail/attributes.  However, this destroys the current form's focus.
Restores the keyboard focus to the next field (Password) after postback.  If the provider doesn't support a password field (PIN auth), then nothing is focused.
Set focus to the password field after a …
=> Fix loss of keyboard focus when selecting/switching the auth provider

RockWeb/Blocks/Finance/TransactionDetail.ascx, RockWeb/Blocks/Finance/TransactionDetail.ascx.cs
Need to be able to set Financial Transaction Detail Attributes.
Add UI to the Modal for Financial Transaction Details.
Used existing code in the FinancialTransactionDetails block to add UI in Details Modal.
No foreseeable impact to other areas.
=> Add Financial Transaction Details Attribute UI to Modal

Rock/Reporting/DataFilter/Person/PostalCodeFilter.cs, Rock/Rock.csproj
Yes
We often need to filter our dataviews by zipcode. We can create a location filter, and then filter by that dataview, but this doesn't work so well in a dynamic report.
This will allow us to filter by zipcode.
I created a new postal code filter. It works with 5 digit, 9 digit, or alphanumeric postal codes.
None.
=> Added new person data filter for Postal Codes

Rock/Reporting/DataFilter/Person/CampusFilter.cs, Rock/Reporting/DataFilter/Person/CampusesFilter.cs, Rock/Reporting/DataSelect/Person/CampusSelect.cs
YES
We have a dynamic report that uses the CampusesFilter that is used quite a bit.  It started to get very slow, and even timing out.  I'm not sure why it "Just started happening", but there was no recent code changes that would have caused it.  I'm guessing that our database recently just got just a little bigger and that amplified the problem.
Fix it so that Campus Filters perform reasonably fast.
I first …
=> Improve performance of CampusFilter, CampusesFilter, and CampusSelect

RockWeb/Blocks/Reporting/DynamicChart.ascx.cs, RockWeb/Scripts/Rock/Controls/charts.js
Yes
DynamicChart in Line-mode does not allow for arbitrary X-axis values, they must be in DateTime format. This creates problems when trying to do weekly year-over-year charts. For example, weekly attendance over the past 3 years. Three lines: Current Year, Last Year, 2 Years Ago. X-axis is week numbers, 1-52 (actually 53 because of odd start weeks).
Provide support in the DynamicChart block to allow SQL queries to provide non-DateTime x-axis values.
_How …
=> Extended DynamicChart block to allow for arbitrary x-axis values

Rock/Reporting/DataFilter/Person/InRegistrationInstanceRegistrationTemplateFilter.cs, Rock/Rock.csproj, Rock/SystemGuid/EntityType.cs, Rock/Web/UI/Controls/Pickers/RegistrationTemplatePicker.cs
Yes
Our admins are wanting to run data views on whether a person has signed up for an event (registration instance), whether it be any or one of a particular template.
This pull request adds a 'In Registration Template(s) filter (add required background bits) that will filter people that have signed up for a Registration Instance of a specific Registration Template(s). If no templates are selected, it will filter people that have signed up for any registration instance. It also allows you to filter further by 'Date Registered'.
The RegistrationTemplatePicker is modeled after the SchedulePicker, as we needed …
=> Added "In Registration Template(s)" DataFilter

RockWeb/Themes/Flat/Assets/Lava/AdDetails.lava, RockWeb/Themes/Flat/Assets/Lava/GroupDetail.lava, RockWeb/Themes/Rock/Assets/Lava/GroupDetail.lava, RockWeb/Themes/Rock/Assets/Lava/OpportunitySearch.lava, RockWeb/Themes/Stark/Assets/Lava/AdDetails.lava, RockWeb/Themes/Stark/Assets/Lava/GroupDetail.lava, RockWeb/Themes/Stark/Assets/Lava/OpportunityDetail.lava, RockWeb/Themes/Stark/Assets/Lava/OpportunitySearch.lava
We have a few people that are visually impaired and wanted to improve their experience using Rock. While every screen reader works a little differently, adding the alt tag helps readers know to ignore a image, and is in use by twitter and facebook for their avatars. (See https://davidwalsh.name/accessibility-tip-empty-alt-attributes)
Add alt tags to theme lava files. Where relevant the title of what the image is used for some minimal SEO gain, for profile images use blank alt tags.
Adding alt text
None?
=> Add alt text to lava theme images to improve accessibility

Rock/Web/UI/Controls/NewFamily/MembersRow.cs
I happened to have made a nearly identical change only to find it when I merged pre-alpha-release. Checked with Mike Peterson and he agreed ShowMiddleName should use the ViewState just like ShowGradePicker and ShowGradeColumn do.
_Provide us some screenshots if your pull …
=> Have ShowMiddleName use the ViewState

Rock/Workflow/Action/CheckIn/FindRelationships.cs
Yes.
After the performance enhancements in #1956, @azturner sent me this change to FindRelationships.  I confirmed the original query execution plan had multiple GroupMember and Person lookups:
Average execution time was ~95ms using a cold cache or OPTION RECOMPILE.
This PR seeks to optimize the `Can Check-in` relationship lookups.
Instead of joining GroupMember and Person multiple times to find intersecting …
=> Performance improvement to FindRelationships workflow action

Rock/CheckIn/CheckInPerson.cs
Yes.
When using the new `PossibleSchedules` and `SelectedForSchedule` fields to implement check-in room balancing, I wasn't getting back the GroupTypes that had been selected.  
This was because CheckInPerson.GetGroupTypes is inconsistent with the pattern used in [CheckInGroup.GetLocations](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/CheckIn/CheckInGroup.cs#L143), [CheckInLocation.GetSchedules](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/CheckIn/CheckInLocation.cs#L201), etc.
_What will this pull …
=> Fix inconsistent check-in behavior that's not returning selected GroupTypes in CheckInPerson.cs

Rock/Model/BinaryFile.cs
Yes
While coding a process to create bulk contribution statement files from a Word merge template, I wanted to save the files on the disk rather than in the database. I found that though I was able to update the BinaryFileType of the file after the merge template CreateDocument() function saved it as the default binary file type, it did not save the file to the disk as expected.
To allow an update of the BinaryFileType to correctly save the file even if …
=> Fix bug when updating a BinaryFile to use a different storage provider

.github/ISSUE_TEMPLATE.md
Most people are struggling with the prerequisite checkbox system, and a general understanding of what GitHub issues is for, this also helps to move non-developers to appropriate support channels. Inspired heavily by the current iteration of [Atom's Issue Template](https://github.com/atom/atom/issues/new) 
- Remove noise from GitHub Issues
- Let developers know where to submit security bugs
- Direct new Rock users to appropriate support channels.
- Big commented out block of directions for security, and support.
- Fewer checkboxes, and including directions on how to use
None, but confirming that secretary …
=> Update Github Issue Template

Rock/Workflow/Action/WorkflowControl/Delay.cs
Fixing the misspelling of minutes in the help text. 
Fix it 😄 
N/A
N/A
N/A
=> Fix minutes spelling in Delay workflow action

RockWeb/App_Code/FileUploader.ashx.cs
Yes
When uploading a file with a | character in the filename (allowed from MacOS) the file uploader throws an error (see issue #2004)
This checks for a list of special characters that might exist from other operating systems that don't work with Windows.
Just check the filename and throw an error if we get something we don't like.
None.
Before:
After:
_If your change effects the UI or needs to be documented in one of the existing [user guides](http://www.rockrms.com/Learn/Documentation), please provide the brief write-up here:_
Shouldn't need to update anything.
=> Adding a illegal characters filter to FileUploader.

RockWeb/Blocks/Finance/AccountList.ascx, RockWeb/Blocks/Finance/AccountList.ascx.cs
Yes
The AccountDetail block had been updated to allow entry of FinancialAccount entity attributes, but choosing "Show In Grid" did not include these attributes in the AccountList block.
To display the selected entity attributes in the AccountList block.
Found similar code in another block and adapted it to find the attributes for the FinancialAccount entity and add them to the grid before adding the Delete column …
=> + Account attributes marked as "Show In Grid" will now appear in the AccountList block

RockWeb/Blocks/Crm/BulkUpdate.ascx.cs
When in the bulk update screen, selecting an input with checkboxes did not remove the disabled state.
This pull request removes the disabled states from checkboxes in the formGroup, if they exist.
I've added to the JS onClick event to check if the formGroup contains checkboxes.  If it does, it removes the disabled state.
https://drive.google.com/file/d/0Bw8uldfEkvqrN25oZ1owMzZqdVE/view
=> SYS-3184 Fixing checkboxes not updating from a disabled state

RockWeb/Blocks/Core/GroupContextSetter.ascx.cs
Yes.
When setting up dashboards to display data by user-selected contexts, the Group Context was pulling every group for a particular grouptype.  Since we have 16 campuses, the list of groups would get fairly large.
This PR seeks to limit the list of Groups by Campus when a Campus Context is set.
I've added a Block Attribute for Admins to enable the Campus filter, assuming a Campus Context is set.  If a Campus …
=> Add the option to restrict Group Context by Campus Context

RockWeb/Blocks/Groups/GroupDetailLava.ascx, RockWeb/Blocks/Groups/GroupDetailLava.ascx.cs
Enhanced the GroupDetailLava block of the Group Leader Toolbox to support:
- Block setting to hide the `Role` while editing or adding a Group Member.
- Block setting to hide the `Public` flag while editing the Group.
**Yes**
Our Small Group team wanted to prevent leaders from changing the role of an existing group member (for example, prevent the leader from making another member a leader without them having been vetted by our team).
Additionally they needed the Leader's to be able to mark their group as Public or Not Public …
=> Enhance GroupDetailLava block to provide new limiting options

Rock/Field/SelectFromListFieldType.cs
Yes
Testing some other logic, accidentally created an attribute with a null value. FormatValue broke when trying to load that attribute.
To avoid throwing an exception when an attribute's value is null
Return string.Empty when value is null.
_Provide us some screenshots if …
=> SelectFromListFieldType.FormatValue no longer breaks when value is null

Rock/Communication/Transport/Twilio.cs, Rock/Rock.csproj, Rock/packages.config
During a sunday service, we did a big push for a campaign backed by text to workflow. We had over 6000 text in which at peak, locked up our rock instance and dropped communication from over half. The waiting on twilio response caused our instance to spike with CPU and timeout on all requests
This makes the waiting for the POST to twilio async to not block the main thread.
After updating the twilio client, we are able to use the `CreateAsyncMessage`. This changes the `Send` method to be an async method.
There shouldn't be any
=> switch to newer async twilio client

Rock.Tests/Rock/Lava/RockFiltersTests.cs, Rock/Lava/RockFilters.cs
**Yes**
Sometimes there is a need to put a value in a very specific date type but often we get these values as strings. A few examples are building custom JSON when we want the value to be a true integer, or when passing values to other filters.
One example filter is DateAdd, which requires a true integer value. The following does not work:
```
{% assign interval = '1' %}
{% assign tomorrow = 'Now' | DateAdd:interval,'d' %}
```
Supply new Lava Filters to …
=> New Lava Filters to cast variables into explicit data types

RockWeb/Blocks/Security/AccountEntry.ascx.cs
Yes
We cannot allow children under 13 to create an account.
This will allow us to set a minimum age for creating a new account.
I used the existing birthday field to see if the person is old enough to create an account. There is a new block attribute to set the minimum age in years. If the person does not meet the required age, a warning is shown.
The default minimum age is 0 so no one should be affected.
=> Added a minimum age option to new accounts

RockWeb/Blocks/Connection/ConnectionOpportunityDetail.ascx.cs
Yes
Capitalization error mentioned by Chris Rea on Slack where all changes to lowercase on save for Connector Groups.
Uppercase "All"
N/A
N/A
None
Before Provided by Chris Rea:
N/A
=> Fixed Connection Opportunity "all" capitalization for consistency

Rock/Lava/Blocks/RockLavaBlockBase.cs, Rock/Utility/ExtensionMethods/LavaExtensions.cs, RockWeb/Blocks/Cms/ContentChannelView.ascx.cs
**Yes**
Lava variable space should be kept as clean and lean as possible in order to not cause confusion to the user when working with Lava.
Declutter the Lava variable space a bit.
Move some of the Lava commands tracking around so it doesn't get in the user's way anymore. …
=> Declutter the Lava variable space

Rock/Communication/SMTPComponent.cs, Rock/Web/UI/Controls/Communication/Email.cs, RockWeb/Blocks/Communication/CommunicationEntry.ascx.cs, RockWeb/Blocks/Communication/SystemEmailDetail.ascx, RockWeb/Blocks/Communication/SystemEmailDetail.ascx.cs
We have the need to cc emails to addresses dynamically (Person attributes, Transaction attributes etc).  We also have times we would like to set the cc/bcc field via the communication entry form.
Set Cc and Bcc fields with Lava.
This moves the CC/Bcc fields down into the recipient section so we can merge lava fields for each recipient iteration.  It also add's the ability to use lava in all the fields.  Lastly it adds CC and Bcc fields to the Email Communication control and allows for setting it to show or not show based on a CommunicationEntry block attribute.
This is the communication entry page when the CC/Bcc functionality is enabled:
=> Email Functionality

Rock/Rock.csproj, Rock/Workflow/Action/People/PersonInDataView.cs
Yes
We have a dataview which is our standard for who can work with children. When someone makes a requests in a connection, we would like to send an email to everyone who not completed the process so they can begin the application to serve. We could use a SQL action, but we would like to have one source for truth. 
This action would allow people to use a dataview to set a boolean attribute in their workflow based on if a person is in that dataview. 
I created a workflow action that checks to see if the person is in a particular dataview and sets a workflow attribute "True" or "False" accordingly. That attribute can then be used as a filter to start or end actions and activities. 
None
Person: The person who will be tested against the dataview.
DataView: The dataview to test the person …
=> Workflow action to test if person is in a dataview

RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Yes
Registration Text Attributes were being populated with the current person's nickname ( see [Jim Michael's issue](https://github.com/SparkDevNetwork/Rock/issues/2040) for more details).
The issue is that even when RegistrationTemplateFormFields are not tied to a person field, they are still saved with a PersonFieldType enum value corresponding to FirstName, '0' (see below), so when the RegistrationEntry block crawls for fields of type FirstName or …
=> - Registration Entry no longer inserts nicknames into Registration Text Attribute form fields ( Fixes #2040).

Rock.Rest/ApiControllerBase.cs
Yes
We email a link to our protection application to applicants, which logs them in to fill out a workflow that's assigned to them, and most of these users will not have a username (the application uses a custom form and controller, if that matters). When saving their changes to the history, no user was being tagged as the creator.
When the principal.Identity.Name is "rckipid=[EncryptedKeyHere]" it will be able to return the associated user.
_How have you …
=> Added support for getting user by EncryptedKey in GetPerson()

RockWeb/Styles/rock-components/pickers.less
Yes
Fixes #1316
Prevent overflow to improve accessibility on mobile devices
max-width: 100%;
N/A
N/A
N/A
N/A
=> Prevented merge picker from overflowing on SMS Communication (Fixes #1316)

Rock/Web/UI/Controls/Checkin Configuration Controls/CheckinAreaRow.cs, Rock/Web/UI/Controls/Checkin Configuration Controls/CheckinGroup.cs, Rock/Web/UI/Controls/Checkin Configuration Controls/CheckinGroupRow.cs, RockWeb/Blocks/CheckIn/AttendanceAnalytics.ascx, RockWeb/Blocks/CheckIn/AttendanceAnalytics.ascx.cs, RockWeb/Blocks/CheckIn/CheckinGroupList.ascx.cs, RockWeb/Blocks/CheckIn/CheckinScheduleBuilder.ascx.cs, RockWeb/Blocks/CheckIn/Config/CheckinAreas.ascx, RockWeb/Blocks/CheckIn/Config/CheckinAreas.ascx.cs, RockWeb/Scripts/Rock/dialogs.js
Occasionally we need to retire check-in groups and to reduce clutter we would like to inactivate them and have them not clutter up the check-in interface. If we choose to delete a group all the attendance records are essentially lost.
My goal is to make is easy to inactivate and reactivate check-in groups.
I modified the configuration controls and blocks to check to see if the group has attendance records before deleting. If the group does not have attendance records it is simply deleted. However, if it does have attendance records it inactivates the group instead of deleting it outright. Inactive groups are hidden by default, but can be shown by selecting a check box. Once a group has been inactivated, it can be deleted or reactivated.
Additionally I added an option to attendance …
=> Changed UI to support inactivating check-in groups

Rock.Rest/Controllers/GroupsController.Partial.cs, Rock/Model/GroupService.Partial.cs, RockWeb/Blocks/Groups/GroupTreeView.ascx, RockWeb/Blocks/Groups/GroupTreeView.ascx.cs
_Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement.pdf) to secretary [at] sparkdevnetwork.org?_ 
No
A church wanted the ability to filter the group tree down based on campus. As well as the ability to search from the group tree.
A campus picker and search box will be added to the settings panel to give the user the ability to filter based on campus or run a search from the tree view.
I added the new campus picker (with a toggle to include "no campus set" entries) to the group tree settings panel, with the corresponding api and GroupService updates to support this new data to filter based off of. A group search box input-group was also added to the settings panel to be able to search for a specific …
=> Add Campus filter and search box to Group Tree View settings panel

Rock/Model/GroupService.Partial.cs, Rock/Model/LocationService.Partial.cs
Yes
When we have an event registration that asks for a person's address, occasionally if they entered the same address we already have on file for them, Rock would move the existing address record to Previous and create a new, identical Home record for them. I found that this was due to the fact that Rock assumes there will only be one Location record in the database for each address, but due to multiple data imports, many addresses had been duplicated in the Location table. When Rock tries to find the existing Location record, …
=> + Event registrations will no longer occasionally create a duplicate address on a family. (Fixes #1680)

Rock.Tests/Rock.Tests.csproj, Rock.Tests/Rock/Lava/RockFiltersTests.cs, Rock.Tests/packages.config
☑️
Fix unit tests that were dependent on a mix of hard-coded event times but would always compare against RockDateTime.Today.
Fix the dang thing to always use RockDateTime.Today.  Also I never want to see an iCal event ever again.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTes …
=> - Fixed date comparisons in unit tests making Appveyor fail every single PR

RockWeb/Blocks/Event/RegistrationEntry.ascx, RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Yes
We use the term household to describe everyone who lives in the same address.  "Family" and "Immediate Family" are too specific to relationship rather than living arrangement.  We also decided to just force everyone to update their record's email address if they change it during registration.
Adding block attributes for:
- Specifying the term to use for family ("immediate family" is the default but we like "household" better).  This is used on the "Registrant is in the same household as Registrar" area.
- Force updating email addresses.
Just some block attributes and some changes in the block.
None.  The …
=> Adding some options for handling emails on RegistrationEntry

Rock.Tests/Rock.Tests.csproj, Rock.Tests/Rock/Utility/ExtensionMethods/StringExtensionsTests.cs, Rock/Utility/ExtensionMethods/StringExtensions.cs
☑️
Fixes #1747.
Fixes the issue and adds unit tests to make sure it doesn't break again.
This removes multiple non-decimal characters at the front of a string.  If non-decimal characters are in the middle of a string, it's no longer valid. …
=> - Fix AsDoubleOrNull allowing strings that don't represent numbers

Rock/Rock.csproj, Rock/Web/UI/CompressedHiddenFieldPageStatePersister.cs, Rock/Web/UI/RockPage.cs
Yes
Extremely slow postback of pages due to large ViewState size.
Apply GZIP compression to the ViewState.
A new subclass of PageStatePersister has been added to the Rock.dll and RockPage class has been updated to override the property getter that retrieves it.
Compression of ViewState using GZIP algorithm is performed if the ViewState is greater than 100KB. The achieved compression ratio is between 15:1 and 20:1. …
=> Add support for ViewState compression with ratio of about 15:1.

Rock.Tests/Rock/Lava/RockFiltersTests.cs
☑️
Skips iCal tests until I can look at the timestamp portion.  This may be a timezone issue where Appveyor is running the tests?
=> - Skip ical tests, timestamps aren't being added

RockWeb/Blocks/CheckIn/AttendanceAnalytics.ascx.cs, RockWeb/Blocks/Finance/GivingAnalytics.ascx.cs
Yes
Unnecessary port included in link from giving analytics and attendance analytics. 
Remove the port
Dropping the port from the copy link
N/A
Links created during development will need to append the port to link URLs.
N/A
N/A
=> - Removed port from analytics link (Fixes #2068)

Rock/Attribute/Helper.cs
Yes
We have about 200 person attributes. Calling SaveAttributeValues() takes a few seconds to run because it loops through all the attributes and loads their values one at a time, then saves each modified attribute one at a time.
To optimize the process of saving all attributes.
Instead of calling SaveAttributeValue() for each attribute, instead load all the entity's attributes all at once, update all that need …
=> SaveAttributeValues() now loads and saves once

RockWeb/Blocks/Groups/GroupMemberDetail.ascx, RockWeb/Blocks/Groups/GroupMemberDetail.ascx.cs
**Yes**
Issue #1996 - During postback the help text for the 'Notified' checkbox vanishes.
Ensure the Help text does not vanish.
Move the Help text from C# code into the .ascx file.
For some reason the HelpBlock control does not save/restore the Text value on postback. I'm not sure if this is a failure of the HelpBlock control or the controls that use it. Therefore if C# code does something like `cbIsNotified.Help = …
=> Fix 'Notified' text to not vanish on Group Member Detail block

RockWeb/Blocks/Groups/GroupFinder.ascx.cs
Yes
When the Group Finder was configured to display the Map and Sort by Distance but not Show Distance, no groups were displayed
Display the groups and ignore the Sort By Distance setting when Show Distance is false.
Added a check for the Show Distance property where the groups are limited by distance, since without that property set to true, no distances have been calculated.
_If your code is a new method or …
=> Fixed a bug that caused groups not to show up if sorting by distance while Map is enabled and Show Distance is disabled (Fixes #2007)

RockWeb/Blocks/Cms/PublicProfileEdit.ascx.cs
Yes
From the issue, The person's ConnectionStatusValueId was being used for their RecordStatusValueId.
Fixes it to properly use the RecordStatusValueId.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request …
=> Fix Public Profile Edit saving wrong Record Status (Fixes #2096)

Rock/Reporting/DataSelect/Group/MemberListSelect.cs
Yes.
When exporting a group report with group members listed in it. It shows the class name instead of the members' names.
I added a ToString override to the MemberInfo class to print the same in an export as it does in the grid.
**Before**
**After**
=> Added a ToString override to fix export problems

RockWeb/Blocks/WorkFlow/WorkflowDetail.ascx.cs, RockWeb/Blocks/WorkFlow/WorkflowList.ascx.cs
**Yes**
Fixes #2098. WorkflowDetail and WorkflowList blocks did not honor the ViewList security setting of the respective Workflow Type being viewed. Specific use case is the Background Check workflow. Users should be able to run it, but not necessarily see the internal data (such as SSN, Result PDF, etc.).
Update blocks to honor that security. This allows admins to give users permission to "View" (i.e. run) a workflow but not view the details of attribute …
=> Updated WorkflowDetail and WorkflowList blocks to honor the ViewList security

RockWeb/Blocks/Reporting/MetricValueList.ascx.cs
**Yes**
When viewing the list of values in a Metric, the Add button vanishes after a Postback event occurs. Fixes #2119.
Set the property enabled/disabled state of the button on every page load rather than just initial non-postback page load.
Move the code for enabling/disabling the Add button into it's own function that is called on each page load.
_If your code is a new method or function (that doesn't need a …
=> Fix Add button not showing in MetricValueList block.

Rock/Web/UI/Controls/NumberBox.cs
**Yes**
Invalid spelling.
Fix spelling of "amount".
Located my text input cursor at the proper location of the file and pressed the "n" key once.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes …
=> Fixed mispelled 'amount' in NumberBox validation message.

Rock/Model/Person.cs
Yes
Business photos shown on hover in known relationships do not load because they mistakenly include a `/` a the beginning of the URL.
Remove the slash
NA
N/A
N/A
=> Fixed business photo URL reference.

RockWeb/Blocks/WorkFlow/WorkflowTypeDetail.ascx.cs
**Yup**
Fix issue #1353.
Errors occur due to a for loop iterating over direct-to-database enumerator which causes issues with Entity Framework when doing SaveChanges() inside the for loop. Fix by converting enumerator to a List first.
Rolled the Magic Programmer's Dice&trade; to determine which solution to use for this problem. It came up with putting `ToList()` at the end of the enumerator chain used at the start …
=> Fixed WorkflowTypeDetail when editing a workflow with a large number of attribute.

Rock/Web/UI/Controls/RockCheckBoxList.cs
Yes
In a workflow that has multiple forms, where a later form has a required multi-select, the validation was firing the first time you see the page and styling the field with has-error immediately because it was received via a postback.  Refreshing the page would remove that styling because a refresh is not a postback. 
The has-error styling should only be used after attempting to move forward from the screen in question.
_How have you implemented your …
=> Fixed initial validation of check box list

RockWeb/Styles/rock-components/tags.less
YES! 
We have tagged some folks in as Missional Community Leaders and others as Missional Community Coaches. When you look at the persons profile the tag names get cut off and you can't tell the difference.
The goal is to make it so that you can see the full tag name on mouseover.
The text span width is limited 120px. When mousing over the tag it expands the max-width to 1000px. This allows for a smooth transition that isn't possible by just by removing the max-width. 
Tested in FF, Chrome, IE, and Chrome mobile.
It should just change the styling of the tags.
=> Changed tag styles to accomidate longer tags

Rock/Attribute/Helper.cs, RockWeb/Blocks/Groups/GroupMemberDetail.ascx.cs
Yes
The attribute fields on the group member detail block appear in sort of a random order. Changing the order of the attributes makes no difference.
To be able to order the group member attribute fields in the group member edit block. 
I removed the suppressOrdering flag and then added and ordering by EntityTypeQualifierValue before ordering by Order.
I tested by looking at the references of GetAttributeCategories(...) and making sure that the ordering continued to work as intended.
There shouldn't be any changes in ordering anywhere else.
=> Made group member attributes appear in a predictable order

Rock/Web/UI/Controls/NoteControl.cs
User should be able to delete notes having edit rights.
Yes
Fix issue #2123 
User cann't delete note even with Edit rights as the delete function only works when the note type is "User Selctable".
Removed the "User Selectable" note type check from the delete function.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request …
=> Fixed delete note button.

Rock/Web/UI/Controls/NewFamily/Members.cs, Rock/Web/UI/Controls/NewFamily/MembersRow.cs
Yes
The rightmost column of the new family screen is very wide considering it only holds an X button. This is due to the Add Person button being stored in this same column.
Make better use of the screen real estate.
Have the Add Person row span all the columns and align the button to the right. Also aligned the delete button to the right.
_If your code is a new method or function (that doesn't need a mock database …
=> - Small improvement to the new family member input display.

RockWeb/Blocks/Security/Login.ascx.cs
Yes
We wanted to be able to modify the text displayed when there was no account found.  This is especially useful because we use Active Directory for our staff users and if they are having trouble logging in, we want to direct them to call our Help Desk.
This pull request provides functionality to be able to customize the "No Account Text"
I added a block attribute which allows for editing/updating the no account …
=> Adding a new attribute allowing the No Account error text to be edited.

Rock/Model/PersonService.Partial.cs, RockWeb/Blocks/Crm/PersonDetail/EditGroup.ascx.cs
Yes
Investigating the creation of Person records, we would often find records that had no information in the History screen about when they were created, by whom, or what their values were at creation. We found that this was happening when people were added from the Edit Family screen.
To create History records when a person is added from the Edit Family screen.
The ID used to save the history was the GroupMember …
=> + History will be properly created when adding a new person from the Edit Family screen. (Fixes #1726)

Rock/Workflow/Action/Communications/SendEmail.cs
Yes
Workflow action to send an email to a group filter by role
Updated the SendEmail workflow action so that it can also use an attribute that has a field type of "Rock.Field.Types.GroupRoleFieldType" for the "Send To Email Address".
=> Workflow action to send an email to a group filter by role

Rock/Reporting/DataFilter/Person/InLocationGeofenceFilter.cs, Rock/Reporting/DataFilter/Person/PostalCodeFilter.cs
YES!
Earlier I created two data views for filtering people by geofence and one by postal code. We use these often, but they pick up all location types. I would like be able to filter only by home address or past address etc...
By adding in option to select location type, we can search by only certain location types.
I added a drop down option with the group location types. If one is selected the filter only applies to that location type. If none is selected it applies to all.
I tested all options and everything seems good to go. I also tested against existing dataviews we are using.
I wrote the enhancement in …
=> Added location type options to Postal Code and Geofence filters

RockWeb/Themes/Flat/Layouts/Dialog.aspx, RockWeb/Themes/Stark/Layouts/Dialog.aspx
**Yes**
When using sites based on the Stark or Flat themes, dialog popup windows (such as system information) do not resize properly when switching nav pills.
The same thing I do in every commit. Try to take over the world!
Changed the javascript on the page to use the "new" resize detector previously implemented in a1344cb7107caea0a4669d0768cd9779332552fb two years ago. It was applied to the Rock theme but not the …
=> Fix modal popups not resizing properly on Stark or Flat themes

RockWeb/Blocks/Connection/ConnectionRequestDetail.ascx, RockWeb/Blocks/Connection/ConnectionRequestDetail.ascx.cs
Yes
We had a request from ministries to show person detail badges on the connection request detail block.  This PR adds the ability to show person badges on the connection request detail.
I had to change the ConnectionRequestDetail block to be a PersonBlock in order to place badges on it.  Then loaded the person from the connection request.
One of the changes I had to make was to remove the using around RockContext because the badge needed a person entity that was still attached to an active context just in case attributes and defined values and such needed to be loaded to display the Lava.
The connection …
=> Person Badges on Connection Request Detail.

RockWeb/Blocks/CheckIn/Config/EditLabel.ascx.cs, RockWeb/Blocks/CheckIn/Success.ascx.cs
**Yes**
Lack of ability to have multiple printers on one IP address (e.g. a single Airport Express with multiple USB printers plugged in).
Add support for printer devices to be defined with 0.0.0.0:9100 syntax. e.g. 10.0.0.42:9102.
This will have a "side effect" of allowing remote server based printing without a VPN with the proper router configuration. You can setup 5 printers in Rock to print to your public IP address, each on a different port (say 9100 …
=> Support 0.0.0.0:9100 syntax in printer IP addresses

Rock.SignNow/SignNow.cs
**Yes**
When setting up teams for SignNow so that other users can upload documents rather than IT having to upload the documents manually or give out the credentials, we noticed that Rock does not recognize any templates in the Team folders.
Templates in the team folders are now available in the `Template` drop down when setting up a new document template. Team documents are prefixed with the team name and a greater than character, such as `IT > Test …
=> Make Team Templates available to Rock in SignNow interface

Rock.SignNow/SignNow.cs
Yes
When a Document name contains an illegal character (such as a "|"), the following error is thrown:
```  
Illegal characters in path.
at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
at System.IO.Path.Combine(String path1, String path2)
at Rock.SignNow.SignNow.GetDocument(SignatureDocument document, String folderPath, List`1& errors) in C:\DEV\WebApps\Jenkins\workspace\Rock\Rock.SignNow\SignNow.cs:line 555
at Rock.Model.SignatureDocumentTemplateService.UpdateDocumentStatus(SignatureDocument signatureDocument, String tempFolderPath, List`1& errorMessages) in …
```
=> Adding a quick check to make the SignNow document filname valid.

RockWeb/Themes/Flat/Assets/Lava/GroupDetail.lava, RockWeb/Themes/Rock/Assets/Lava/GroupDetail.lava, RockWeb/Themes/Stark/Assets/Lava/GroupDetail.lava
Yes
The group detail view lists the "Pending Members" header and adds a new `<div class="well">` for every two pending members.
Move the well and header to show once for all pending members. 
Modified all GroupDetail.lava templates
N/A
None
Proposed Fix (Sensitive info removed)
N/A
=> Fix GroupDetail to not show header multiple times

RockWeb/Blocks/Security/AccountEntry.ascx.cs
YES!
Long story: We had a summer program registration that could take payments in installments. A mom used her husbands account to register and used her name and email as the registrar information. This tied the registration to her profile and meant she needed to have a log-in to make payments. She couldn't create a username because she had a PIN attached to her profile.
People who have a username attached to their profile should be able to make an account in the account entry block if they don't have an database username already.
Check to see if they have a database username instead of just any username. …
=> PIN numbers no long keep people from creating accounts

RockWeb/Blocks/Crm/BulkUpdate.ascx.cs
Yes
Bulk Update Block was not handling updates to deceased people
Included Deceased people while getting peoples from the PersonService.
=> Fixes #2108 Handled Deceased people in Bulk Update

RockWeb/Blocks/CheckIn/Search.ascx
Yes
Issue #2222 - Checkin does not autofocus when searching by name
Allow search by name to auto focus.
Adds a `search-input` class for both the search by name and phone and uses that class to focus.
N/A
If non-standard themes have implemented a `.search-input` class there could be some styling issues.
N/A
N/A
=> Fix for checkin form focus (Fixes #2222)

RockWeb/Blocks/Groups/GroupList.ascx, RockWeb/Blocks/Groups/GroupList.ascx.cs
Yes
https://github.com/SparkDevNetwork/Rock/issues/755
Adding Group directly when Context is person
When GroupList block is used on person detail page with a person context ( e.g. Security Roles), a new group could easily be added to the list using the + icon (Add) directly from this block instead of having to navigate to a different page to add person to group.
=> Add member to group when Context is person

Rock/Web/UI/Controls/Grid/SelectField.cs
Yes
Grid on postback use to reset the control state of Select Field.
Select Field cb_DataBinding function use to override the selected state of Select Field. 
As cb_DataBinding was totally dependent on DataSelectedField.
=> Fixed keeping selected row as selected after the postback

RockWeb/Blocks/Finance/PledgeList.ascx.cs
Yes
Date Range Filter was not working as expected in Pledge List block.
Same datetime variables which is value type  were used to filter both date range and modified date range.
=> Fixes Date Range Filter in Pledge List

Rock/MergeTemplates/WordDocumentMergeTemplateType.cs
**Yes**
We have word document merge templates that contain an 8.5x11" letter as page 1 and then a number 10 envelope as page 2. When trying to use this template, only the final page in the output is formatted as an envelope, the rest end up formatted as 8.5x11" letter size.
The same thing I do with every commit. Try and take over the wo... err wait. Sorry bad dream. The goal is to add support for multi-layout word template documents.
_How have you …
=> Add support for multiple page layouts to word merge templates

RockWeb/Blocks/Fundraising/FundraisingParticipant.ascx.cs
**Yes**
If a contributor to a fundraising trip participant has no home address then an exception is thrown because the address is not checked for null before being referenced.
Add null checking.
Treat a null home address like an anonymous gift (i.e. show an empty string instead of the address).
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit …
=> Fixed FundraisingParticipant block to not throw exception when home address missing

RockWeb/Blocks/CheckIn/CheckinGroupList.ascx.cs
**Yes**
Depending on how your system is configured (like ours) the CheckinGroupList block would sometimes show empty. This seems to have been from a refactor some time ago where the output of one recursive call was accidently ignored.
Magic
Append the results of the recursive call to the local content buffer so it actually gets included. @mikejed tested this fix for me on his currently working system and there was …
=> Fix Check-in Detail page sometimes not showing groups

RockWeb/Blocks/Communication/EmailPreferenceEntry.ascx.cs, RockWeb/Blocks/Security/Login.ascx.cs
Yes
Issue #1711 
Fix all non-migration based uses of "thank-you" and replace with "thank you".
Find and Replace.
N/A
N/A
N/A
N/A
=> Fix thank you to be unhyphenated (Partial Fix #1711)

Rock/Jobs/RockCleanup.cs
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST test your code before submitting a pull request._
_What could this …
=> Add functionality to the Rock Cleanup job to remove orphaned attributes from deleted entities

Rock/CheckIn/CheckinType.cs, Rock/Workflow/Action/CheckIn/FindFamilies.cs, Rock/Workflow/Action/CheckIn/FindFamilyMembers.cs, Rock/Workflow/Action/CheckIn/FindRelationships.cs
**Yes**
Da spell'n of'n da property called `PreventInactivePeopele` is being wrong'n.
Fix'n da spell'n sozen people no sounda like meezen.
Add new property that pulls the same data but uses the correct spelling. Since this was a public property I have added an Obsolete tag to the original property.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be …
=> Fix mispelling in CheckInType - PreventInactivePeopele

RockWeb/Blocks/Utility/IdleRedirect.ascx.cs
**Yes**
Similar issue to the check-in on the welcome page getting stuck at 0. The idle redirect timer didn't get destroyed on a partial postback which caused it to fire even if there was activity.
Make the Idle Redirect block true to it's documentation.
Destroyed timer in javascript during a partial postback so that it does not fire.
_If your code is a new method or function (that doesn't need a mock database or …
=> Fix IdleRedirect block triggering too soon after a partial postback

RockWeb/Blocks/Core/DeviceDetail.ascx, RockWeb/Blocks/Core/DeviceDetail.ascx.cs, RockWeb/Blocks/Core/DeviceList.ascx.cs
**Yes**
Could not add attributes to devices unless I went through SQL which is not ideal.
Allow administrators to have a safe and comfortable user interface that allows them to view and edit device attributes. Our goal should always be to make administrators feel like they are empowered on their own installation of Rock. Whenever possible we should do so in a way that makes them feel safe in providing powerful features to their users. If we fail at this …
=> Added support for editing Device attributes.

RockWeb/Blocks/Utility/EntityAttributeValues.ascx, RockWeb/Blocks/Utility/EntityAttributeValues.ascx.cs
**Yes**
"Have you ever wished you could edit attribute values for any entity in the system? Well now you can! No modifications to your database are needed with this handy universal Entity Attribute Values block. Simply install this update and you too can edit attribute values on everything you could imagine - and more! Act now and we'll even throw in the ability to edit attribute values on attribute values!"
Provide a way for tinkerers and developers to …
=> Feature: Independent block for viewing and editing Entity Attribute Values

RockWeb/Themes/DashboardStark/Styles/theme.less
#1584 Mentions DashboardStark overflowing the page bounds. While this no longer appears to be an issue, it's impossible to edit the blocks/zone in the footer because it's affixed to the bottom of the page. This adds padding to the footer when the block/zone edit class is applied, which pushes the admin toolbar out of the way.
Make footer editable
Padding to the footer, applied only when editing.
N/A
When editing the page, extra padding on other page elements that are using the footer element will be added. This is unlikely due to the semantic nature of the footer tag.
N/A
=> Fixed admin bar to allow editing of footer in DashboardStark #1584

RockWeb/Themes/Flat/Assets/Lava/CalendarItem.lava, RockWeb/Themes/Flat/Assets/Lava/FundraisingOpportunitySidebar.lava, RockWeb/Themes/Rock/Assets/Lava/CalendarItem.lava, RockWeb/Themes/Rock/Assets/Lava/FundraisingOpportunitySidebar.lava, RockWeb/Themes/Stark/Assets/Lava/CalendarItem.lava, RockWeb/Themes/Stark/Assets/Lava/FundraisingOpportunitySidebar.lava
#2249 + Fix for a nearly identical call in fundraising opportunities lava.
Change all if statements to use the `ContactPersonAliasId`, which is more efficient than running a trim statement on a `FullName` which would always exist if there's a contact person alias. 
Lava
N/A
N/A
N/A
=> Fixed fundraising and event lava to not use embedded filters in if statements

Rock/Web/Cache/GlobalAttributesCache.cs
https://github.com/SparkDevNetwork/Rock/issues/2079
It will prevent grades appearing incorrectly (+- a year) depending on the viewer's client culture.
Ideally the date and month would've been parsed using a Rock wide culture setting but it doesn't appear we track that anywhere and since server culture in some hosting environments can't be changed I decided to stick with the existing Lava Tip for the attribute which specifies `mm/dd`. 
I decided to append the current year to date time as there were some instances where trying to do `ParseExact` on a mm/dd format would fail to parse correctly and also there would be some valid inputs where it produced a DateTime that was invalid for the current year because of leap years. 
This will only affect churches that are based in a location which …
=> Fix #2079: Grades Changing with Client Culture

Rock/Lava/RockFilters.cs
**Yes**
Needed to display a check mark if somebody had signed a e-signature document or an empty square if they had not.
New Lava filter that allows the builder to check if a person has signed a specific document template type.
New Lava filter can be passed either a Person object or an Id number of the person to check. The first parameter is the Id of the document template. Two additional parameters are available …
=> New Lava filter for checking if digital document is signed.

RockWeb/Scripts/jquery.tinyscrollbar.js
**Yes**
Partial fix for issue #1731.
Resolve the issue of not being able to use the mouse to scroll on mixed-input devices.
Enabled mouse-tracking events on touch input devices.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be …
=> Partial fix for scrolling problems on devices supporting touch and mouse

RockWeb/Blocks/WorkFlow/WorkflowEntry.ascx.cs
Yes
Passing a variable into a workflow via the QueryString worked fine, but the variable did not get passed to the workflow when using a route such as MyPage/{PersonId}
Check for parameters in both QueryString and routes.
Accessed RockPage.PageParameters(), which already checks both places for parameters, rather than Request.QueryString.AllKeys.
_If your code is a new method or function (that doesn't need a mock …
=> Updated WorkflowEntry to check for parameters in both querystring and routes

RockWeb/Blocks/CheckIn/RapidAttendanceEntry.ascx, RockWeb/Blocks/CheckIn/RapidAttendanceEntry.ascx.cs
**Yes**
Entering attendance for a large group of people (for example a worship service) is slow and time consuming.
A block which allows data to be entered as quickly as possible.
New block. Configuration allows selection of the parent group whose immediate children will be available for selection. When you select a group any locations defined for that group will be available for selection (if only one then it is …
=> New Rapid Attendance Entry block

RockWeb/Blocks/Cms/ActiveUsers.ascx, RockWeb/Blocks/Cms/ActiveUsers.ascx.cs
#2261
Add tooltips with JS scoped to the active user block to not impact performance.
Add JS and hints to the badges
N/A
N/A
(Replaced Guests with Users in this PR)
N/A
=> Updated the active users block to show hints at color dot meanings #2261

RockWeb/Blocks/Cms/PublicProfileEdit.ascx.cs
+ Added ability to disable First and Last Name editing in Public Profile Edit Block.
Yup!
Users are modifying names in the Public Profile Update block in ways that caused data integrity issues.  i.e. `John and Jane` in the First Name Field or completely changing the name to another family member.
Allow the data team to decide if the First and Last Name fields should be enabled when End Users edit.
Added an Advanced Block setting to Disable Name Edit.
None
Defaults to allow editing (like existing behavior) so no impact to most users.
None
=> Feature Disable Name Edit

Rock.Tests/Rock/Lava/RockFiltersTests.cs, Rock/Lava/RockFilters.cs
**Yes**
Enhance the well being of our users. #2252 
Make it easier for admins to be able to deal with URLs inside of Lava.
New Lava filter that acts as a front-end to the Uri C# class.
Unit-Test coming (just realized after putting this together that I don't have that yet). Will remove the `in progress` label when that is done.
Lava test and output below.
```
<p>
{% assign url = …
```
=> New Lava filter to parse and spit out components of a URL.

RockWeb/Blocks/Fundraising/FundraisingProgress.ascx, RockWeb/Blocks/Fundraising/FundraisingProgress.ascx.cs
**SÍ**
Matching block styles a little more closely to other Rock blocks.
1. Match block styles more closely with standard Rock styles.
2. Make the block hide itself when given a group that is _not_ a Fundraising Opportunity.
3. Make the block functional when viewing a single participant via `?GroupMemberId=123`
Items 2 and 3 allow for the block to be placed on the standard Group Detail and Group Member Detail pages and they only show up in the UI when …
=> Update FundraisingProgress styles and add functionality for single participant progress

RockWeb/Blocks/CheckIn/AttendanceHistoryList.ascx.cs
Yes
Attendance history filter options won't clear with "Clear Filter".
BindFilter method was missing in the respective event.
=> Fixed #2377 - Attendance history filter options won't clear with "Clear Filter".

RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Yes
'Registered By' Name is appended Twice when cases are mismatched for the system registered user
=> Fixed #2374 Registration person note adds duplicate registered by

Rock/Web/UI/Controls/ButtonDropDownList.cs
Yes
The Rock:ButtonDropDownList rendered a blank icon <i> even when the SelectionStyle is not Checkmark. This ends up offsetting the label even on the title.
=> Fixed #2344 Text Offsetting when SelectionStyle is Title in ButtonDropdownList

Rock/Model/GroupRequirement.cs
See discussion at #2422 and attachment:
This only affects `develop` as prior versions do not allow the requirement to be set at the GroupType level, only the Group level.  The obsolete-tagged method used prior to v7 checked to see if `this.Group` was NULL.
=> Fix exception in SQL/Lava requirement when set on GroupType

RockWeb/Blocks/Event/CalendarContentChannelItemList.ascx, RockWeb/Blocks/Event/CalendarContentChannelItemList.ascx.cs
**Darn Tootin' I Have**
Our staff keeps creating Content Channel Items to advertise an event before it's on the calendar. This currently requires us to use a convoluted URL to force an existing Content Channel Item to link to the calendar event occurrence.
Technically this will work around the problem. The staff will still do things in the wrong order but now we can let them clean up after themselves instead of us cleaning up the mess.
_How have you …
=> Added ability to link existing Content Channel Items to Calendar Events.

RockWeb/Blocks/Groups/GroupRegistration.ascx.cs
**Yes**
Issue #2402 
Minor tweaks to the overcapacity rule checking. Still does not fully match the internal logic, but should be closer to what end-users would expect.
Limit capacity checking to active members.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/R …
=> Fix Group Registration block to not count inactive or pending members when calculating capacity

Rock/Web/UI/Controls/RockRating.cs
Yes
Fixed Required Field Validation for RockRating Control
RockControlHelper.Init method was missing to be called inside RockRating due to which RequiredFieldValidator was never initialized  for the Rating control.
=> Fixed Required Field Validation for RockRating Control

RockWeb/Blocks/Groups/GroupFinder.ascx.cs
Yes
Campus filter could not be used without other filters being enabled in Group Finder.
Allow campus filter to be used by itself.
If other filters aren't enabled in Group Finder check to see if campus filter is enabled before btnSearch visibility is set to false.  …
=> Campus Filter Only Search Button Fix

RockWeb/Blocks/Connection/MyConnectionOpportunities.ascx.cs
Yes
Connections always show "last activity note" column even when set to not show the last activity note from block setting.
Correct the Column index for grid view. Previously it was pointing to 'Last Activity' column rather than 'Last Activity Note' Column
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST test your code before submitting a pull request._
_What could this change potentially impact? Are there any security …
=> Fixed #2430 Mapped show last activity note block setting with column

RockWeb/Blocks/Groups/GroupFinder.ascx.cs
Yes
Issue #2172
Fix errant pipe default on new instances of block.
**A migration needs to be created for:**
Block GUID: `7332DD26-D5F5-4736-BFCF-FC4AD97DD571`
Attribute GUID: `9DA54BB6-986C-4723-8FE1-E3EF53119C6A`
Changing:
`{% if LinkedPages.GroupDetailPage != '' %}` to `{% if LinkedPages.GroupDetailPage and LinkedPages.GroupDetailPage != '' %}`
`{% if LinkedPages.RegisterPage != '' %}` to `{% if LinkedPages.RegisterPage and LinkedPages.RegisterPage != '' %}`
Fixing `and` formatting:
`{% if Location.FormattedHtmlAddress && Location.FormattedHtmlAddress != '' %}` to `{% if Location.FormattedHtmlAddress and …
=> Fix Group Finder Block map links to detail pages

Rock/Rock.csproj, Rock/Workflow/Action/Utility/SetEntityAttribute.cs, Rock/Workflow/Action/Utility/SetEntityProperty.cs
👍 
As discussed in #2104, It would be great to have a way of setting attributes (and properties) on any entity inside a workflow. This would allow us to work with any entity we want, instead of being limited to the existing Actions or resorting to SQL 😨 to update things.
This change adds two new Workflow Actions for setting a property or attribute value for any entity.
I've added two new workflow actions - **Set …
=> + Added Workflow Actions for setting a Property or Attribute of any Entity.

RockWeb/Blocks/Security/Login.ascx.cs
Fixes #2115 
Change the Login block to check for locked and unconfirmed external accounts
I took the logic for checking for confirmation/locked accounts from the login method from the internal login button event and moved it to a separate method which is called by both the `lbLogin` and the `btnLogin`. The method signature and naming for that method are a bit weird because I'm bad at naming and I wanted to preserve the `UserLoginService` if it was an internal auth.
Not sure this is testable but if it is I'll happily write a test.
If someone has locked an external auth account previously there would've been no consequences. After this change, they'd be locked out.
🤷‍♂️
=> Change Login Block To Honour Locked & Unconfirmed External Accounts

Rock/Web/UI/RockPage.cs
Yes
Fixes #2412 Made Edit Properties Visible in Admin toolbar when User has Edit Role
Changed the dependency from Administrate to both Administrate as well as Edit at the time of displaying Edit Properties in Admin Bar.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST test your code before submitting a pull …
=> Fixes #2412 Made Edit Properties Visible in Admin toolbar when User has Edit Role

RockWeb/Blocks/Cms/PublicProfileEdit.ascx.cs
Yes
#2308 Person attributes not saving when adding a new family member on the external website
While adding New family member, DisplayEditAttributes method was not called on Load.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests …
=> Fixes #2308 Save Person attributes when adding a new family member

RockWeb/Blocks/Finance/TransactionEntityMatching.ascx.cs
Yes
#2481 Fundraising Matching - Displays inactive groups
minor tweak in TransactionEntityMatching to only list active group in the dropdown list.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be sure your pull request includes the corresponding unit tests in the Rock.Tests project. In all cases *you* MUST test your code before submitting a pull request.
N/A
What could this change …
=> Fixes #2481 Display only active groups in Fundraising Matching

RockWeb/Blocks/Event/RegistrationListLava.ascx.cs
**Yes**
If a registration instance had multiple linkages, one of which did not have an EventItemOccurrenceId, then the block caused an Oops error on the My Account page, preventing people from seeing the page. Error caused by the `hasDates` variable containing a list of any registrations that had _any_ Linkages with a valid `EventItemOccurrenceId`. Then later it being assumed that _all_ Linkages had a valid `EventItemOccurrenceId`.
Update the query …
=> Fixed bug in Registration List Lava block with multiple Linkages

DotLiquid/StandardFilters.cs, Rock/Lava/RockFilters.cs
Sorry this wasn't an issue or submitted as an enhancement, if I need to submit another way before the pull request please let me know. …
=> Sort Order for Lava Filters

RockWeb/Blocks/Finance/TransactionEntry.ascx.cs
Issue #2157 ... Ran into issue while completing #2337
Prevents field from populating when value is 0, also adds currency symbol on `lblTotalAmount` initial load. (Current behavior is `0.00` on initial load, currency sign `$0.00` is added after adding a value to an account).
Checked for 0
N/A
N/A
N/A
N/A
N/A
=> Fixed #2157 Funds in Giving block are populated with 0.00

Rock/PersonProfile/Badge/FamilyAttendance.cs
**Yes**
#2476 Help text/Tooltip and functionality was not in sync with each other in case of Child in Family attendance bar graph.
Modified Notes or Tooltip in case of Child in Family Attendance
Yes i changed the notes for child.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Roc …
=> Fixed #2476 Modified Notes or Tooltip in case of Child in Family Attendance

Rock/Web/UI/Controls/NewFamily/MembersRow.cs, Rock/Web/UI/Controls/Pickers/DatePicker.cs, RockWeb/Blocks/Connection/ConnectionRequestDetail.ascx, RockWeb/Blocks/Crm/PersonUpdate.Kiosk.ascx, RockWeb/Blocks/Finance/TransactionEntry.ascx, RockWeb/Blocks/Groups/GroupAttendanceDetail.ascx, RockWeb/Scripts/Rock/Controls/datePicker.js
Credit card transaction entry selection allows you to select dates in the past. Preventing the ability to select invalid dates improves UX.
Add `AllowPastDateSelection` method that matches `AllowFutureDateSelection`
Added `AllowFutureDateSelection` to New Family and past to ConnectionRequestDetail.ascx, PersonUpdate.Kiosk.ascx, GroupAttendanceDetail and `AllowPastDateSelection` to TransactionEntry
None 😞 
Prevents frustration? Implications are minimal because it's still possible to force a invalid selection, the date picker just won't display the date.
From the transaction entry block. (The disabled dates …
=> Added JS to date picker to prevent selecting past dates

Rock/Lava/RockFilters.cs
**Yes**
When you have a Group Guid, for example from a Group attribute in a Workflow, you have no good way to load that group in Lava to get information from it. This provides that ability.
Greater flexibility through insignificant innovation.
Copy and Paste the PersonById and PersonByGuid methods and rename a few words.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes …
=> Add new Lava filters GroupById and GroupByGuid

RockWeb/Blocks/Crm/PersonDetail/AttributeValues.ascx.cs, RockWeb/Styles/developer.css
**Yes**
The display of a matrix type attribute is a little awkward since the 'data' portion spills over into the title area
Minor css fix related to display of a matrix Field in AttributeValues block
I have defined few custom css to align the grid and label to correct position.
Also done minor changes in AttributeValues  to call those CSS class in case of Matrix field type.
If your code is a new method or function (that …
=> Minor css fix related to display of a matrix Field in AttributeValues block

RockWeb/Blocks/Crm/PersonMerge.ascx.cs
**Yes**
Created Date Time is always set in respect to person selected.
To Use earliest Created Date Time on People Merge
Queried minimum date time on all the person at the time of merge.
If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFiltersTests.cs) be …
=> Fixes #2516 Used earliest Created Date Time on People Merge

RockWeb/Blocks/Security/BackgroundCheck/ProtectMyMinistrySettings.ascx, RockWeb/Blocks/Security/BackgroundCheck/ProtectMyMinistrySettings.ascx.cs
PMM will send results over non-SSL connection. Make sure admin sees big fat warning when configuring as such. See #2578.
Ensure the admin is informed that they are using a non-SSL connection to get results from PMM.
Since HTML5 killed the `blink` tag I had to resort to a Bootstrap alert div.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit …
=> Show big fat warning on PMM configuration page when using a non-SSL URL

RockWeb/Blocks/Event/RegistrationTemplateDetail.ascx.cs
**Yes**
In certain PostBack situations, such as clicking Edit and then clicking Cancel, the read-only list of forms would duplicate and show multiple copies of the same form(s). See #2152.
Fix the problem.
Clear existing text data before appending new data to the Literal control. …
=> Fixed Event Template Details from showing duplicate forms in certain situations.

RockWeb/Blocks/Groups/GroupRegistration.ascx.cs
**In at least one universe in this grand Multi-verse, Yes**
Group Registration block would throw errors if spouse cell phone was left blank and an existing spouse had been found in the database. See #2339.
Make bugs go away.
Emptied a can of RAID&trade; on the source code.
Took solution for previous fix that applied to the "primary" person and applied it to the spouse. Code now checks if the phone number is …
=> Updated Group Registration block to not error if no spouse number is blank

Rock/Web/UI/Controls/AttributeEditor.cs
Have you filled out and sent your [Spark Contributor Agreement](http://www.rockrms.com/Content/RockExternal/Misc/Contributor%20Agreement …
=> Added Subtitle (Attribute Id) To Modal Dialog from Attribute Editor

RockWeb/Styles/_store.less
**Yes**
While "Icon Safe Area" is not exactly a correct statement, I believe it conveys the idea. Basically we are recommending developers put an icon in the "red section" of the package banner (420x210 centered) and other information, such as possible text, outside of that "safe area". However on wider monitors, such as 1920x1080, the browser window is wide enough that the package icon displays outside this "safe area" and will display text.
While we don't have a good way yet to have a dedicated icon, this at least provides a …
=> - Updated Rock Store to only show Icon Safe area of plugin image

RockWeb/Blocks/WorkFlow/WorkflowEntry.ascx.cs
**Yes**
This fixes two separate, but related issues (See #2567 for details of first issue):
1. If a User Entry Form exists on an activity, and that activity is activated multiple times, then the first activity is always processed even if the form-action is already marked as completed.
2. If two User Entry Forms exist on a single activity, the same issue can cause the first form to always be displayed instead of the second form.
Fix the problem.
_How have …
=> WorkflowEntry block executes wrong Activity

Rock/Attribute/EnumFieldAttribute.cs, Rock/Attribute/EnumsFieldAttribute.cs
Yes
I needed to add two different Enum block settings to a single block.
This will allow more than one Enum attribute to be added to a single block.
I set AllowMultiple to True on EnumFieldAttribute (and also EnumsFieldAttribute merely for consistency). …
=> Allowed multiple enum attributes to be added to a single block

Rock/MergeTemplates/WordDocumentMergeTemplateType.cs
Yes
We generate documents that have page number fields in them, and we needed these page number fields to work properly in the final generated file.
To allow page number fields (and other field codes) to remain in generated Word documents.
Set RemoveFieldCodes = false in SimplifyMarkupSettings.
Field codes will now remain in Word templates, so if anyone has fields in their templates that they don't want to be retained in the final document, this may be a problem. I'd this this is pretty unlikely.
=> No longer removes field codes in Word merge templates

RockWeb/Blocks/Finance/ContributionStatementLava.ascx.cs
Also fixed spelling of `adjustedPledgeEndDate`
See #2647
Fix the exception-causing code.
Verified that the date is not the maximum allowed value before adjusting it.
=> Fix #2647, don't adjust DateTime.MaxValue

Rock/Web/UI/Controls/CodeEditor.cs
**Yupz**
See issue #2557 for full discussion.
If the `CodeEditor` control is not visible in the .ascx file, but then made visible in the OnLoad method of the block (i.e. not a postback, but not visible by default as we want to decide based on query string parameters or something), the ace.js does not get included.
Make sure ace.js gets included properly.
Move the ace.js inclusion into the OnPreRender event method. …
=> Initialize ace.js later in CodeEditor initialization

Rock/Field/Types/DecimalRangeFieldType.cs, Rock/Field/Types/DefinedValueRangeFieldType.cs, Rock/Field/Types/GroupAndRoleFieldType.cs, Rock/Field/Types/GroupTypeGroupFieldType.cs, Rock/Field/Types/IntegerRangeFieldType.cs, Rock/Field/Types/SlidingDateRangeFieldType.cs
**はい** (Yes)
See #2596. Some field types, specifically ones that normal return a comma or pipe delimited value from the editor, would return a `,` value instead of null if no values were set. This prevented the default value from being used instead.
Update field types to allow returning null instead of `,` when empty.
Check for blank values before returning the formatted string.
_If your code is a new method or …
=> Updated various field types to support reverting to default value.

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
Yes
Fix spelling errors on contributing guide and pull request template.
📝 👍 
N/A
N/A
N/A
N/A
N/A
N/A
=> Fixed spelling on github contributing & PR template

Rock/Workflow/Action/CheckIn/SetAvailableSchedules.cs
Yes
Fix spelling on Set Available Schedules workflow description. To `Sets the available schedules for each grouptype, group, and location`
Fix
N/A
N/A
N/A
N/A
N/A
N/A
=> Fixed available spelling on Set Available Schedules workflow

Rock/Reporting/DataFilter/NotInOtherDataViewFilter.cs
=> Fixes #2718 - The 'Not in Existing DataView' is being implied inversly.

RockWeb/Blocks/Communication/TemplateDetail.ascx.cs
Email template preview images keep disappearing from our list of templates. We found that was because the images are being marked as temporary and being removed.
To not have to upload our preview images anymore.
On save, if the image changes delete the previous image (if exists) and set the new image as not temporary.
N/A
None.
N/A
N/A
N/A
=> Email template preview images delete fix.

RockWeb/Blocks/Administration/Pages.ascx, RockWeb/Blocks/Cms/ContentChannelDetail.ascx, RockWeb/Blocks/Cms/ContentChannelTypeDetail.ascx, RockWeb/Blocks/Finance/BatchDetail.ascx, RockWeb/Blocks/Finance/BenevolenceRequestDetail.ascx, RockWeb/Blocks/Prayer/PrayerCommentDetail.ascx, RockWeb/Blocks/Security/BackgroundCheck/ProtectMyMinistrySettings.ascx, RockWeb/Blocks/Security/RestKeyDetail.ascx
Yes
#2708, the batch detail block and a few other blocks were missing access key shortcuts on the save and cancel buttons
Add access keys to save and cancel buttons.
`Alt+s & Alt+c`
N/A
N/A
N/A
N/A
N/A
=> - Added missing access key shortcuts on save and cancel buttons

Rock.Slingshot/BulkImport/BulkImportHelper.cs, Rock.Slingshot/SlingshotImport/SlingshotImporter.cs
See https://github.com/SparkDevNetwork/Slingshot/issues/9.  The code between `LocationImport` and `PersonAddressImport` wasn't consistent with truncating Street1 and Street2 to 100 characters.  This change makes that consistent.
Ideally the LocationImport and PersonAddressImport should use the same logic, but refactoring doesn't fit in my timeline 😸
=> Slingshot: Fix EF error on location import

Rock/Model/Registration.cs, Rock/Model/RegistrationTemplateFormField.cs, RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Lack of ability to allow registrants to update their connection status.
Grant ability to allow registrants to update their connection status.
Duplicated the Marital Status person field code to handle the similar Connection Status.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested [see example](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests/Rock/Lava/RockFilt …
=> Add Connection Status as a possible Person Field when building Registration Templates

Rock/Web/UI/Controls/CodeEditor.cs
Yes
Fixes #2806
Increase usability of code editor by automatically wrapping lines
Add `ce_{0}.getSession().setUseWrapMode(true);` to CodeEditor control
N/A
None
N/A
N/A
N//A
=> Updated Ace Editor to wrap lines by default

Rock/Web/UI/Controls/ModalDialog.cs, RockWeb/Blocks/Event/RegistrationInstanceLinkageDetail.ascx, RockWeb/Blocks/Event/RegistrationInstanceLinkageDetail.ascx.cs
See #2624. The dialog on the Registration Instance screen to link to an existing Calendar Item was broken and did not work.
Make it work as one might expect.
1. Fix the Calendar Item drop down to not reset itself.
2. Updated the display and sorting on the Occurrence drop down to be more useful and show the campus name and the next start datetime of the occurrence. Sorting is now done by "All Campuses" first, then by Campus Name, then by …
=> Fixed ability to link Registration Instance to existing Calendar Item.

Rock.Slingshot/SlingshotImport/SlingshotImporter.cs
=> Fixed issue with slingshot images getting enumerated multiple times

RockWeb/Webhooks/Lava.ashx
**Yes**
If a user defines the Value of a Lava Webhook endpoint as just `vcard` instead of `/vcard` then it will never be matched, as the code expects all endpoint values to begin with `/`.
Make the beginning `/` optional.
If the DefinedValue value does not start with `/` or `^` then prepend '/' to the URL string.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) …
=> Update Lava Webhook endpoints to not fail when DefinedValue does not start with /

Rock/Communication/Medium/Sms.cs
**Yes**
Issue #2552, when all 899 available response codes had been used in the past 30 days the system would loop forever trying to generate a new code.
Increase number of available codes, decrease window for a code being considered "used" and rework the loop to have a final escape.
System now supports up to 5-digit response codes. It generates them in a "bucket system" of 100 at a time, between 100 and 90,000 …
=> Reworked SMS Response Code generate to prevent infinite loops.

Rock/Lava/Blocks/Sql.cs
See #2866. Currently no way to use SQL parameters with Lava `{% sql %}` syntax which makes it harder to protect against SQL injection.
Provide parameters to `{% sql %}` syntax. See original issue for example(s).
Added new code for passing extra parameters specified in the `{% sql %}` command into the SQL statement. …
=> Added support to the Lava Sql block for Parameterized SQL statements

Rock/Data/DbContext.cs, Rock/Model/WorkflowTrigger.cs, Rock/Workflow/TriggerCache.cs, RockWeb/Blocks/WorkFlow/WorkflowTriggerDetail.ascx.cs, RockWeb/Blocks/WorkFlow/WorkflowTriggerList.ascx, RockWeb/Blocks/WorkFlow/WorkflowTriggerList.ascx.cs
See #2369, #2667, #2671.
1. Inability to use "did value change in any way" logic on pre-save actions.
2. Inability to use "did value change" logic on post-save actions.
3. Inability to have a trigger only run when an entity is added (as opposed to anytime it is saved).
4. Qualifier check logic not consistent between pre-save and post-save.
Resolve those items.
1. If no previous value or current value are specified in the trigger configuration it is …
=> Update Workflow Trigger actions and logic

Rock/Follow/Event/PersonBaptized.cs
See #2612. Desired to have the ability to receive following reminders when somebody was baptized N years ago, such as a 5th anniversary.
Add support to the Following job for this feature.
Added new "anniversary count" configuration field to indicate how many years after the event to trigger on. …
=> Improved Baptism Following Event to support N years after date anniversary reminders

RockWeb/Blocks/Reporting/ReportDetail.ascx, RockWeb/Blocks/Reporting/ReportDetail.ascx.cs
Yes
Not being able to right hand click a link or open a link in a new tab is a bummer. This PR takes the Data View link contained on the Report Detail block and allows right clicking by moving the link from a `OnClick` JS event to a href.
Fully functional, right clickable link.
Remove `OnClick` change `asp:LinkButton` to `asp:HyperLink`
N/A
N/A
Changes `Data View` link on lower right side
N/A
N/A
=> - Added link to Report Detail Data View link instead of OnClick JS

RockWeb/Blocks/Crm/PersonMerge.ascx.cs
Yes
Issue #2174, when merging a listed and unlisted phone number the unlisted number always shows `Unlisted`. Making it difficult to determine the winning record.
When a number is unlisted, use number formatted and _(Unlisted)_ i.e. `(559) 555-5555 <em>(Unlisted)</em>`
If statement that looks for unlisted.
N/A
N/A
_Ignore the { typo, fixed in commit 🙃 _
N/A
N/A
=> - Added the ability to view unlisted phone numbers in person merge block

Rock/Model/Person.cs
Yes
Issue #662. Chose against adding lava hooks since date differences can be calculated in lava and are less likely to be used.
Replicate `DaysToBirthday` for anniversary
Mash up `DaysToBirthday` and `NextAnniversary` code
N/A
N/A
N/A
Might want to mention anywhere `Days To Birthday` is.
N/A
=> Added 'Days To Anniversary' to person report fields

Rock.Migrations/Migrations/20180313_AddDaysUntilAnniversary.sql, Rock/Model/Person.cs
See #662.
Ability to query in a DataView by the number of days until an anniversary, in the same way you can filter by the number of days until a birthday.
Add the placeholder property in the code and a new SQL script to add a dynamic column that is calculated the same way as the Days Until Birthday column. …
=> Added new DataView filter for Days Until Anniversary

RockWeb/Blocks/Finance/ScheduledTransactionListLiquid.ascx.cs, RockWeb/Themes/Flat/Assets/Lava/ScheduledTransactionListLiquid.lava, RockWeb/Themes/Stark/Assets/Lava/ScheduledTransactionListLiquid.lava
Yes
People are confused about what card is being used for a scheduled transaction. If the transaction uses a credit card renders a descriptive: `{{ ScheduledTransaction.CreditCardType }} {{ ScheduledTransaction.AccountNumberMasked }}` instead of `Credit Card`
Provide a liquid tag inside the scheduled transaction list lava block. Also change the currency tag to be internationalized. (Templates previously used `$`)
N/A
The `AccountNumberMasked` could show unmasked account numbers if the migration masking NMI cards never ran.
N/A
N/A
N//A
=> + Updated scheduled transaction list lava to include card number

RockWeb/Blocks/Fundraising/FundraisingProgress.ascx.cs
See #2897. If the total goal amount for the main progress bar was 0, a divide by zero error occurred.
Fix the bug.
Computers should be able to divide by zero, but changing the code to not divide by zero seemed like a simpler solution.
Progress bars now show 100% if the goal is zero since the goal would always be reached.
_If your code is a new method or function (that doesn't need a mock database or SqlServerTypes library) and can be Xunit tested …
=> Fixed Fundraising Progress to not divide by zero if goal is zero.

Rock/Lava/RockFilters.cs
Usage: {% assign person = Guid | PersonByAliasGuid %}
Allows a person to be loaded via a person alias guid. Useful in cases where a long-lived url referencing a person needs to exist, but a person alias id isn't appropriate for issues related to privacy.
(In our specific example at CCV, we email links to baptism photos. We don't use IDs because they can be enumerated by the recipient to view other's photos. We don't use the direct person guid because it can be lost during a person merge.)
=> + Added PersonByAliasGuid lava filter

Rock/Model/RegistrationTemplateDiscount.cs, RockWeb/Blocks/Event/RegistrationEntry.ascx.cs, RockWeb/Blocks/Event/RegistrationTemplateDetail.ascx, RockWeb/Blocks/Event/RegistrationTemplateDetail.ascx.cs
There are times when an organization has an event that offers a discount.  Instead of providing a discount code, they want to have the discount apply automatically based on the configured limits.
*Scenario 1: Group Discounts*
An organization offers an event with a cost of $25 per person.  If two or more people are registered together, the cost is automatically reduced to $15 per person.
*Scenario 2: Limited Time Discount*
An organization offers an event that has a limited time discount.  If the person registers before the deadline, they automatically receive a 20% discount.
This will add a new registration discount setting that will allow the discount to be applied automatically based on the configured limits:
When the registrar gets to the summary screen and they qualify for a discount, …
=> Added support for automated registration discounts

RockWeb/Blocks/Communication/CommunicationEntryWizard.ascx
Yes
There's an extra blank line height on the email editor. This PR removes it.
Remove the extra blank line.
Delete `<asp:ListItem />` 
N/A
None
N/A
N/A
N//A
=> Removed Extra blank Line Height on email wizard

Rock/Model/ExceptionLogService.Partial.cs, RockWeb/App_Code/Global.asax.cs
When an error occurs during initialization of Rock, it can be near impossible - or at least very difficult - for users to find out the exception if the error is logged to the database but Rock failed to start. This is because the UI is not available.
See #2733 
Make ExceptionLogService always log to the RockExceptions.csv file during startup.
Added a static property to ExceptionLogService to indicate that it should always log to file. Would have …
=> Updates ExceptionLogService to always log to file during startup.

RockWeb/Blocks/Administration/PageProperties.ascx, RockWeb/Blocks/Cms/SiteDetail.ascx, RockWeb/Blocks/Communication/CommunicationEntryWizard.ascx, RockWeb/Blocks/Core/BlockProperties.ascx, RockWeb/Blocks/Crm/PersonAttributeForms.ascx, RockWeb/Blocks/Event/RegistrationTemplateDetail.ascx, RockWeb/Blocks/Finance/AccountDetail.ascx
Yes
#2774, incorrect errors from Ace when editing valid code
Replace `EditorMode="Html` with `EditorMode="Lava"` to prevent errors and provide relevant syntax highlighting
Change EditorMode
N/A
N/A
N/A
N/A
N//A
=> Updated code editor blocks to prevent incorrect html errors

RockWeb/Blocks/Groups/GroupListPersonalizedLava.ascx.cs, RockWeb/Themes/Rock/Assets/Lava/GroupListSidebar.lava, RockWeb/Themes/Stark/Assets/Lava/GroupListSidebar.lava
=> Show Inactive Groups in GroupListPersonalizedLava block

RockWeb/Blocks/Store/PurchasedPackages.ascx.cs
See #2882. If you have purchased a plugin but it is not installed on the server, then viewing your purchased plugins will throw a null reference exception. This can happen, for example, if you have installed a plugin on your production system but not yet installed it on your dev system.
I think I did this correctly against the hotfix-1.7.4 branch.
Fix the null reference exception so the user can see their purchase history.
Check if there is no …
=> Fixed bug in Purchased Plugins page that would throw exception if a plugin is not installed

Rock/Web/UI/Controls/RockListBox.cs
The items selected on a RockListBox control should be splitter using a comma-delimiter.
It wasn't possible to select some items on the RockListBox control due to not using the correct delimiter to parse the selection string.
It splits the items selected using a comma-delimiter.
=> Fixes RockListBox items selection

RockWeb/Blocks/Core/TagReport.ascx, RockWeb/Blocks/Core/TagReport.ascx.cs
Inability to add people directly to a tag without going to their profile page. See #556.
Grant ability to do so.
When viewing the members of a tag, if the tag entity type is a Person then the Add button becomes available in the action bar. Upon clicking a modal dialog opens with the person picker expanded by default and ready to type in a person's name. You can then either Save and it will close the modal or Save And Add and it will add the person …
=> Added ability to add people to tags when viewing the tag details page

RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Fees should retain the order they were assigned when showing on the form.
Fees are not being ordered on the form.
Orders the fees.
N.A.
=> Added missing order on fees

RockWeb/Blocks/Administration/NotificationList.ascx, RockWeb/Blocks/Administration/NotificationList.ascx.cs
See #2896. Notifications were deleted instead of marked as read, thus making it impossible to tell when a user read (that is, acknowledged) the notification.
Also fixed up a few UI issues and some comments and method locations in the code behind.
Notifications should be marked as read instead of deleted.
1. When clicking the "X" button the notification recipient record is now marked `Read = 1` and `ReadDateTime = RockDateTime.Now()` instead of being …
=> Updates to Notification List block to mark notifications as read intead of deleting them

Rock/Jobs/GetScheduledPayments.cs
By default payments will download from all active financial gateways.  Churches that run multiple gateways/bank accounts have difficulty reconciling transactions to the right funds if the batch includes transactions from all gateways.  
This PR adds the capability to select a single gateway to download scheduled payments from.  If selected, additional jobs need to set up targeting other active gateways (note included in the description).  This PR is sponsored by [Willamette Christian Church](http://willamette.cc/).
Added a Target Gateway block attribute to the Rock GetScheduledPayments Job and filtered the active gateways queryable to return the target gateway if it …
=> Add the ability for GetScheduledPayments to target a specific gateway

Rock/Web/UI/Controls/PhoneNumberBox.cs
Added logic to only store in the phone number text-box the first 20 digits typed to match the phone number length set on the database.
The phone number box field allowed entering numbers longer than 20 digits causing an entity validation error when saving it on the database.
Added a line of JavaScript code that only keeps the 20 first digits entered in the text-box.
=> Fixes minor validation bug in PhoneNumberBox

RockWeb/Blocks/Event/RegistrationDetail.ascx.cs
Hides the new submit button used only for 3step gateways when submitting a manual payment.
2 submit buttons are displayed when trying to add a manual payment. The new Submit button that is used for 3 step gateways shouldn't be visible when processing manual payments.
Hides the wrong submit button on the manual payment screen.
=> Hides wrong manual payment submit button

RockWeb/web.config
Reference [here](https://weblogs.asp.net/scottgu/442448) and [here](https://bitsandscrews.com/10-solid-tips-to-increase-and-optimize-iis-performance-for-2018-covers-asp-net-wordpresscoldfusion-and-sharepoint/#Disable_ASPNet_debugging_from_WebConfig).  This setting is the default, which gets passed to the installer and deployed to production environments.
To fix existing Rock installations, we may need to add a setting under System Settings > System Config.
=> Set debug property in web.config

RockWeb/Blocks/Crm/BulkUpdate.ascx, RockWeb/Blocks/Crm/BulkUpdate.ascx.cs
1. Update block to use multiple background threads when performing updates. By default it will use the number of "cpu threads", but the user can override with a block setting (up to 64). A "cpu thread" is the number of cores available, including hyperthreading. So a quad-core CPU with hyper-threading would use 8 worker threads. (See Note Below)
2. Updated block to use SignalR to give live feedback to the user about the progress. This also means no more timeouts when doing massive updates. Progress is given in 2.5 second increments.
Note on worker threads: It looks like C# managed code (i.e. Rock) is limited to a single CPU group by default. From what I understand of the docs, it looks like a dual-CPU system would have 2 CPU groups. This means the C# code (Rock) could only use 50% of the …
=> Bulk Update block enhancements to performance and UI progress

Rock/Communication/Transport/Twilio.cs, Rock/Jobs/LocationServicesVerify.cs, Rock/Jobs/RockCleanup.cs, Rock/Services/NuGet/RockProjectManager.cs, Rock/Transactions/RunJobNowTransaction.cs, RockWeb/Blocks/BulkImport/BulkImportTool.ascx.cs, RockWeb/Blocks/Core/ScheduledJobList.ascx.cs, RockWeb/Blocks/Crm/BulkUpdate.ascx.cs, RockWeb/Webhooks/LaunchWorkflow.ashx, RockWeb/Webhooks/Lava.ashx, RockWeb/Webhooks/Twilio.ashx
Replaces calls to `Thread.Sleep(x)` with `Task.Delay(x).Wait()`.
Fixes: #3125 
I was only able to test the changes to the BulkUpdate block and the ScheduledJobList block. But I did run an additional check in a stand-alone console app of putting `Task.Delay(5000).Wait()` to verify that the method works outside of a "task" so this should not cause any change of functionality.
n/a
=> Updated uses of Thread.Sleep() to call Task.Delay().Wait() instead. (Fixes #3125)

Rock/Lava/RockFilters.cs
Add optional third parameter to the `Groups` filter that allows for including inactive groups.
Fixes: #2380 
New item to add to Groups filter documentation:
* Group Status (optional): By default the filter will only include active groups. Pass the string 'All' to include inactive groups as well.
=> Added ability for Groups Lava filter to include inactive groups too

Rock/Web/UI/Controls/RockCheckBoxList.cs
RockCheckBoxList has never properly triggered the SelectedIndexChanged event. This PR adds that functionality. Like the standard CheckBoxList control, this requires the `AutoPostBack` value to be enabled as well.
Fixes: #1169
This is somewhere between a bugfix and a feature, but the related issue is listed as a bug.
n/a
=> Fixed the RockCheckBoxList control to properly trigger SelectedIndexChanged event.

Rock/Model/SignatureDocumentTemplateService.Partial.cs
When sending a signature document invite to a person, Sign Now will return an error. This is caused by Rock requesting a document that does not yet have a document key. Originally, there was an issue where previously made documents would be recreated again and again. A change was made to fix this, but it would never create a new document.  We collaborated with Chris Funk to make sure this doesn't break fixes he made previously. Now the logic checks to see if the document in rock has a document key and if it does not it will make one, otherwise it will just resend. 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
=> Fixed issue where signature documents could not be sent

RockWeb/Blocks/Cms/ContentChannelView.ascx.cs
When using the Content Channel View block and editing filters, if you add a new Filter Group or Filter, the action buttons for those new items will now show up until a second postback occurs. This was due to the event handlers not being installed before the new items were rendered.
Fixes: #1574
n/a
n/a
=> Fixed Content Channel View to show buttons when new filter groups are added.

RockWeb/Blocks/Reporting/DynamicData.ascx.cs
Adds block setting to the Dynamic Data block that allows the block to specify it's own enabled lava commands. This allows users to use entity commands and other things in a DD block without enabling them globally.
For completeness, this enabled the specified lava commands in the SQL Query Lava, the Page Title Lava, and the Custom Results Lava.
Fixes: #2474
n/a
n/a
=> Added Enabled Lava Commands setting to Dynamic Data block.

Rock/Lava/RockFilters.cs
When using {{ 'Global' | Client:'ip' }} with a load balancer or reverse proxy. The HTTP_X_FORWARDED_FOR ip address gets overwritten by forwarding ip address. This means that every IP will be the same. This change adds an `else` so it only uses the address if there is no forwarded for.
=> Fixed lava bug where HTTP_X_FORWARDED_FOR was ignored

RockWeb/Blocks/Finance/ContributionStatementLava.ascx.cs
Modifies the Contribution Statements Lava block to allow passing the contribution year as a route parameter.
Closes: #3292
=> Allow using StatementYear as a route parameter (Closes #3292)

RockWeb/Blocks/Groups/GroupDetail.ascx.cs
Our Rock admin has long wanted the ability to click on the Group Type label on the top of the group viewer page and be taken to the detail page for that group type. Additionally, having a tool tip with the description of the group type would be very helpful.
This checks to see if the user can administrate the page before making the text clickable.
=> Enhancements to group type highlight label

RockWeb/Blocks/CheckIn/LocationSelect.ascx.cs
This allows the Location Select block to display the list of Locations by the `Order` property instead of `Name` (defaults to `Name`).
Fixes: #3278
=> Added block setting that allows sorting of Locations

Rock/Rock.csproj, Rock/Workflow/Action/CheckIn/FilterGroupsByDataView.cs
At Southeast we have found that the standard check-in filters do not give us as much control over our check-in as we would like. About 2 years ago we created a way to use data views in our check-in system. We use check-in by data view more than any other type, and frequently have had requests for it. This is an improved version of what we have been running weekly at SECC.
I've promised to contribute this for over a year. This workflow supports …
=> + Added workflow action to check-in by data views

Rock/Model/Person.cs
The PreSaveChanges on a person previously inactivated the person in all groups when that person was inactivated.  Now it will also inactivate all connection requests.  This is a change that is consistent with existing functionality.
This is a pretty simple change.  It mirrors the functionality directly before it in the GroupMember section.
I'm not sure any documentation needs to be updated.  I reviewed some of the documentation surrounding when a …
=> Automatically inactivate all Connection Requests for a person when they are marked inactive and deceased.

RockWeb/Blocks/Connection/MyConnectionOpportunities.ascx.cs
By removing the loading of the ConnectionRequests from the block code, you can speed up the loading of the block without changing what you can accomplish with the Lava.
I removed the code loading the Connection Requests to the Opportunity Summary Template.  This dramatically speeds up load times when there's a high number of Connection Requests.
Fixes: #3397 
This can only cause an issue in the unlikely case where someone uses `{{ ConnectionRequests …
=> Removed Unnecessary Merge Field Loading

Rock/Jobs/CompleteWorkflows.cs
We noticed that our complete workflow jobs were taking longer and longer to run each night. On investigation it turns out that the Complete Workflow job completes all workflows and actions instead of just the active ones. This PR is to change this to only select active workflows to complete. I used the same logic used in `Workflow.IsActive`.
=> Changed complete workflow job to only close active workflows

RockWeb/App_Code/GetImage.ashx.cs
Fix an issue where requesting than an image be resized larger than it's existing size can cause it to return nothing.
Fixes: #3431
I made the changes suggested by @cabal95 in not disposing the file stream. I added an additional check to make sure the returned stream had length before returning.
N/A
=> Fixed issue where requesting oversized image return nothing Fixes: #3431

RockWeb/web.config
The ImageResizer settings are set to limit resizes to 3,600 x 3,600 pixels. This prevents sizing an image for a 4K display (3,840 x 2,160). This PR ups that limit to 4,000 x 4,000 pixels.
Fixes: #3430
This PR is a change to the web.config.
=> - Upped ImageResizer limits to 4,000x4,000 pixels. (Fixes #3430)

RockWeb/Webhooks/Lava.ashx
This is just adding a try/catch for situations where a Cookies parameter might already exist in the lava merge dictionary.
This probably doesn't occur for most other churches in other hosting environments but in our situation,, for some reason in some situations, the Cookies key already existed in the dictionary so it was throwing an error that we were logging.
N/A
=> Exception handling for situations where Cookies already exist.

Rock.Tests/Rock/Lava/RockFiltersTests.cs, Rock/Lava/RockFilters.cs
When trying to sort a list of objects that came from a JSON source ( using `|FromJson`), `|Where` doesn't work if you are filtering by an integer.  This makes filtering by Id or some other number challenging. The reason is that JsonConvert.DeserializeObject converts all numbers as long and it doesn't match the provided int. I have changed the way the two objects are compared so that the expected outcome happens. Unit tests included.
Related …
=> Fixed lava where filter to work with arbitrary data

RockWeb/Blocks/Connection/MyConnectionOpportunities.ascx.cs
Currently the 'Last Activity' column in the My Connection Opportunities block will sort the requests by the name of the last activity when clicking the column header. It would be much more useful if this sorted the request by the date and time of the last activity rather than the name of the last activity.
- [x ] Bugfix (non-breaking change which fixes an issue)
- [ x] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [x ] I have read the [Contributing to …
=> Update 'Last Activity' column in the My Connection Opportunities to sort by date/time

Rock/Field/Types/SchedulesFieldType.cs
We have several volunteer groups with member attributes of type Schedules that we want to be able to filter on when in the Group Viewer. This code would enable a filter control for Schedules that matches results that contain one of the selected schedules, drawing from the Schedule and Categories (for the 'contains' feature) Field Types.
None
=> Added a filter control for the Schedules FieldType

Rock/Web/UI/Controls/Grid/Grid.cs, RockWeb/Blocks/Communication/CommunicationDetail.ascx, RockWeb/Blocks/Communication/CommunicationDetail.ascx.cs
Updating the Failed grid on communication detail to convert communication recipients into people in order to create a merge document. Also, as a small bonus, you can now pick a sub-set of those people so you can pick and choose who you would like to merge.
Fixes: #3400 
=> Fixing the Merge Template functionality when executed from the failed communication list

Rock/Model/PersonSignal.cs
The Person Signal model should have been configured to have a Parent Authority back to the Signal Type. It didn't for some reason. Most likely due to my own stupidity when originally drafting the code.
The result was that anybody with access to the Person Signals List block could see the Note of the signal as well.
Fixes: #3576
> Note: This PR is based against the hotfix-1.8.8 branch.
If your pull request requires a migration, please *exclude the …
=> Fixed Person Signals not respecting View security of parent SignalType

DotLiquid/StandardFilters.cs, Rock.Tests/Rock/Lava/RockFiltersTests.cs
The `StripHtml` filter currently does not recognize multi-line HTML comments. This fixes that and adds two unit tests.
Fixes: #3548
n/a
n/a
=> Fixed StripHtml Lava filter to properly handle HTML comments.

RockWeb/Blocks/Finance/TransactionEntityMatching.ascx.cs
When dealing with Fundraising matching, you often will only be matching a handful of transactions out of a batch. However, the code currently will _un-match_ a transaction if the Group Member is not set at all.
This becomes a problem when you have a batch with 10 transactions. Say this is a batch for a Event Registrations. One of those transactions needs to be moved to be a Fundraising payment because we realize we probably shouldn't have put a fee on that event. So we have all 10 transactions showing on our Fundraising Matching screen, all the drop downs are blank. We change the drop down for line item 3 to match a fundraising participant and click Save. The way things work prior to this patch, it will disassociate the other 9 transactions and leave them just floating out there not …
=> Fixed Fundraising Matching to be better about not un-matching transactions accidentally

Rock/Web/UI/RockTheme.cs, RockWeb/Blocks/Cms/ThemeList.ascx.cs, RockWeb/Blocks/Cms/ThemeStyler.ascx.cs
One of the challenges I've run into when developing a Rock Theme is the sparse error messages produced when Rock is unable to compile a .less file. This PR adds extra logging to the Less compilation process and tweaks the formatting where it's displayed to show exactly where the error is and what caused it.
Before:
After:
N/A
N/A
N/A
=> Improved error messages when compiling Themes.

RockWeb/Blocks/Groups/GroupDetail.ascx.cs
If you have a Check-in Group type set to Show in Navigation, you are able to change that check-in group's schedule and location configuration from the Group Details page. Previously, this page did not flush the check-in cache which would leave the check-in state out of sync from the database.
If the group had GroupLocation data that has been modified then the check-in cache is emptied upon save. Used the `GroupMemberWorkflowTrigger` logic in the same method as a template for implementing conditional cache flushing so we don't flush the cache every time any group is saved.
Fixes: #2975
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any …
=> Fixed check-in configuration getting out of sync when editing a check-in group in Group Details page.

Rock/Web/Cache/RockCache.cs
A couple weeks ago we ran into an issue where our check-in went down on a Sunday morning due to some issues with cache throwing errors (screenshot below.) It turns out the reason was one of our cache tags had a null cache key in its list of cache keys. I've spent the morning trying to figure out how we managed to generate a null cache key and I have no idea. But we did, and it broke everything. Thankfully clearing all cache fixed the issue. 
This PR is a small change to RockCache to be tolerant of null strings in the list.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …
=> Fixed null reference in cache

RockWeb/Blocks/Administration/SystemInfo.ascx
The Clear Cache button is very close to the Restart Rock button. Sometimes while clearing cache I maybe click a little too hastily. This makes everyone sad. So, I added a confirmation before restarting.
I added a new link and used CSS to hide the normal asp button. Then updated the javascript to request a confirmation before manually performing a postback on the original now hidden button.
=> Added confirmation before restarting Rock.

Rock/Utility/ExcelHelper.cs
Modified the excel export to use table styles instead of conditional formatting to create the banded rows. I chose "Medium4" as the table style because it is the closest visually to the current look.
Fixes: #3267 
If your pull request requires a migration, please *exclude the migration from the Rock.Migration project*, but submit it with your pull request. Please add a note to your pull request that provides a heads up that a migration file is …
=> - Modified Excel export to use table styles (Fixes #3267)

Rock/Model/History.cs, Rock/Model/UserLogin.cs
We wanted to have user login information logged to History. So I added logging to the pre and post save to the Entity table.
Fixes: #2936 
=> Added history to userlogins Fixes #2936

RockWeb/Blocks/Reporting/ServiceMetricsEntry.ascx.cs
Adds new block setting to Service Metrics Entry block that allows to filter available campuses based on selection. If no campuses are selected (default value) then all campuses are available - which preserves the current behavior.
Fixes: #3692
=> Added ability to limit Service Metrics Entry block to specific campuses

Rock/Jobs/ProcessBIAnalytics.cs
Fixes a an error that gets thrown while executing the update queries checking for nulls or empty strings when the column type is different than a varchar.
Also added logic to check for null parameters being passed to the SQL command so these are passed as DBNull.values.
The ProcessBIAnalytics job would fail to execute when processing non text/varchar attributes.
These code changes fix the null comparison performed on the update queries for any data type.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
=> Fixes update queries

RockWeb/Blocks/Utility/InternalCommunicationView.ascx.cs
The internal communication view block caches an object whose class is in the code behind for the block. Because this code is compiled as a different binary for each server, only the server that stored the cached item can retrieve it; any other server in a distributed solution would throw an exception. This PR serializes the data in JSON before caching.  
I haven't run across any other blocks that cache objects derived from classes in the code …
=> Fixed exception when running redis cache

Rock.Mailgun/Communication/Transport/MailgunHttp.cs
The MailgunHTTP transport has an issue due to it testing the FromAddress and FromName for null or empty _before_ it merges the lava. This means that if the lava is merged to be an empty string it will continue through and have no value. Later on this will throw an exception. We noticed this problem after forgetting to set the contact on a registration instance and registrants failed to receive their confirmations.
This change first renders the lava and then tests for blank values. 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to …
=> MailgunHTTP: Fixed out of order setting and testing of from information

Rock.Mailgun/Communication/Transport/MailgunHttp.cs, Rock/Communication/SMTPComponent.cs
While working on the problem with MailgunHTTP I noticed an additional problem where the from addresses were being saved incorrectly. This is caused by a simple typo.
=> Fixed incorrect arguments in SaveCommunicationTransaction

Rock/Jobs/DataAutomation.cs
A fix to the data automation job so that it correctly calculates when a campus was manually updated recently. We found that the job wasn't observing the rule we set because it was misreading the history table. This mainly changes the entity type from person to group.
Tested with real data to make sure it both updates and ignores according to the rules.
=> Fixed data automation job to not update recently updated campuses

RockWeb/Blocks/Reporting/PowerBiReportViewer.ascx.cs
The block settings for what panes to show were not being read until the settings page was opened. That was causing the block to always use the defaults (false).
Fixes: #3887 
I am fairly certain that this PR will fix the issue and have no negative side effects. However, I do not have access to PowerBi server to test against. I did test with a dummy report, and the resulting urls are in the expected format.
=> Fixed PowerBiReportViewer not respecting settings for hiding panes

RockWeb/Blocks/Cms/ContentChannelItemDetail.ascx, RockWeb/Blocks/Cms/ContentChannelItemDetail.ascx.cs
**The issue:** 
When "Child Items Manually Ordered" is enabled (within Content Channels) the "Child Items" would not be sorted correctly when it was manually sorted. In other words, when a person tries to sort any "Child Items" (by click-drag-and-releasing the hamburger icons), then the child items on the site/client side of Rock would not reflect the order it was supposed to be in.
**What was expected instead:** 
Content Channel "Child Items" that are manually sorted was supposed to be saved as sorted.
**The Solution:**
The "Child Items" needed to be sorted by the "Order" through the Content Channel Item Association/join table; not by the "Priority" of the Content Channel Item itself.
**Here's what I did.**
As it turns out, the Child Items were sorted by the Content Channel Item itself - …
=> Fixed content channel item ordering. Fixes #2522

RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
Sanitize the HTML before doing a Empty/Null check on the instructions. This catches cases such as empty paragraph tags that creep into the HTML editor when attempting to delete the contents.
Fixes: #3937
For testing I created 3 registration instances. One with real content in the instructions, one with "psuedo" blank content (that is typed something, left field, went back to the field and erased - which left `<p><br></p>` in the raw instructions), …
=> - Fixed blank instruction page in Event Registration. (Fixes #3937)

Rock/Model/GroupMember.cs
The `IsArchived`, `ArchivedDateTime`, and `ArchivedByAliasPersonId` filters didn't work as expected because archived group members are ignored in reporting. This PR hided the filters from reporting so that they don't confuse users as to why no results are returned.
Fixes: #3933
=> Removed dataview filters related to archived group members

RockWeb/Blocks/Reporting/SqlCommand.ascx, RockWeb/Blocks/Reporting/SqlCommand.ascx.cs
When I am building a custom SQL query for a Dynamic Report block or something, I often use the Sql Command block/page to build the actual query first. It's faster, I don't have to go in and out of edit mode etc. while getting the query itself to work.
Many times while doing this I also want to know how long the query takes. Primarily for performance reasons, I want to make sure I'm not building a query that is taking 3 seconds when I'm expecting it to only take a few milliseconds. Because of postback overhead, it's often hard to tell how long the query itself is taking.
This adds new UI elements to the Sql Command block that informs the user how long the query or command took to execute.
(new …
=> Added timing information to Sql Command block.

Rock/Field/SelectFromListFieldType.cs
After updating from 8.9 to 9.3, I edited the rightmost badge block on the Person profile page and only one badge was checked in the block settings despite there being multiple badges displaying. When I hit save, all but that one disappeared.
It turned out that the attribute value had guids separated by a comma and space, but this control only allowed commas as delimiters.  At least one of these extraneous spaces was added by the migration to add the Assessments badge at this line:
https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Migrations/Migrations/Version%209.0/Version%201.9.0/201906192243232_Rollup_0618.cs#L267
I confirmed that the checkbox problem on that badge block was also happening on the demo site.
_Put an `x` in …
=> - Fixed bug that prevented proper selection of all stored values if they were delimited by more than just a single comma

Rock/UniversalSearch/IndexComponents/Lucene.cs
We are working on moving to a clustered environment. As part of that we came up with the solution of using virtual directories for App_Data and Content. This works correctly with most things, however Lucene only places files on the absolute directory and not on the virtual. This change switches methods for mapping the file location so it is compatible with absolute and virtual directories.
=> Fixed Lucene path mapping to work with virtual directories

Rock/Web/Cache/Entities/CampusCache.cs
As we are continuing to work on our clustered environment we have discovered that CampusCache does not keep the Order instead returning 0. This caused a few of our pages to change in undesirable ways. The fix for this is just adding the DataMember attribute to the property so it gets serialized.
=> Fixed campus order not being cached in Redis

RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
We had an issue with our custom registration entry block throwing exceptions. We located the cause of the issue and notice the same issue was in core. A null check for the FeeValue list was incorrectly checking the Fee instead. If the Fee was null at this point it would have already thrown an error, but the FeeValue can be null.
=> Fixed null reference check

Rock/Workflow/Action/Utility/SetEntityProperty.cs
Extend SetEntityProperty to enable it to set entity properties that are nullable enums (like ConnectionRequest.AssignedGroupMemberStatus).
Fixes: #
_Put an `x` in the boxes that apply. You can also fill these out after creating the …
=> Workflow.Action.Utility.SetEntityProperty: Set Nullable Enum

RockWeb/Blocks/Event/RegistrationEntry.ascx.cs
We had some problems where people who were registering to a wait list threw an exception if the registration has a signature document.  What happens is the form for the document doesn't exist if they are on the wait list, but then it tries to show it anyway. This checks to see if the form exists before we try to show it.
We've been running this for a few months and it has fixed our issues.
=>  Fixed bug where inline legal forms would cause errors with waitlists

Rock.Tests/Rock/Lava/RockFiltersTests.cs, Rock/Lava/RockFilters.cs
Submitting this on behalf of @cbump.
This enhancement is to add the lava filter "RegExMatchValues". It works like "RegExMatchValue" except that instead of returning a string of the first match it returns all of the matches in a list. Originally, Chuck submitted this as a modification of "RegExMatchValue" and was asked to change it into a new tag.
Tests the input against a Regular Expression and returns an array of the matching substrings.
Example: …
=> Added lava regex with multiple matches

Rock/Web/UI/Controls/Pickers/CategoryPicker.cs, Rock/Web/UI/Controls/Pickers/ItemPicker.cs, RockWeb/Scripts/Rock/Controls/itemPicker.js, RockWeb/Scripts/Rock/Extensions/rockTree.js
Adds support to `treeView.js` for prefixing item Id numbers if they are categories. This allows the `ItemPicker` control to differentiate between selecting a category and selecting an item. See https://github.com/SparkDevNetwork/Rock/issues/1632#issuecomment-581580802 for full discussion of the exact changes.
Basically, …
=> Fixed bug with pickers and collision of Id numbers

RockWeb/Webhooks/TextToWorkflowTwilio.ashx, RockWeb/Webhooks/Twilio.ashx, RockWeb/Webhooks/TwilioSms.ashx
Twilio was logging an error every time a message was received if Rock didn't send an immediate reply. Messages still send and receive fine, but the constant errors logged in Twilio console make troubleshooting anything else more difficult.
Here is the full text of the error that gets logged:
```
Warning - 14103
Message Invalid Body
The Message body does not contain valid text or a media URL
```
According to Twilio's docs, they expect an empty response element (`<Response />`) from the webhook when there is no response to send. For the pipeline webhook, Rock was sending an empty message body instead (`<Response><Message /></Response>`). For both the workflow and legacy Twilio webhooks, Rock was sending plain-text instead of Twiml.
This PR updates all 3 Twilio webhooks to return a proper …
=> Fix "Invalid Body" warning from Twilio when no response is returned from the webhook

Rock.Migrations/Migrations/202002111831294_AddFundraisingAllowDonationsUntil.cs, RockWeb/Blocks/Fundraising/FundraisingDonationEntry.ascx.cs, RockWeb/Blocks/Fundraising/FundraisingOpportunityView.ascx.cs
This PR replaces #3674.
Adjusts the Fundraising Donation Entry block to use a new `Allow Donations Until` attribute value which specifies the last day to accept donations towards group members.
Adjusts the Fundraising Opportunity View block to use a new `Allow Donations Until` attribute value which specifies the last day to accept donations towards group members.
IMPORTANT: The above two statements are slightly misleading, but there is a reason for explained below in further comments.
Included migration (not referenced in project file) to perform the following steps:
1. Add new Group attribute `Allow Donations Until` to Fundraising Opportunity group type.
2. Set order on `Allow Donations Until` to make it appear directly after `Financial Account`.
3. Set order on subsequent attributes so …
=> + Added new Allow Donations Until date on fundraising opportunities. (Fixes #3438)

Rock/Web/UI/RockPage.cs
Fixes: #4115 
Updated ResolveRockUrlIncludeRoot to use https if WebRequestHelper.IsSecureConnection() returns true, otherwise uses previous behavior. 
I'm a python developer that uses mac/linux. I setup a windows machine and installed VS just to track down this issue today. Can't get the project to build (VS fails, but then shows 0 errors).
Would love to add/run test for this, but I also have no idea how to do that yet.
Submitting this PR …
=> + Fixed issue where urls were generated with http even though site is loaded over https.

RockWeb/Blocks/Communication/EmailPreferenceEntry.ascx.cs
We wanted an ability to launch a workflow whenever a person unsubscribes from a list.  We wanted to be able to alert the staff and take the appropriate actions automatically whenever a person unsubscribes.  This PR will add a workflow type field to the block settings that isn't required.  After the communication lists to unsubscribe from are chosen and the submit button is clicked on, the workflow type if chosen will be used to get the workflow and launch it.
**Here's what I did:**
I updated the EmailPreferenceEntry.ascx.cs code to include a workflow type field block attribute and used its guid in the click event of the submit button only if the unsubscribe radio button is checked.  The guid is used to get the workflow type cache that is passed to a method I called StartWorkflow that …
=> Update Email Preference Entry

Rock.Rest/Controllers/MetricsController.partial.cs
This change simply surfaces the value and date of the previous metric value to the lava of the liquid dashboard widget, for determining comparisons.
=> Added previous metric date and value to metrics controller for comparisons/trends

RockWeb/Blocks/Groups/GroupDetail.ascx.cs
In the Rock 1.10.3 version of the group detail block the group type drop down list currently shows the applicable group types children of the parent's parent instead of children of the parent. (That's a mouth full.) We noticed this AFTER we pulled in the fix for #4217. This fixes the typo that fixed the typo.
=> Fixed incorrect data source for grouptype drop down list

Rock/Web/UI/Controls/Grid/RockLiteralField.cs, Rock/Web/UI/Controls/Grid/RockTemplateField.cs
This changes the GetExportValue method of the Rock Literal Field and the Rock Template Field to turn `<br>'s` to `\r\n` before stripping the HTML. The intention is to fix the issue with addresses and other html formatted content to export values more similarly to what is expected.
Fixes: #4226
I opted to insert .ConvertBrToCrLf() before the .StripHtml(). This was as drastic as I wanted to get in this PR.
=> Added missing new lines in excel cells. 

RockWeb/Blocks/Communication/CommunicationDetail.ascx.cs
Before 10.2 fixed the slow load times of the recipient list, that list timing out prevented a large communication from being approved for sending. Although timeouts are less likely now, the error should still be handled.
This change will allow a message with a large recipient list to still be approved even if it times out when loading.
=> - The Communication Detail screen will no longer fail to load if the recipient list times out.

Rock/Utility/ExtensionMethods/LinqExtensions.cs
Solution for #4332 where the attributeValue EntityId was trying to match on the wrong entity type. I added a check to see if the source entity and attribute entity type were the same, if they are not I search the source entity for property of the same type as the attribute entity type and same the property information as …
=> + Fixes incorrect sorting on Attribute Values in LinqExtensions (Fixes #4332)

Rock/Data/Entity.cs, Rock/Web/UI/RockPage.cs, RockWeb/Blocks/Crm/PersonDetail/GroupMembers.ascx.cs
With security becoming more and more a concern these days, we wanted to stop using Id numbers for our Context URL values in certain places. For example, in our Small Group Locator pages, we want to use an HTML block to display additional information about the group passed in the URL. This is currently passed by Id number …
=> Added ability to specify Entity Context URL values by Guid.

Rock/Web/UI/Controls/Pickers/GradePicker.cs
This fixes the graduation year in GradePicker on the date of the grade transition.
It's currently inconsistent with the doc ("transition occurs at the end of the specified date") and the graduation year to grade conversion elsewhere:
https://github.com/SparkDevNetwork/Rock/blob/689e6a5f7e6fd7781e0963028242fe92f97e55e7/Rock/Utility/RockDateTime.cs#L298
Fixes: #4533
=> Fix incorrect graduation year on GradeTransitionDate

RockWeb/Webhooks/Twilio.ashx, RockWeb/Webhooks/TwilioSms.ashx
This commit (https://github.com/SparkDevNetwork/Rock/commit/35415fe4a45612ae8ad4b5288e1fbfe2a77249e5) reintroduced an old bug that causes Twilio to log an error every time a message Is received if Rock doesn't send an immediate reply. Messages still send and receive fine, but the constant errors logged in Twilio console make troubleshooting anything else more difficult.
Here is the full text of the error that gets logged:
```
Warning - 14103
Message Invalid Body
The Message body does not contain valid text or a media URL
```
According to Twilio's docs, they expect an empty response element (`<Response />`) from the webhook when there is no response to send, but Rock was sending an empty message body instead (`<Response><Message /></Response>`). 
This PR updates both Twilio webhooks to …
=> Update Twilio webhooks to avoid "Invalid Body" warnings from Twilio

RockWeb/Blocks/Finance/BenevolenceRequestDetail.ascx, RockWeb/Blocks/Finance/BenevolenceRequestDetail.ascx.cs
Hello, 
There was a need to add attributes to Benevolence Results. This is a PR to add UI to the Benevolence Request Detail block to allow this functionality.
I would categorize this as an enhancement. It adds non-breaking functionality and very minor bug fixes.
Because this block stores the Benevolence Result changes in the view state using the BenevolenceResultInfo POCO, I needed it to inherit IHasAttributes to work with the existing UI helpers. I implemented the interface and added the necessary UI for the attributes. Attributes that are marked "Show In Grid" will display in the results grid. I used a mock instance of BenevolenceResult to load the attributes for the UI as needed.
Additionally while working on this I did some minor fixes:
-  The grid was set to allow sorting, but it was …
=> Added ui for benevolence result attributes and other fixes

RockWeb/Blocks/Event/RegistrationInstanceGroupPlacement.ascx, RockWeb/Blocks/Event/RegistrationInstanceGroupPlacement.ascx.cs
When selecting placement groups, there is only an option to select one group at a time or all the groups under a parent group. We would like to be able to quickly select multiple groups that aren't necessarily under the same parent group.
This change was a big help for our church's 2021 camp season, as it greatly reduced the amount of time required to configure placement groups.
=> Changed single-select to multi-select in group placement group picker.

Rock/CheckIn/KioskGroupType.cs
While testing 1.12.5 with a Redis cache I noticed that check-in would not stay open. If I switched back to memory cache it would work, but not with Redis. I tracked this down to an optimization in cache that lost it's data on serialization. The fix was to just change what data is serialized by moving the [DataMember] decoration. I tested this with and without redis and it seems to have fixed the issue. 
=> Fixed issue where redis cached servers lost grouptype ref

Rock.Lava/Filters/Generic/TemplateFilters.DatesAndTimes.partial.cs, Rock.Tests.UnitTests/Rock/Lava/Filters/DateFilterTests.cs
New lava filter to determine if a target datetime falls within a given range of two other datetimes. 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
=> + (Lava) Added a new lava filter to determine if date falls within a range

Rock/Attribute/BenevolenceTypeFieldAttribute.cs, Rock/Field/Types/BenevolenceTypeFieldType.cs, Rock/Rock.csproj, Rock/Workflow/Action/Finance/BenevolenceRequestAdd.cs
The "Benevolence Request Add" workflow action was failing with a foreign key exception because it wasn't setting any value for the new (added in v13) BenevolenceTypeId property. This issue just showed up in v13.4 because the presave hook that was setting a default value [was …
=> Fixed "Benevolence Request Add" action to prompt for Benevolence Type.

RockWeb/Blocks/Core/CampusDetail.ascx.cs
Fixes: #5127 
The campus editor block was not correctly loading the values for the defined values picker for campus schedule types. The only option available was the default "Weekend Service" even though there were additional defined values.
The issue was because the pickers are assigned a DefinedTypeId in `LoadDropDowns` …
=> Fixed Schedule Type Dropdown not loading values on Campus Detail Block

Rock.JavaScript.Obsidian.Blocks/src/Crm/PersonDetail/badges.ts
In v13 and below tooltips on badges were set to display HTML by default. In the v14 Obsidian rewrite of the person profile page's badge block, you have to manually enable HTML on a per-badge basis with `data-html="true"`. 
This PR restores the pre-v14 functionality.
Fixes: #5263 
What types of changes does your code …
=> Update Obsidian badges block to display HTML in tooltips by default

Rock.JavaScript.Obsidian.Blocks/src/Event/RegistrationEntry/registrant.partial.ts
This fixes an issue where the Obsidian Registration Entry block was unable to display group member attribute fields. This meant that any group member attribute on a registration was not able to be filled out or edited. Instead of showing the field, the block would show an alert that said "Could not resolve field source 2". …
=> Fixed an issue in Obsidian Registration Entry where group member attribute fields were not being resolved

Rock.JavaScript.Obsidian.Blocks/src/Event/RegistrationEntry/utils.partial.ts
This fixes an issue where the Obsidian Registration Entry block would use the value of the first field as the registrant's First Name in the progress bar instead of using the value of the First Name field.
This fixes this by adding an additional constraint to the function that finds the First Name field so that it can only …
=> Fixed an issue in Obsidian Registration Entry where the progress bar was using the wrong field for first name

RockWeb/Themes/Rock/Assets/Lava/GroupHistoryTimeline.lava
This fixes an issue in the Group History Timeline lava template where there would not be a space between the date and the year on section headings. This fixes that issue by appending a comma and space to the beginning of the year in order to follow date formatting conventions. Appending this to the beginning of the year means that the comma and space will only be shown if the year is.
**Before this fix:**
**After this fix:**
Fixes: #5826 
=> Fixed a Formatting on the Group History Timeline Lava Template

Rock.Lava/Filters/Generic/TemplateFilters.DatesAndTimes.partial.cs, Rock.Tests.UnitTests/Rock/Lava/Filters/DateFilterTests.cs
**In case you are submitting a non bug-fix-PR, we highly recommend you to engage in a PR discussion first.**
There are many factors we consider before accepting a pull request. This includes:
1. Whether or not the Rock system you run is a standard, main-line build. If it is not, there is a lower chance we will accept your request since it may impact some other part of the system you don't regularly use.
2. Features that would be used by less than 80% of Rock organizations, or ones that don't match the goals of Rock.
With the PR discussion we can assess your proposed changes before you start working on it so that we can come up with the best possible approach to it. This may include:
1. Coming up with an alternate approach that does not involve changes to core.
2. Advising how your …
=> Add Weekly to DateDiff Lava filter

RockWeb/App_Code/GetQRCode.ashx.cs
https://community.rockrms.com/ideas/2009/allow-customizable-colors-for-qr-codes
This change allows for RGBA hex values in the QR Code generator. These values can come in as RRGGBB, or RRGGBBAA hex values.
- [x ] This is a single-commit PR. (If not, please squash your commit and re-submit it.)
- [ x] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [ x] I have read the …
=> Update GetQRCode.ashx.cs to allow RGBA values
